//! Refs page — built via the `docs!` macro.

use docs_macro::docs;
#[allow(unused_imports)]
use crate::shell::{codeblock, pageheader, CodeBlockProps, PageHeaderProps};
#[allow(unused_imports)]
use idea_ui::{body, card, heading, stack};

docs! {
    slug = "refs",
    title = "Refs",
    category = Reference,
    description = "Programmatic handles to mounted primitives and components.",
    related = ["components", "primitives", "navigation", "overlays-and-animation"],
    concepts = [Ref, Handle, ComponentMethods],

    section(heading = "Overview") {
        p("A ", code("Ref"), " is how you get a programmatic handle to a mounted thing \
           — a button, a view, a custom component — so you can call methods on it \
           imperatively. You'll reach for one whenever you need to trigger an action \
           on the thing rather than describe it through reactive state."),
        p("The most common case isn't a built-in primitive. It's giving a component \
           you wrote an imperative surface — \"reset this form,\" \"scroll this list \
           to the top,\" \"focus this input,\" \"play this animation\" — and calling \
           it from a parent. This page leads with that pattern because it's the one \
           app code actually uses every day."),
    },

    section(heading = "The two flavors") {
        p("Refs come in two shapes:"),
        list(
            ["Component refs — a handle to one of your own ", code("#[component]"),
             " functions, generated by its ", code("methods!"), " block. Used to \
              call imperative methods you declared on the component."],
            ["Primitive refs — a handle to a built-in primitive (", code("ButtonHandle"),
             ", ", code("ViewHandle"), ", etc.). Used to trigger a click, read a \
              frame, scroll a list to the top."],
        ),
        p("The mechanics are the same in both cases. A ", code("Ref<H>"),
          " is a slot, ", code(".bind(ref)"), " attaches it to the mounted thing, ",
          code(".with(|h| ...)"), " calls into the handle. The two flavors differ \
           only in what the handle exposes."),
    },

    section(heading = "Component refs") {
        p("This is the pattern you'll reach for most. A parent component wants to \
           imperatively trigger something inside a child — reset a form, scroll a \
           list, focus an input, play an animation. Instead of routing the action \
           through a prop and a signal flip, the child exposes the action as a \
           method and the parent calls it directly."),
    },

    section(heading = "Declaring methods on a component") {
        p("Inside a ", code("#[component]"), " function body, a ", code("methods!"),
          " block declares the imperative methods the component exposes:"),

        code(rust, r##"
            use framework_core::{component, signal, ui, Bindable, Primitive};

            pub struct CounterProps {
                pub initial: i32,
            }

            #[component]
            pub fn counter(props: &CounterProps) -> Bindable<CounterHandle> {
                let value = signal!(props.initial);

                methods! {
                    fn reset(&self) {
                        value.set(0);
                    }
                    fn bump_by(&self, n: i32) {
                        value.update(|v| *v += n);
                    }
                    fn set_to(&self, n: i32) {
                        value.set(n);
                    }
                }

                ui! {
                    View {
                        Text { format!("Count: {}", value.get()) }
                    }
                }
            }
        "##),

        p("Three things change versus a regular component:"),
        list(
            ["The ", code("methods!"), " block declares the imperative surface. \
              Each method takes ", code("&self"), " and zero or more typed \
              parameters, and runs against captures from the component's scope — \
              here, the ", code("value"), " signal."],
            ["The return type is ", code("Bindable<CounterHandle>"), " instead of ",
             code("Primitive"), ". The macro derives the handle name from the \
              function name (", code("counter"), " → ", code("CounterHandle"),
             "), so you don't write the struct yourself."],
            ["The framework generates ", code("CounterHandle"), " with one method \
              per declared ", code("fn"), ". Calling ", code("handle.bump_by(5)"),
             " invokes the closure body that captured ", code("value"),
             ", runs in the component's scope, and updates the signal. Cascades \
              fire normally."],
        ),
        p("Method bodies have access to anything captured from the surrounding \
           scope — signals, closures, other refs. Writes propagate through the \
           reactive substrate exactly the way they would if the same write happened \
           inside an ", code("on_click"), "."),
    },

    section(heading = "Capturing the handle in a parent") {
        p("The parent allocates a ", code("Ref<CounterHandle>"),
          " and binds it to the child:"),

        code(rust, r##"
            use framework_core::Ref;

            #[component]
            pub fn parent_app() -> Primitive {
                let counter_ref: Ref<CounterHandle> = Ref::new();

                ui! {
                    counter(initial = 10).bind(counter_ref)

                    Button(
                        label = "Reset",
                        on_click = move || { counter_ref.with(|h| h.reset()); },
                    )

                    Button(
                        label = "Add 5",
                        on_click = move || { counter_ref.with(|h| h.bump_by(5)); },
                    )
                }
            }
        "##),

        p("What happens at runtime:"),
        list(
            [code("Ref::new()"), " allocates a slot in the parent's scope. The slot \
              is empty."],
            ["The framework mounts the counter. When the child's body has finished \
              running and the handle has been constructed, the framework fills ",
             code("counter_ref"), "'s slot."],
            ["Before mount, ", code("counter_ref.with"), " returns ", code("None"),
             " silently. After mount, it runs the closure with the handle."],
            ["Calling ", code("handle.bump_by(5)"), " invokes the captured closure, \
              which updates ", code("value"), ". The reactive text inside the \
              counter re-runs and updates on screen."],
        ),
    },

    section(heading = "Sibling-to-sibling through a parent") {
        p("Two children of the same parent can talk to each other through a ref \
           the parent holds:"),

        code(rust, r##"
            let target: Ref<CounterHandle> = Ref::new();

            ui! {
                counter(initial = 0).bind(target)

                Button(
                    label = "Set target to 100",
                    on_click = move || { target.with(|h| h.set_to(100)); },
                )
            }
        "##),

        p("The button doesn't know about the counter directly — it knows about the \
           ref. The ref is the wire that threads imperative reach across the tree."),
    },

    section(heading = "Method vs signal prop — when to pick which") {
        p("A natural question: \"Should ", code("reset"), " be a method, or should \
           I take a ", code("Signal<bool>"), " prop the parent flips to trigger \
           reset?\""),
        p("The method wins when:"),
        list(
            ["The action is genuinely fire-and-forget — \"do this thing now.\""],
            ["Multiple call sites need to invoke it from different points in the \
              tree."],
            ["The action involves more than just changing one piece of state — \
              focus shifts, animations, scroll position changes."],
        ),
        p("The signal wins when:"),
        list(
            ["The trigger is itself a piece of state worth observing."],
            ["Sibling components also care about the same state and should react \
              to it."],
        ),
        p("In practice, most apps mix both: signals for state that drives UI, \
           methods for actions the parent dispatches."),
    },

    section(heading = "Primitive refs") {
        p("The framework's built-in primitives expose handles the same way. Same \
           shape — allocate a ", code("Ref<H>"), ", bind, call methods:"),

        code(rust, r##"
            let btn: Ref<ButtonHandle> = Ref::new();

            ui! {
                Button(label = "Original", on_click = on_click).bind(btn)

                Button(
                    label = "Trigger the original",
                    on_click = move || { btn.with(|h| h.click()); },
                )
            }
        "##),

        p("The handle types you'll meet, with the most-used method per handle:"),
        list(
            [code("ButtonHandle"), " — ", code(".click()"), " fires the press"],
            [code("PressableHandle"), " — ", code(".click()"), " fires the press"],
            [code("ViewHandle"), " — ", code(".frame()"), ", ",
             code(".absolute_frame()"), " for geometry"],
            [code("LinkHandle"), " — ", code(".click()"),
             " for trigger-on-keystroke patterns"],
            [code("NavigatorHandle"), " / ", code("TabsHandle"), " / ",
             code("DrawerHandle"), " — navigation commands (covered in Navigation)"],
            [code("IconHandle"), " — start a stroke animation imperatively"],
            [code("OverlayHandle"), " / ", code("AnchoredOverlayHandle"), " / ",
             code("PresenceHandle"), " — overlay control"],
        ),
        p("The rest (", code("TextHandle"), ", ", code("ImageHandle"), ", ",
          code("TextInputHandle"), ", ", code("ToggleHandle"), ", ",
          code("SliderHandle"), ", ", code("WebViewHandle"), ", ",
          code("VideoHandle"), ", ", code("ActivityIndicatorHandle"), ", ",
          code("VirtualizerHandle"), ", ", code("GraphicsHandle"),
          ") exist but their method surfaces are still being filled in. New \
           operations land on those traits without app code needing to change."),
    },

    section(heading = "Reading geometry") {
        p("The most common primitive-ref use is reading a view's bounding rect:"),

        code(rust, r##"
            let row: Ref<ViewHandle> = Ref::new();

            ui! {
                View { /* content */ }.bind(row)

                Button(label = "Where am I?", on_click = move || {
                    if let Some(rect) = row.with(|h| h.frame()).flatten() {
                        println!("row is at {:?}", rect);
                    }
                })
            }
        "##),

        p("Two methods:"),
        list(
            [code(".frame()"), " — rect in the parent's coordinate system"],
            [code(".absolute_frame()"), " — rect in viewport (window) coordinates"],
        ),
        p("Both return ", code("Option<ViewportRect>"), " because layout might not \
           have happened yet, or the backend might not expose geometry. Backends \
           that do: web (", code("getBoundingClientRect"), "), iOS (",
          code("UIView.frame"), " + ", code("UIView.convert"), "), Android (",
          code("View.getLocationOnScreen"), ")."),
    },

    section(heading = "Anchoring overlays") {
        p(code("ButtonHandle"), ", ", code("PressableHandle"), ", and ",
          code("ViewHandle"), " all implement the ", code("AnchorableHandle"),
          " trait. ", code("AnchoredOverlay"),
          " reads it to position itself relative to the anchor:"),

        code(rust, r##"
            let trigger: Ref<ButtonHandle> = Ref::new();
            let is_open = signal!(false);

            ui! {
                Button(
                    label = "Open menu",
                    on_click = move || is_open.update(|v| *v = !*v),
                )
                .bind(trigger)

                if is_open.get() {
                    AnchoredOverlay(
                        target = trigger,
                        side = ElementSide::Below,
                        align = ElementAlign::Start,
                    ) {
                        // menu content
                    }
                }
            }
        "##),

        p("The overlay tracks the anchor through scrolls, layout shifts, and \
           orientation changes — same rect machinery as ", code(".absolute_frame()"),
          ", read continuously."),
    },

    section(heading = "The Ref<H> API") {
        code(rust, r##"
            let r: Ref<H> = Ref::new();

            r.with(|h| h.some_method());      // Option<R> — runs the closure if mounted
            r.is_mounted();                    // bool
            r.get();                           // Option<H> — clone of the handle if mounted
        "##),

        p("A ", code("Ref<H>"), " is a ", code("Copy"), " token, same shape as ",
          code("Signal<T>"), ". Pass it into closures, into child components, \
           anywhere, without ", code(".clone()"),
          ". The token indexes into the reactive arena; the storage is shared."),
        p("Allocate refs early — typically right at the top of a component — and \
           bind them inline in the ", code("ui!"), " block. The slot stays empty \
           until the primitive (or component) mounts."),
    },

    section(heading = "Binding via .bind") {
        p("Every primitive's builder and every ", code("Bindable<H>"),
          "-returning component exposes ", code(".bind(ref)"), ":"),

        code(rust, r##"
            View { ... }.bind(view_ref)
            Button(label = "...", on_click = ...).bind(button_ref)
            ScrollView { ... }.bind(scroll_ref)
            counter(initial = 0).bind(counter_ref)
            Navigator::new(&HOME).screen(...).bind(nav_ref)
        "##),

        p("The handle type has to match the primitive (or component) kind — ",
          code(".bind"), " is type-checked. Passing a ", code("Ref<ButtonHandle>"),
          " to a View's ", code(".bind"), " is a compile error."),
    },

    section(heading = "Lifecycle") {
        p("A ref's slot is empty until the primitive mounts. Between ",
          code("Ref::new()"), " and the first mount, ", code(".with"), " returns ",
          code("None"), " and ", code(".is_mounted()"), " is ", code("false"),
          ". Once mounted, the slot stays filled until the primitive unmounts \
           (its scope drops). After unmount, the slot empties."),
        p("Reactive subtrees produce common lifecycle cases:"),
        list(
            ["A ref bound to a primitive inside a ", code("when()"),
             " — the slot empties when the condition flips false, fills again when \
              it flips back."],
            ["A ref allocated inside a screen's scope — when the screen pops, the \
              slot is freed along with everything else in that scope."],
        ),
        p("You don't have to handle these explicitly. ", code(".with"), " returns ",
          code("None"), " rather than panicking when the slot is empty, and the \
           lifecycle is owned by the scope, not by you."),
    },

    section(heading = "Refs vs Signals") {
        p("Two distinctions worth keeping straight:"),
        list(
            [code("Signal<T>"), " — reactive state. Reads inside tracked contexts \
              subscribe; writes notify subscribers. Use for anything that changes \
              over time and drives UI."],
            [code("Ref<H>"), " — an imperative handle slot. Filled at mount, \
              emptied at unmount. Reading it doesn't subscribe to anything. Use \
              to invoke methods on a mounted thing."],
        ),
        p("Both live in the reactive arena and share the ", code("Copy"),
          "-token shape. They solve different problems and coexist freely — you'll \
           often fire a ref-driven action from inside a signal-driven event \
           handler."),
    },

    section(heading = "Where to read more") {
        list(
            ["Components — ", code("methods!"),
             " blocks and the full component-handle generation rules."],
            ["Navigation — ", code("NavigatorHandle"), ", ", code("TabsHandle"),
             ", ", code("DrawerHandle"), " and their command surfaces."],
            ["Overlays and animation — ", code("AnchoredOverlay"),
             "'s anchoring model."],
            ["Primitives — the full list of primitive handle types."],
        ),
    },
}
