//! # scene-parity — structural-op golden-record harness
//!
//! Pins the EXACT sequence of **structural** backend operations the
//! runtime emits for a fixed set of reactive scenarios, as golden files
//! frozen from the pre-runtime-v2 walker. The scene core
//! (`runtime-scene` + `runtime-vocabulary`) must keep reproducing those
//! sequences — see `README.md` for the contract and the closed set of
//! places where a deliberate divergence is allowed.
//!
//! Three pieces:
//!
//! - [`new_core::SceneHost`] — a `runtime_scene::Host` that records ONLY
//!   the 7 structural ops (`insert`, `insert_many`, `insert_at`,
//!   `remove_child`, `clear_children`, `create_anchor`, node creation)
//!   into an ordered, human-readable log. Prop/style updates are
//!   deliberately invisible: structure parity is the gate, and ignoring
//!   the rest keeps the goldens stable across style churn. Node names
//!   are `n0, n1, …` in creation order.
//! - [`scenarios_new::NewScenario`] + [`new_core::NewCx`] — a scenario
//!   builds a tree, then performs scripted signal mutations,
//!   snapshotting the op log after each step.
//! - [`new_core::check_new`] — runs a scenario in a given [`Mode`] and
//!   diffs the serialized steps against `goldens/<name>.<mode>.golden`
//!   (or the sanctioned `goldens_newcore/` override).
//!
//! The FULL-OP suite lives in [`full`] + [`full_new`] +
//! [`scenarios_full_new`]: a recorder that logs the COMPLETE
//! backend-call stream (create/update/style/release calls, not just
//! structure), pinning the vocabulary handlers against the same frozen
//! `goldens_full/` corpus. See README §"The FULL-OP suite".
//!
//! ## The goldens are frozen testimony
//!
//! The golden files were generated by the OLD walker before it was
//! deleted. There is no way to regenerate them from it any more: a
//! re-baseline can only record the CURRENT implementation's output,
//! which permanently discards the old core's testimony. Treat an edit to
//! a golden as the substance of a change, and never make one to turn a
//! red test green.

use std::cell::RefCell;
use std::fmt;
use std::path::PathBuf;
use std::rc::Rc;

pub mod full;
pub mod full_new;
pub mod scenarios_full_new;

pub mod new_core;
pub mod scenarios_new;

// ===========================================================================
// Node + Recorder
// ===========================================================================

/// The recording backend's node: a creation-order index. `n0` is the
/// first node the walker asked the backend to create, `n1` the second, …
/// Deterministic across runs (single-threaded, synchronous walker).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct PNode(pub u32);

impl fmt::Display for PNode {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "n{}", self.0)
    }
}

#[derive(Default)]
struct RecorderInner {
    next_id: u32,
    ops: Vec<String>,
}

/// Shared, ordered op log + monotonic node-id counter. Cloning is an
/// `Rc`-clone: the backend, the harness, and any scenario-registered
/// cleanup hooks all append to the same log.
#[derive(Clone, Default)]
pub struct Recorder {
    inner: Rc<RefCell<RecorderInner>>,
}

impl Recorder {
    pub(crate) fn mint(&self) -> PNode {
        let mut inner = self.inner.borrow_mut();
        let id = inner.next_id;
        inner.next_id += 1;
        PNode(id)
    }

    pub(crate) fn push(&self, op: String) {
        self.inner.borrow_mut().ops.push(op);
    }

    /// Scenario-visible marker: a scope cleanup fired. Scenarios register
    /// these via `runtime_core::on_cleanup` inside a branch/row scope so
    /// the goldens pin *dispose ordering* relative to the structural ops
    /// (e.g. "remove_child BEFORE the row's cleanup" in `each`'s unmount,
    /// "cleanup BEFORE clear_children" in the anchored `when`).
    pub fn note_cleanup(&self, label: &str) {
        self.push(format!("cleanup {label}"));
    }

    /// Drain the ops recorded since the last call.
    pub fn take_ops(&self) -> Vec<String> {
        std::mem::take(&mut self.inner.borrow_mut().ops)
    }
}

// ===========================================================================
// Mode
// ===========================================================================

/// Which structural strategy the backend reports.
///
/// - `Anchored` — `supports_child_splice() == false`: reactive regions
///   nest under a `create_reactive_anchor` wrapper and swap subtrees via
///   `clear_children` + `insert` (SSR + web-hydration + legacy native).
/// - `Spliced` — `supports_child_splice() == true`: style-less reactive
///   regions splice directly into the real parent via `remove_child` +
///   `insert_at(base_index)` (web CSR + splice-capable native).
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Mode {
    Anchored,
    Spliced,
}

impl Mode {
    pub fn suffix(self) -> &'static str {
        match self {
            Mode::Anchored => "anchored",
            Mode::Spliced => "spliced",
        }
    }

    fn splice(self) -> bool {
        matches!(self, Mode::Spliced)
    }
}

// ===========================================================================
// Scenario + Cx
// ===========================================================================

/// One recorded step: the label plus every structural op it produced.
pub struct Step {
    pub label: String,
    pub ops: Vec<String>,
}

// ===========================================================================
// Golden serialization + paths
// ===========================================================================

/// The header-less step body of a golden — the goldens on disk carry a
/// `#`-prefixed header written by the (now-deleted) old-core writer,
/// which the comparison strips from both sides before diffing (see
/// [`new_core::normalize`]).
pub fn serialize_steps(steps: &[Step]) -> String {
    let mut out = String::new();
    for step in steps {
        out.push_str(&format!("\n== {} ==\n", step.label));
        if step.ops.is_empty() {
            out.push_str("(no structural ops)\n");
        } else {
            for op in &step.ops {
                out.push_str(op);
                out.push('\n');
            }
        }
    }
    out
}

/// Absolute path of a scenario's golden file.
pub fn golden_path(name: &str, mode: Mode) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("goldens")
        .join(format!("{name}.{}.golden", mode.suffix()))
}
