//! `#[macro_export]` invocation macros for every component.
//!
//! These are the macros `ui! { Foo(...) }` lowers to —
//! `runtime-macros`' `ui!` emitter dispatches a component name like
//! `Stack` to `Stack!(...)` verbatim (no case transform; the macro
//! name equals the PascalCase tag). Each macro here constructs the
//! matching `*Props` struct and calls the plain function in
//! `components/*`.
//!
//! Why these are hand-written instead of generated by
//! `#[component]`: that proc macro produces a local-scope
//! `macro_rules!` that's invisible to other crates. `idea-ui` is a
//! library, so its component macros need `#[macro_export]` plus
//! `$crate::` paths in their bodies — which is what's here.
//!
//! Macro shape: each macro accepts `name = expr` pairs. `children`
//! is just another field on every props struct (or absent), so the
//! `ui!` emitter's `children = vec![…]` lowering "just works" — the
//! macro doesn't need a separate children arm.
//!
//! Components with by-ref signatures (`fn name(props: &Props)`) put
//! the `&` inside the macro body. Container components (`fn name(props:
//! Props)`) consume their props by value so they can move `children`
//! out — those omit the `&`.

// =============================================================================
// stack — by-value (owns its children). Single component covers both
// axes via the `axis` prop; default is `StackAxis::Column`.
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! Stack {
    () => {
        $crate::components::stack::stack(
            <$crate::components::stack::StackProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::stack::stack($crate::components::stack::StackProps {
            $( $field: ($value).into(), )+
            ..<$crate::components::stack::StackProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// btn — by-ref (idea-ui's styled clickable; uses `intent` + `kind`)
//
// The ui! tag is `Btn(...)` (lowered to `btn!(...)`) rather than
// `Button(...)` because the framework's `ui!` macro already
// recognizes `Button` as a shorthand for the framework's `<button>`
// primitive (`runtime_core::button`). Keeping both tags lets
// app code mix raw HTML-button-style primitives with idea-ui's
// styled `Btn` without one taking the other's name.
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! Btn {
    () => {
        $crate::components::button::button(
            &<$crate::components::button::ButtonProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::button::button(&$crate::components::button::ButtonProps {
            $( $field: ($value).into(), )+
            ..<$crate::components::button::ButtonProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// typography — by-ref. The single text component covering every kind
// of text on a page (Display, H1-H3, BodyXl/Lg/_/Sm, Caption, Overline)
// via the `kind` axis. Replaces the older Heading/Body/Caption trio.
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! Typography {
    () => {
        $crate::components::typography::typography(
            &<$crate::components::typography::TypographyProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::typography::typography(&$crate::components::typography::TypographyProps {
            $( $field: ($value).into(), )+
            ..<$crate::components::typography::TypographyProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// card — by-value (owns children)
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! Card {
    () => {
        $crate::components::card::card(
            <$crate::components::card::CardProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::card::card($crate::components::card::CardProps {
            $( $field: ($value).into(), )+
            ..<$crate::components::card::CardProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// field — by-ref
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! Field {
    () => {
        $crate::components::field::field(
            &<$crate::components::field::FieldProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::field::field(&$crate::components::field::FieldProps {
            $( $field: ($value).into(), )+
            ..<$crate::components::field::FieldProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// switch — by-ref
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! Switch {
    () => {
        $crate::components::switch::switch(
            &<$crate::components::switch::SwitchProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::switch::switch(&$crate::components::switch::SwitchProps {
            $( $field: ($value).into(), )+
            ..<$crate::components::switch::SwitchProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// spinner / divider / badge — by-ref
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! Spinner {
    () => {
        $crate::components::spinner::spinner(
            &<$crate::components::spinner::SpinnerProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::spinner::spinner(&$crate::components::spinner::SpinnerProps {
            $( $field: ($value).into(), )+
            ..<$crate::components::spinner::SpinnerProps as ::core::default::Default>::default()
        })
    };
}

#[macro_export]
#[doc(hidden)]
macro_rules! Divider {
    () => {
        $crate::components::divider::divider(
            &<$crate::components::divider::DividerProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::divider::divider(&$crate::components::divider::DividerProps {
            $( $field: ($value).into(), )+
            ..<$crate::components::divider::DividerProps as ::core::default::Default>::default()
        })
    };
}

#[macro_export]
#[doc(hidden)]
macro_rules! Badge {
    () => {
        $crate::components::badge::badge(
            &<$crate::components::badge::BadgeProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::badge::badge(&$crate::components::badge::BadgeProps {
            $( $field: ($value).into(), )+
            ..<$crate::components::badge::BadgeProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// spacer / center — layout helpers
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! Spacer {
    () => {
        $crate::components::spacer::spacer(
            &<$crate::components::spacer::SpacerProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::spacer::spacer(&$crate::components::spacer::SpacerProps {
            $( $field: ($value).into(), )+
            ..<$crate::components::spacer::SpacerProps as ::core::default::Default>::default()
        })
    };
}

#[macro_export]
#[doc(hidden)]
macro_rules! Center {
    () => {
        $crate::components::center::center(
            <$crate::components::center::CenterProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::center::center($crate::components::center::CenterProps {
            $( $field: ($value).into(), )+
            ..<$crate::components::center::CenterProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// IconButton — by-ref
//
// `ui!` dispatch is transform-free: a call site `IconButton(...)` lowers
// to `IconButton!(...)` verbatim, so the macro name must equal the call
// name exactly. The macro BODY calls the snake_case `icon_button` fn.
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! IconButton {
    () => {
        $crate::components::icon_button::icon_button(
            &<$crate::components::icon_button::IconButtonProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::icon_button::icon_button(
            &$crate::components::icon_button::IconButtonProps {
                $( $field: ($value).into(), )+
                ..<$crate::components::icon_button::IconButtonProps as ::core::default::Default>::default()
            }
        )
    };
}

// =============================================================================
// avatar — by-ref
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! Avatar {
    () => {
        $crate::components::avatar::avatar(
            &<$crate::components::avatar::AvatarProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::avatar::avatar(&$crate::components::avatar::AvatarProps {
            $( $field: ($value).into(), )+
            ..<$crate::components::avatar::AvatarProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// tag — by-ref
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! Tag {
    () => {
        $crate::components::tag::tag(
            &<$crate::components::tag::TagProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::tag::tag(&$crate::components::tag::TagProps {
            $( $field: ($value).into(), )+
            ..<$crate::components::tag::TagProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// alert — by-ref
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! Alert {
    () => {
        $crate::components::alert::alert(
            &<$crate::components::alert::AlertProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::alert::alert(&$crate::components::alert::AlertProps {
            $( $field: ($value).into(), )+
            ..<$crate::components::alert::AlertProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// skeleton — by-ref
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! Skeleton {
    () => {
        $crate::components::skeleton::skeleton(
            &<$crate::components::skeleton::SkeletonProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::skeleton::skeleton(&$crate::components::skeleton::SkeletonProps {
            $( $field: ($value).into(), )+
            ..<$crate::components::skeleton::SkeletonProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// tabs — by-value (owns the Vec<Tab>)
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! Tabs {
    () => {
        $crate::components::tabs::tabs(
            <$crate::components::tabs::TabsProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::tabs::tabs($crate::components::tabs::TabsProps {
            $( $field: ($value).into(), )+
            ..<$crate::components::tabs::TabsProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// select — by-value (owns the Vec<SelectOption>)
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! Select {
    () => {
        $crate::components::select::select(
            <$crate::components::select::SelectProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::select::select($crate::components::select::SelectProps {
            $( $field: ($value).into(), )+
            ..<$crate::components::select::SelectProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// modal / popover — by-value (own their children)
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! Modal {
    () => {
        $crate::components::modal::modal(
            <$crate::components::modal::ModalProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::modal::modal($crate::components::modal::ModalProps {
            $( $field: ($value).into(), )+
            ..<$crate::components::modal::ModalProps as ::core::default::Default>::default()
        })
    };
}

#[macro_export]
#[doc(hidden)]
macro_rules! Popover {
    () => {
        $crate::components::popover::popover(
            <$crate::components::popover::PopoverProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::popover::popover($crate::components::popover::PopoverProps {
            $( $field: ($value).into(), )+
            ..<$crate::components::popover::PopoverProps as ::core::default::Default>::default()
        })
    };
}
