// AUTOGENERATED by port-solid. Holes are marked with `todo!`.
// Review every `todo!("port …")` before shipping — the
// porter refused to translate those spots mechanically.

use runtime_core::{component, jsx, signal, effect, on_cleanup, provide, inject, Primitive, Signal};

#[derive(Default)]
pub struct CounterProps {
    pub initial: i32,
}

#[component]
pub fn counter(props: &CounterProps) -> Primitive {
    let count = signal!(props.initial /* ?? 0 (verify default covers) */);
    effect!({
        todo!("port handler-body (line 11): effect setup body — JS imperative code, AI pass needed — console.log(\"count:\", count());");
    });
    jsx! {
        <View>
            <Text>
                {format!("Count: {}", count.get())}
            </Text>
            <Button label="Inc" on_click={move || count.set(count.get() + 1)} />
        </View>
    }

}

