//! Filesystem scaffolding for the scratch crate.
//!
//! After `port-project` writes `.rs` files into `<output>/src/ported/`,
//! this module:
//!
//! - generates `<output>/Cargo.toml` (a self-contained package with
//!   its own `[workspace]` section so it doesn't get pulled into a
//!   surrounding workspace),
//! - generates `<output>/src/main.rs` that just `mod ported;`'s the
//!   tree so all ported files participate in compilation,
//! - walks `<output>/src/ported/` and drops a `mod.rs` at every
//!   directory level that re-exports its children.

use std::fs;
use std::io;
use std::path::{Path, PathBuf};

/// Locations of every idealyst crate the scratch project depends
/// on, in `cargo`-friendly path form. The simplest place to get
/// these is from a single workspace root via [`Workspace::discover`].
pub struct Workspace {
    pub runtime_core: PathBuf,
    pub render_wgpu: PathBuf,
    pub ios_sim: PathBuf,
    pub variant_phone: PathBuf,
}

impl Workspace {
    pub fn from_root(root: &Path) -> Self {
        let join = |sub: &str| root.join(sub);
        Self {
            runtime_core: join("crates/runtime/core"),
            render_wgpu: join("crates/gpu-backend/engine"),
            ios_sim: join("crates/gpu-backend/painter/ios-sim"),
            variant_phone: join("crates/gpu-backend/variant/phone"),
        }
    }
}

pub fn write_cargo_toml(output_dir: &Path, ws: &Workspace, with_host: bool) -> io::Result<()> {
    // Compile-check-only Cargo.toml: only `runtime-core` is
    // needed for the ported files to type-check. The full host
    // stack — `render-wgpu`, `ios-sim`, `variant-phone` — is opt-in
    // via `with_host`, because pulling those in roughly triples
    // the cold-build cost (wgpu's transitive deps are heavy).
    let mut deps = format!("runtime-core = {{ path = {:?} }}\n", ws.runtime_core);
    if with_host {
        deps.push_str(&format!("render-wgpu = {{ path = {:?} }}\n", ws.render_wgpu));
        deps.push_str(&format!("ios-sim = {{ path = {:?} }}\n", ws.ios_sim));
        deps.push_str(&format!("variant-phone = {{ path = {:?} }}\n", ws.variant_phone));
    }

    let toml = format!(
        r#"[package]
name = "port-preview-output"
version = "0.0.1"
edition = "2021"

# This is a self-contained scratch crate. The `[workspace]` section
# keeps it isolated when the output dir happens to sit inside a
# parent cargo workspace.
[workspace]

[dependencies]
{deps}
[[bin]]
name = "port-preview-output"
path = "src/main.rs"
"#,
        deps = deps,
    );
    fs::write(output_dir.join("Cargo.toml"), toml)
}

/// Compile-check-only `main.rs`. Loads the ported tree via
/// `mod ported;` and exits — surfaces every type error at
/// `cargo check` time but doesn't open a window.
pub fn write_main_rs_check_only(output_dir: &Path) -> io::Result<()> {
    let src = r#"// Scratch entry point generated by `port-preview` (compile-check mode).
//
// The `mod ported;` line is the load-bearing bit: it forces the
// compiler to walk the entire ported subtree, surfacing every
// type error / missing item / hole-induced compile failure at
// `cargo check` time.

#![allow(unused, non_snake_case)]

mod ported;

fn main() {
    println!("port-preview: ported tree compiled cleanly.");
}
"#;
    fs::write(output_dir.join("src").join("main.rs"), src)
}

/// Rendering `main.rs`. Wires up the wgpu desktop preview against
/// a specific root component. Generated when `port-preview`
/// successfully resolves a root via `--root <Name>` (default `App`)
/// or `--root-file <path>`.
pub fn write_main_rs_rendering(
    output_dir: &Path,
    root_module_path: &str,
    root_fn_name: &str,
    root_component_name: &str,
) -> io::Result<()> {
    let src = format!(
        r#"// Scratch entry point generated by `port-preview` (render mode).
//
// Wires the ported root component `{component}` to the wgpu
// desktop preview host. No theme is installed by default; if the
// ported component reads tokens (`Tokenized::token(...)`) the
// resolver returns each token's fallback value. Add an
// `install_tokens(...)` call inside `body()` to test styling
// against a real palette.

#![allow(unused, non_snake_case)]

use std::rc::Rc;

use runtime_core::Primitive;

mod ported;

use {module_path}::{{{fn_name}, {component}Props}};

fn body() -> Primitive {{
    let props = {component}Props::default();
    {fn_name}(&props)
}}

fn main() {{
    let skin: Rc<dyn render_wgpu::Painter> = Rc::new(ios_sim::IosSim::new());
    let _ = variant_phone::run_at(skin, None, body);
}}
"#,
        component = root_component_name,
        fn_name = root_fn_name,
        module_path = root_module_path,
    );
    fs::write(output_dir.join("src").join("main.rs"), src)
}

/// Walk the ported tree starting at `dir` and drop a `mod.rs` at
/// every directory level that re-exports its `.rs` siblings and
/// `mod` subdirectories.
///
/// File stems that aren't valid Rust identifiers (or are reserved
/// keywords) are aliased via `#[path = "…"]`; the module name
/// gets a `_` suffix and the original file is still loaded.
pub fn write_mod_tree(dir: &Path) -> io::Result<()> {
    let mut entries: Vec<_> = fs::read_dir(dir)?
        .filter_map(Result::ok)
        .filter(|e| {
            // Skip a previously-generated mod.rs so reruns are idempotent.
            e.path().file_name().and_then(|n| n.to_str()) != Some("mod.rs")
        })
        .collect();
    entries.sort_by_key(|e| e.path());

    let mut mod_rs = String::new();
    mod_rs.push_str("#![allow(unused, non_snake_case, non_camel_case_types)]\n\n");

    for entry in &entries {
        let path = entry.path();
        if path.is_dir() {
            let raw_name = match path.file_name().and_then(|n| n.to_str()) {
                Some(n) => n,
                None => continue,
            };
            let module = sanitize_module_name(raw_name);
            if module != raw_name {
                mod_rs.push_str(&format!("#[path = \"{}\"]\n", raw_name));
            }
            mod_rs.push_str(&format!("pub mod {};\n", module));
            write_mod_tree(&path)?;
        } else if path.extension().and_then(|e| e.to_str()) == Some("rs") {
            let stem = match path.file_stem().and_then(|s| s.to_str()) {
                Some(s) => s,
                None => continue,
            };
            let module = sanitize_module_name(stem);
            if module != stem {
                mod_rs.push_str(&format!("#[path = \"{}.rs\"]\n", stem));
            }
            mod_rs.push_str(&format!("pub mod {};\n", module));
        }
    }

    fs::write(dir.join("mod.rs"), mod_rs)
}

/// Coerce a filename stem into a valid Rust identifier. Anything
/// non-`[A-Za-z0-9_]` becomes `_`; leading digits get an `n_`
/// prefix; reserved keywords get a `_` suffix.
fn sanitize_module_name(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    let mut first = true;
    for ch in s.chars() {
        if first {
            if ch.is_ascii_digit() {
                out.push_str("n_");
            }
            first = false;
        }
        if ch.is_ascii_alphanumeric() || ch == '_' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if RUST_KEYWORDS.contains(&out.as_str()) {
        out.push('_');
    }
    out
}

const RUST_KEYWORDS: &[&str] = &[
    "as", "break", "const", "continue", "crate", "else", "enum",
    "extern", "false", "fn", "for", "if", "impl", "in", "let",
    "loop", "match", "mod", "move", "mut", "pub", "ref", "return",
    "self", "Self", "static", "struct", "super", "trait", "true",
    "type", "unsafe", "use", "where", "while", "async", "await",
    "dyn", "abstract", "become", "box", "do", "final", "macro",
    "override", "priv", "typeof", "unsized", "virtual", "yield",
    "try",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sanitize_basics() {
        assert_eq!(sanitize_module_name("foo"), "foo");
        assert_eq!(sanitize_module_name("foo-bar"), "foo_bar");
        assert_eq!(sanitize_module_name("9lives"), "n_9lives");
        assert_eq!(sanitize_module_name("type"), "type_");
        assert_eq!(sanitize_module_name("ALL_CAPS"), "ALL_CAPS");
    }
}
