//! Component implementations. Each module exports a plain `fn`
//! plus the variant enums its stylesheet uses. Invocation macros
//! live in `crate::invocations` so all of them are `#[macro_export]`
//! at the crate root.

use runtime_core::{
    text, AlignSelf, Element, IdealystSchema, IntoElement, IntoStyleSource, Reactive, StyleRules,
};

/// `StyleRules` that make an inline component HUG its content on the cross
/// axis instead of inheriting a flex parent's default `align-items: stretch`
/// (which would grow a Badge/Tag/Chip to the row's height and float its label
/// to the top — the same class of bug Button fixes). `Center` keeps the pill
/// sized to content while still letting a centering parent (a toolbar row, a
/// centered preview) center it. Attach as a `with_computed` layer.
pub(crate) fn hug_self() -> StyleRules {
    StyleRules { align_self: Some(AlignSelf::Center), ..Default::default() }
}

/// Render an optional, possibly-reactive text prop
/// (`Reactive<Option<String>>`) as an optional styled text node:
///
/// - `Static(None)` → `None` (no node — no layout slot for an absent
///   label).
/// - `Static(Some(s))` → a static text node.
/// - `Dynamic(f)` → a reactive text node that re-paints when `f`'s
///   signals change, showing `""` while the value is `None`.
///
/// Shared by the components with an optional text prop (Switch/Field
/// `label`, Alert `body`). Coercion is uniform: a call-site
/// `label = Some("x".to_string())` or `label = None` lands here via the
/// `ui!`/`jsx!` dispatch's per-field `.into()` (blanket
/// `From<Option<String>>`), and a `Signal<Option<String>>` /
/// `rx!(Some(...))` arrives `Dynamic`.
pub(crate) fn optional_reactive_text(
    content: Reactive<Option<String>>,
    style: impl IntoStyleSource,
) -> Option<Element> {
    match content {
        Reactive::Static(None) => None,
        Reactive::Static(Some(s)) => Some(text(s).with_style(style).into_element()),
        Reactive::Dynamic(f) => {
            Some(text(move || f().unwrap_or_default()).with_style(style).into_element())
        }
    }
}

/// Size scale shared by the selection controls (Switch, Checkbox,
/// Radio) and the linear Progress bar. These have intrinsic
/// dimensions rather than the Button family's padding/font scale, so
/// they use this closed enum instead of the `ButtonSize` trait. The
/// string keys match the `size` arms generated by the matching
/// idea-theme sheet builders.
#[derive(Copy, Clone, Debug, PartialEq, Eq, Default, IdealystSchema)]
pub enum ControlSize {
    /// Small.
    Sm,
    /// Medium (default).
    #[default]
    Md,
    /// Large.
    Lg,
}

impl ControlSize {
    /// The `size` variant-axis key for this scale.
    pub fn as_variant_str(self) -> &'static str {
        match self {
            ControlSize::Sm => "sm",
            ControlSize::Md => "md",
            ControlSize::Lg => "lg",
        }
    }
}

// `VariantEnum` lets the docs-app `DocControls` derive render a size
// picker; the inherent `as_variant_str` above is what components call.
impl runtime_core::VariantEnum for ControlSize {
    fn as_variant_str(self) -> &'static str {
        match self {
            ControlSize::Sm => "sm",
            ControlSize::Md => "md",
            ControlSize::Lg => "lg",
        }
    }
    fn all_variants() -> &'static [Self] {
        &[ControlSize::Sm, ControlSize::Md, ControlSize::Lg]
    }
}

#[cfg(test)]
mod control_size_tests {
    use super::ControlSize;

    #[test]
    fn variant_keys_match_sheet_builder_size_arms() {
        // These strings MUST equal the `size` arm keys generated by the
        // idea-theme sheet builders (SWITCH_TRACK_DIMS / CHECKBOX_DIMS /
        // RADIO_DIMS / PROGRESS_DIMS), or the component would request a
        // nonexistent arm and silently fall back to the default size.
        assert_eq!(ControlSize::Sm.as_variant_str(), "sm");
        assert_eq!(ControlSize::Md.as_variant_str(), "md");
        assert_eq!(ControlSize::Lg.as_variant_str(), "lg");
        assert_eq!(ControlSize::default(), ControlSize::Md);
    }
}

// The catalog scope every component in this module tree belongs to (by
// ambient module proximity — `idea_ui::components` is an ancestor of
// `idea_ui::components::*`). No-op without the `catalog` feature.
runtime_core::doc_scope!(
    Components = "Components",
    slug = "components",
    docs = "idea-ui's component library — buttons, inputs, layout, overlays, feedback, and data-display widgets, all cross-platform."
);

#[cfg(all(feature = "prim-icon", feature = "prim-activity"))]
// Per-component prim gating: a component compiles only when every
// primitive family it (transitively) renders is enabled — see the
// feature table in Cargo.toml (components/mod.rs gates are the
// authoritative map). Using a gated-out component is a compile error
// naming the missing `prim-*` feature, not a runtime placeholder.
pub mod alert;
#[cfg(all(feature = "prim-text-input", feature = "prim-portal"))]
pub mod autocomplete;
// Avatar renders its `src` through the image primitive (`image_from`).
#[cfg(feature = "prim-image")]
pub mod avatar;
pub mod badge;
#[cfg(feature = "prim-icon")]
pub mod breadcrumbs;
#[cfg(feature = "prim-icon")]
pub mod checkbox;
pub mod grid;
#[cfg(feature = "prim-image")]
pub mod image;
pub mod link;
pub mod list;
#[cfg(feature = "prim-portal")]
pub mod menu;
/// Shared scrolling panel for the anchored-menu family (Select/Menu/SubMenu/
/// Autocomplete). Internal — not a component; see `menu_panel::scrolling_menu_panel`.
pub(crate) mod menu_panel;
#[cfg(feature = "prim-icon")]
pub mod pagination;
pub mod progress;
pub mod radio;
#[cfg(feature = "prim-text-input")]
pub mod textarea;
#[cfg(all(feature = "prim-icon", feature = "prim-activity", feature = "prim-portal", feature = "prim-presence"))]
pub mod toast;
#[cfg(feature = "prim-portal")]
pub mod tooltip;
#[cfg(all(feature = "prim-icon", feature = "prim-activity"))]
pub mod button;
pub mod card;
pub mod center;
pub mod chip;
pub mod collapsible;
pub mod divider;
// Gated on text-input only: the module also hosts the shared input/help
// stylesheets Textarea renders with. The Field COMPONENT additionally
// needs icon + activity (adornments, loading spinner) — those items
// carry their own cfg(all(...)) inside the module.
#[cfg(feature = "prim-text-input")]
pub mod field;
#[cfg(feature = "prim-icon")]
pub mod icon;
#[cfg(feature = "prim-icon")]
pub mod icon_button;
#[cfg(all(feature = "prim-portal", feature = "prim-presence"))]
pub mod modal;
#[cfg(feature = "prim-portal")]
pub mod popover;
pub mod segmented_control;
// Gated on portal only: Autocomplete (text-input + portal) reuses the
// module's `SelectOption` / `SelectSize` types, which carry no icon
// dependency. The Select COMPONENT additionally needs icon (chevron) —
// those items carry cfg(all(...)) inside the module.
#[cfg(feature = "prim-portal")]
pub mod select;
pub mod skeleton;
#[cfg(feature = "prim-icon")]
pub mod slider;
pub mod spacer;
#[cfg(feature = "prim-activity")]
pub mod spinner;
pub mod stack;
pub mod surface;
#[cfg(feature = "prim-icon")]
pub mod switch;
#[cfg(feature = "table")]
pub mod table;
pub mod tabs;
pub mod tag;
pub mod typography;

// `Icon` is re-exported here (rather than only at the crate root in
// lib.rs) so it's reachable as `crate::components::Icon`. The crate-root
// `idea_ui::Icon` alias lives in lib.rs alongside the other components.
#[cfg(feature = "prim-icon")]
pub use icon::{Icon, IconProps};
