//! Emitter — porter IR → idealyst Rust source (as a string).
//!
//! Output shape per component:
//!
//! ```text
//! #[derive(Default)]
//! pub struct CounterProps { pub initial: i32 }
//!
//! #[component(default(initial = 0))]
//! pub fn Counter(props: &CounterProps) -> Element {
//!     let count = signal!(props.initial);
//!     effect!({
//!         todo!("port handler-body: console.log('count:', count)");
//!     });
//!     jsx! {
//!         <View>
//!             <Text>{format!("Count: {}", count.get())}</Text>
//!             <Button label="Inc" on_click={move || /* … */} />
//!         </View>
//!     }
//! }
//! ```
//!
//! Two design rules:
//!
//! 1. **No silent fallback.** Every `Hole` in the IR becomes a
//!    visible `todo!("port <kind>: <original>")` in the output.
//!    A successful port lists its holes loudly.
//! 2. **Output is plain strings.** No `quote!` / no `proc_macro2`.
//!    The emitter exists to produce a file a human (or AI) will
//!    read and edit; readability beats AST hygiene here.

use crate::ir::*;

/// Render a `PropsType` as a free-standing `pub struct` Rust
/// source block. Used by per-framework lifters to materialize TS
/// interfaces, and by the project-level driver when resolving
/// cross-file context aliases (the alias's name takes the place
/// of the original interface name).
pub fn render_struct(struct_name: &str, props: &PropsType) -> String {
    let mut out = String::new();
    out.push_str("#[derive(Default, Clone)]\n");
    out.push_str(&format!("pub struct {} {{\n", struct_name));
    for f in &props.fields {
        out.push_str(&format!("    pub {}: {},\n", f.name, f.ty));
    }
    out.push_str("}\n");
    out
}

/// Render a single `JsxNode` as a `jsx! { … }` expression string,
/// suitable for embedding inside another `jsx!` invocation (e.g.
/// inside an `if`/`else` branch). Collapses all newlines so the
/// embedded macro reads as a single line — rustfmt will tidy on
/// the receiving end if the caller writes the file to disk.
pub fn render_node_inline(node: &JsxNode) -> String {
    let mut buf = String::new();
    emit_jsx_node(&mut buf, node, 0);
    // Collapse runs of whitespace to a single space so the inline
    // form is readable on one line.
    let mut out = String::with_capacity(buf.len() + 12);
    out.push_str("jsx! { ");
    let mut prev_space = false;
    for ch in buf.chars() {
        if ch.is_whitespace() {
            if !prev_space {
                out.push(' ');
            }
            prev_space = true;
        } else {
            out.push(ch);
            prev_space = false;
        }
    }
    while out.ends_with(' ') {
        out.pop();
    }
    out.push_str(" }");
    out
}

pub fn emit_module(module: &Module) -> String {
    let mut out = String::new();
    emit_header(&mut out, module);
    for snippet in &module.passthroughs {
        out.push_str(&snippet.text);
        out.push_str("\n\n");
    }
    // Any context aliases the project-level driver didn't get a
    // chance to resolve (or single-file CLI runs without a driver
    // at all) emit as visible TODO-typed sentinel structs. The
    // file fails to compile until the user fills in the fields —
    // the right loud failure mode.
    for (alias, ref_name) in &module.unresolved_context_aliases {
        out.push_str(&format!(
            "// TODO: createContext alias `{}` referenced unresolved type `{}`.\n\
             // Define `{}` to match the imported `{}` interface, or run\n\
             // `port-project` on the whole tree so the cross-file registry\n\
             // can resolve it automatically.\n\
             pub struct {} {{}}\n\n",
            alias, ref_name, alias, ref_name, alias
        ));
    }
    for c in &module.components {
        emit_component(&mut out, c);
        out.push('\n');
    }
    out
}

fn emit_header(out: &mut String, module: &Module) {
    let tool = if module.source_tool.is_empty() { "port-*" } else { module.source_tool.as_str() };
    out.push_str(&format!("// AUTOGENERATED by {tool}. Holes are marked with `todo!`.\n"));
    out.push_str("// Review every `todo!(\"port …\")` before shipping — the\n");
    out.push_str("// porter refused to translate those spots mechanically.\n\n");
    if !module.imports.is_empty() {
        out.push_str("use runtime_core::{");
        out.push_str(&module.imports.join(", "));
        out.push_str("};\n\n");
    }
}

fn emit_component(out: &mut String, c: &Component) {
    emit_props_struct(out, c);
    emit_component_attr(out, c);
    // Component fns are PascalCase — fn name == macro name == `jsx!`
    // call name, matching the framework's transform-free dispatch.
    // `#[component]` suppresses the `non_snake_case` lint.
    out.push_str(&format!(
        "pub fn {fn_name}(props: &{props_ty}) -> Element {{\n",
        fn_name = c.name,
        props_ty = props_struct_name(&c.name),
    ));
    for r in &c.body.preamble {
        emit_reactive(out, r);
    }
    out.push_str("    ");
    match &c.body.returns {
        ReturnExpr::Jsx(node) => emit_jsx_block(out, node),
        ReturnExpr::Hole(h) => out.push_str(&emit_hole_expr(h)),
    }
    out.push_str("\n}\n");
}

fn emit_props_struct(out: &mut String, c: &Component) {
    out.push_str("#[derive(Default)]\n");
    out.push_str(&format!("pub struct {} {{\n", props_struct_name(&c.name)));
    for f in &c.props.fields {
        out.push_str(&format!("    pub {}: {},\n", f.name, f.ty));
    }
    out.push_str("}\n\n");
}

fn emit_component_attr(out: &mut String, c: &Component) {
    let defaults: Vec<String> = c.props.fields.iter()
        .filter_map(|f| f.default.as_ref().map(|d| format!("{} = {}", f.name, d)))
        .collect();
    if defaults.is_empty() {
        out.push_str("#[component]\n");
    } else {
        out.push_str(&format!("#[component(default({}))]\n", defaults.join(", ")));
    }
}

fn emit_reactive(out: &mut String, r: &Reactive) {
    match r {
        Reactive::State { name, init, .. } => {
            // `setter` is intentionally unused at emission time —
            // the lowering pass already rewrote setter calls in
            // any handler/effect bodies before we got here.
            out.push_str(&format!("    let {} = signal!({});\n", name, init));
        }
        Reactive::Effect { body, deps } => {
            // `effect!` is the framework macro form — handles
            // RAII slot registration, scope-aware lifetime, and
            // pairs with `on_cleanup(...)` for invalidation calls
            // emitted into the body.
            out.push_str("    effect!({\n");
            if let Some(deps) = deps {
                out.push_str(&format!("        // original deps: [{}]\n", deps.join(", ")));
            }
            for line in body.text.lines() {
                out.push_str("        ");
                out.push_str(line);
                out.push('\n');
            }
            out.push_str("    });\n");
        }
        Reactive::Let { name, expr } => {
            out.push_str(&format!("    let {} = {};\n", name, expr));
        }
        Reactive::Stmt(expr) => {
            out.push_str(&format!("    {};\n", expr));
        }
        Reactive::Hole(h) => {
            out.push_str("    ");
            out.push_str(&emit_hole_stmt(h));
            out.push('\n');
        }
    }
}

fn emit_jsx_block(out: &mut String, node: &JsxNode) {
    out.push_str("jsx! {\n");
    emit_jsx_node(out, node, 2);
    out.push_str("    }\n");
}

fn emit_jsx_node(out: &mut String, node: &JsxNode, indent: usize) {
    let pad = "    ".repeat(indent);
    match node {
        JsxNode::Element { name, attrs, children } => {
            out.push_str(&pad);
            out.push('<');
            out.push_str(name);
            for a in attrs {
                out.push(' ');
                out.push_str(&emit_attr(a));
            }
            match children {
                None => out.push_str(" />\n"),
                Some(kids) if kids.is_empty() => {
                    out.push_str("></");
                    out.push_str(name);
                    out.push_str(">\n");
                }
                Some(kids) => {
                    out.push_str(">\n");
                    for k in kids {
                        emit_jsx_node(out, k, indent + 1);
                    }
                    out.push_str(&pad);
                    out.push_str("</");
                    out.push_str(name);
                    out.push_str(">\n");
                }
            }
        }
        JsxNode::Text(s) => {
            // `jsx!` requires text to live inside a `<Text>` wrapper —
            // bare strings between tags are a compile error. Wrap.
            out.push_str(&pad);
            out.push_str("<Text>\"");
            out.push_str(&escape_string(s));
            out.push_str("\"</Text>\n");
        }
        JsxNode::Expr(expr) => {
            out.push_str(&pad);
            out.push('{');
            out.push_str(expr);
            out.push_str("}\n");
        }
        JsxNode::Hole(h) => {
            out.push_str(&pad);
            out.push_str("{ ");
            out.push_str(&emit_hole_expr(h));
            out.push_str(" }\n");
        }
    }
}

fn emit_attr(a: &JsxAttr) -> String {
    match &a.value {
        JsxAttrValue::StringLit(s) => format!("{}=\"{}\"", a.name, escape_string(s)),
        JsxAttrValue::Expr(e) => format!("{}={{{}}}", a.name, e),
        JsxAttrValue::Hole(h) => format!("{}={{{}}}", a.name, emit_hole_expr(h)),
    }
}

// =============================================================================
// Holes
// =============================================================================

fn emit_hole_expr(h: &Hole) -> String {
    // `todo!()` is an expression, fits anywhere a Rust expr is
    // expected (return value, JSX child slot, attribute value).
    format!("todo!({})", quote_message(h))
}

fn emit_hole_stmt(h: &Hole) -> String {
    // Statement position — the trailing semicolon makes it usable
    // standalone in the preamble.
    format!("todo!({});", quote_message(h))
}

fn quote_message(h: &Hole) -> String {
    // Embed the original source inline so an LLM (or human) sees
    // the surrounding Rust *and* the JS it has to translate.
    let line = h.original.line.map(|l| format!(" (line {})", l)).unwrap_or_default();
    let original = collapse_whitespace(&h.original.text);
    format!(
        "\"port {kind}{line}: {reason} — {original}\"",
        kind = h.kind,
        line = line,
        reason = escape_string(&h.reason),
        original = escape_string(&original),
    )
}

// =============================================================================
// Small helpers — naming, escaping
// =============================================================================

fn props_struct_name(component_name: &str) -> String {
    format!("{}Props", component_name)
}

fn escape_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(ch),
        }
    }
    out
}

fn collapse_whitespace(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut prev_space = false;
    for ch in s.chars() {
        if ch.is_whitespace() {
            if !prev_space {
                out.push(' ');
            }
            prev_space = true;
        } else {
            out.push(ch);
            prev_space = false;
        }
    }
    out.trim().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn hole_emits_as_todo_expr() {
        let h = Hole {
            kind: HoleKind::HandlerBody,
            reason: "axios call".into(),
            original: SourceSnippet::at("axios.get('/x')", 42),
        };
        let out = emit_hole_expr(&h);
        assert!(out.starts_with("todo!(\"port handler-body"));
        assert!(out.contains("axios.get"));
    }
}
