//! `idealyst brs` — collect `#[method]`-tagged functions across the
//! project's source tree and emit them into a single `.brs` file.
//!
//! This is the build-time companion to the `#[method]` proc-macro
//! re-exported from `backend-roku`. At regular `cargo build` time
//! the macro validates the supported subset and emits a sibling
//! `*_BRS` constant alongside each annotated function — useful for
//! IDE feedback but not collected anywhere. This subcommand
//! re-parses the source files, runs the same transpiler over every
//! `#[method]` fn it finds, and writes the concatenated result to
//! disk so the BrightScript bundle can be packaged into a Roku
//! .pkg.
//!
//! Why re-parse rather than read the compiled constants? Because
//! collecting `pub const` values from a Rust crate without
//! actually loading the compiled binary is awkward — you'd either
//! shell out to `cargo expand`, dynamically load the lib, or
//! invent a registry-style submission pattern. Re-parsing with
//! `syn` is dramatically simpler, and the transpiler is the
//! authoritative semantics either way.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use anyhow::{anyhow, Context, Result};
use syn::{File, Item};

#[derive(clap::Args, Debug)]
pub struct Args {
    /// Project directory. Defaults to the current directory.
    /// The CLI scans every `.rs` file under `<dir>/src/`.
    #[arg(default_value = ".")]
    pub dir: PathBuf,

    /// Output file. Defaults to `<dir>/dist/roku/main.brs`.
    #[arg(short, long)]
    pub output: Option<PathBuf>,
}

pub fn run(args: Args) -> Result<()> {
    let src_dir = args.dir.join("src");
    if !src_dir.is_dir() {
        return Err(anyhow!(
            "no `src/` directory under {}; run `idealyst brs` from a Rust crate root",
            args.dir.display()
        ));
    }

    let mut found: BTreeMap<String, String> = BTreeMap::new();
    let mut scanned = 0usize;
    visit_dir(&src_dir, &mut |path| {
        scanned += 1;
        scan_file(path, &mut found)
    })?;

    if found.is_empty() {
        eprintln!(
            "[idealyst brs] scanned {} file(s) under {}; no `#[method]` functions found",
            scanned,
            src_dir.display()
        );
    }

    let output_path = args
        .output
        .unwrap_or_else(|| args.dir.join("dist/roku/main.brs"));
    if let Some(parent) = output_path.parent() {
        std::fs::create_dir_all(parent).with_context(|| {
            format!("creating output dir {}", parent.display())
        })?;
    }

    let mut bundle = String::new();
    bundle.push_str(
        "' Generated by `idealyst brs`. Do not edit by hand — \
         the source of truth is the Rust crate.\n\n",
    );
    for (name, body) in &found {
        bundle.push_str(&format!("' --- {} ---\n", name));
        bundle.push_str(body);
        bundle.push('\n');
    }

    std::fs::write(&output_path, &bundle).with_context(|| {
        format!("writing {}", output_path.display())
    })?;

    eprintln!(
        "[idealyst brs] {} function(s) → {} ({} bytes)",
        found.len(),
        output_path.display(),
        bundle.len()
    );
    Ok(())
}

/// Recursively call `visit` on every `.rs` file under `dir`. Skips
/// `target/`, `dist/`, and hidden directories — the project's build
/// output sometimes contains generated `.rs` files we shouldn't
/// re-transpile.
fn visit_dir(dir: &Path, visit: &mut dyn FnMut(&Path) -> Result<()>) -> Result<()> {
    for entry in std::fs::read_dir(dir)
        .with_context(|| format!("reading {}", dir.display()))?
    {
        let entry = entry?;
        let path = entry.path();
        let file_name = entry.file_name();
        let name_str = file_name.to_string_lossy();
        if name_str.starts_with('.')
            || name_str == "target"
            || name_str == "dist"
            || name_str == "node_modules"
        {
            continue;
        }
        if path.is_dir() {
            visit_dir(&path, visit)?;
        } else if path.extension().is_some_and(|e| e == "rs") {
            visit(&path)?;
        }
    }
    Ok(())
}

/// Parse a single source file and append the BRS for every
/// `#[method]`-tagged function into `out`.
fn scan_file(path: &Path, out: &mut BTreeMap<String, String>) -> Result<()> {
    let source = std::fs::read_to_string(path)
        .with_context(|| format!("reading {}", path.display()))?;
    let parsed: File = match syn::parse_file(&source) {
        Ok(f) => f,
        Err(e) => {
            // Bad Rust syntax — but `cargo build` will surface this
            // properly. We don't want a syntax error in a stray
            // file to abort the BRS collection of the rest of the
            // project, so just warn.
            eprintln!(
                "[idealyst brs] WARN: skipping {} (parse error: {})",
                path.display(),
                e
            );
            return Ok(());
        }
    };

    walk_items(&parsed.items, path, out)
}

fn walk_items(
    items: &[Item],
    path: &Path,
    out: &mut BTreeMap<String, String>,
) -> Result<()> {
    for item in items {
        match item {
            Item::Fn(f) => {
                if has_method_attr(&f.attrs) {
                    let name = f.sig.ident.to_string();
                    let brs = backend_roku_transpile::transpile_fn(f).map_err(|e| {
                        anyhow!(
                            "{}: `#[method] fn {}`: {}",
                            path.display(),
                            name,
                            e
                        )
                    })?;
                    out.insert(name, brs);
                }
            }
            Item::Mod(m) => {
                if let Some((_, items)) = &m.content {
                    walk_items(items, path, out)?;
                }
                // External `mod foo;` (no inline body) becomes its
                // own file under src/, which the outer directory
                // walk picks up — nothing to do here.
            }
            _ => {}
        }
    }
    Ok(())
}

/// Returns true if the attribute list contains `#[method]` or
/// `#[<path>::method]` (matches by last path segment).
fn has_method_attr(attrs: &[syn::Attribute]) -> bool {
    attrs.iter().any(|a| {
        a.path()
            .segments
            .last()
            .map(|s| s.ident == "method")
            .unwrap_or(false)
    })
}
