//! Ephemeral "catalog wrapper" crate generator.
//!
//! The MCP server lists a project's `#[component]`s by running a binary
//! that (a) links the project's library so its `inventory::submit!`
//! registrations are present, and (b) is built with `runtime-core/mcp`
//! on so the `#[component]` macro actually *emits* those registrations.
//!
//! Rather than make every project carry that binary + an `mcp` feature
//! (the old scaffold did), the CLI generates a throwaway wrapper crate
//! under `target/idealyst/<project>/catalog/` — the same place and
//! shape as the per-platform `{web,ios,android}` wrappers. The wrapper
//! path-deps the project and turns on `runtime-core/mcp`; Cargo's
//! feature unification then builds `runtime-macros` with emission on for
//! the *entire* graph, so the project's components register even though
//! the project declares no `mcp` feature itself.
//!
//! This is the mechanism that lets `idealyst mcp` work against any
//! project — old or new — with zero per-project boilerplate.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::framework_source;

/// Generate (or refresh) the catalog wrapper crate for `project_root`
/// and return its directory. The returned crate exposes a `catalog`
/// bin that prints the project's MCP catalog JSON to stdout — run it
/// with `cargo run -q --bin catalog` from the returned directory.
///
/// Idempotent: files are only rewritten when their contents change, so
/// repeated calls don't invalidate cargo's fingerprints and trigger
/// needless rebuilds.
pub fn generate(project_root: &Path) -> Result<PathBuf> {
    // Absolute project path — the wrapper lives elsewhere on disk and
    // references the project by path, so a relative `.` / cwd would
    // resolve against the wrapper dir, not here.
    let project_root = fs::canonicalize(project_root)
        .with_context(|| format!("canonicalize project dir {}", project_root.display()))?;

    let manifest = build_ios::parse_manifest(&project_root)
        .context("read the project's Cargo.toml to build a catalog wrapper")?;
    let source = framework_source::resolve(&project_root)?;

    let wrapper_dir = source
        .wrapper_root(&project_root)
        .join(&manifest.name)
        .join("catalog");
    fs::create_dir_all(wrapper_dir.join("src"))
        .with_context(|| format!("create {}", wrapper_dir.join("src").display()))?;

    // `runtime-core` with `mcp` on is the lever: enabling it anywhere in
    // the graph flips the `#[component]` emission gate for every crate,
    // including the project lib.
    let fcore_dep = source.dep("crates/runtime/core", &["mcp"]);
    // Redirect any git-pinned framework crates the project uses to the
    // same physical paths the wrapper uses, so the two halves share ONE
    // `runtime_core` instance (otherwise feature unification can't merge
    // the `mcp` feature, and the wrapper→project type bridge fails).
    // Empty in git mode — there both sides already use the same rev.
    let patch_block = source.patch_block();

    let cargo_toml = format!(
        r#"# GENERATED by `idealyst mcp`. Do not edit — rewritten on demand.
#
# Ephemeral catalog-extraction wrapper. Links the project's library and
# turns on `runtime-core/mcp` so every `#[component]` in the project (and
# its component-library deps) registers in the MCP catalog. The project
# itself needs no `[[bin]] catalog` and no `mcp` feature.
#
# Empty `[workspace]` declares this wrapper standalone even though it
# lives under the framework workspace's `target/idealyst/...`; without it
# cargo would try to claim it as a member of the parent workspace.
[workspace]

[package]
name = "{name}-catalog-wrapper"
version = "0.0.1"
edition = "2021"
publish = false

[[bin]]
name = "catalog"
path = "src/main.rs"

[dependencies]
runtime-core = {fcore_dep}
{user_name} = {{ path = "{user_path}" }}
{patch_block}"#,
        name = manifest.name,
        fcore_dep = fcore_dep,
        user_name = manifest.name,
        user_path = project_root.display(),
        patch_block = patch_block,
    );

    let main_rs = format!(
        r#"//! GENERATED by `idealyst mcp` — ephemeral catalog extractor.
//!
//! `use {lib} as _;` links the project's library so its
//! `inventory::submit!` component registrations are present; the wrapper
//! is built with `runtime-core/mcp`, so those registrations were
//! emitted. `dump_catalog_json` serializes the collected catalog to
//! stdout.

use {lib} as _;

fn main() {{
    runtime_core::__mcp::dump_catalog_json();
}}
"#,
        lib = manifest.lib_name,
    );

    // Share the project/workspace target dir so common dependencies stay
    // warm across builds and the produced binary lives at a predictable
    // path. (The `mcp`-feature build of runtime-core is a distinct cargo
    // fingerprint from the project's normal build, so they coexist
    // rather than clobber each other.)
    let cargo_config = format!(
        "# GENERATED. Redirect this wrapper's build output to the shared\n\
         # target dir so subsequent extractions reuse the cache.\n\
         \n\
         [build]\n\
         target-dir = \"{}\"\n",
        source.cargo_target_dir(&project_root).display(),
    );

    write_if_changed(&wrapper_dir.join("Cargo.toml"), &cargo_toml)?;
    write_if_changed(&wrapper_dir.join("src/main.rs"), &main_rs)?;
    fs::create_dir_all(wrapper_dir.join(".cargo"))
        .with_context(|| format!("create {}", wrapper_dir.join(".cargo").display()))?;
    write_if_changed(&wrapper_dir.join(".cargo/config.toml"), &cargo_config)?;

    Ok(wrapper_dir)
}

/// Write `contents` to `path` only if it differs from what's already
/// there. Avoids bumping mtimes (and thus cargo fingerprints) on
/// no-op regenerations.
fn write_if_changed(path: &Path, contents: &str) -> Result<()> {
    if let Ok(existing) = fs::read_to_string(path) {
        if existing == contents {
            return Ok(());
        }
    }
    fs::write(path, contents).with_context(|| format!("write {}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A minimal project: `[package]` + a hyphenated name (so we exercise
    /// the `name → lib_name` `-`→`_` conversion) and a `runtime-core`
    /// dep. No `[[bin]] catalog`, no `mcp` feature — the whole point is
    /// that the wrapper supplies both.
    fn fake_project(tag: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!(
            "idealyst-catwrap-{}-{}",
            tag,
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        fs::write(
            dir.join("Cargo.toml"),
            "[package]\nname = \"my-app\"\nversion = \"0.0.1\"\nedition = \"2021\"\n\
             [dependencies]\nruntime-core = { git = \"https://example.com/x\", rev = \"0\" }\n",
        )
        .unwrap();
        dir
    }

    #[test]
    fn generate_emits_a_runnable_catalog_wrapper() {
        let project = fake_project("emit");
        let wrapper = generate(&project).expect("generate wrapper");

        // Lives under the project's `target/idealyst/<name>/catalog`.
        assert!(wrapper.ends_with("target/idealyst/my-app/catalog"), "{:?}", wrapper);

        let cargo = fs::read_to_string(wrapper.join("Cargo.toml")).unwrap();
        // A `catalog` bin the MCP server can run.
        assert!(cargo.contains("[[bin]]"));
        assert!(cargo.contains("name = \"catalog\""));
        // runtime-core with the `mcp` feature on — the emission lever.
        assert!(cargo.contains("runtime-core ="));
        assert!(cargo.contains("features = [\"mcp\"]"), "cargo: {cargo}");
        // Path-deps the project under its package name.
        assert!(cargo.contains("my-app = { path ="), "cargo: {cargo}");
        // Standalone so the parent workspace doesn't claim it.
        assert!(cargo.contains("[workspace]"));

        let main_rs = fs::read_to_string(wrapper.join("src/main.rs")).unwrap();
        // Imports by LIB name (hyphen → underscore) and dumps the catalog.
        assert!(main_rs.contains("use my_app as _;"), "main: {main_rs}");
        assert!(main_rs.contains("dump_catalog_json"));

        let _ = fs::remove_dir_all(&project);
    }

    #[test]
    fn generate_is_idempotent() {
        let project = fake_project("idem");
        let wrapper = generate(&project).expect("first generate");
        let main_path = wrapper.join("src/main.rs");
        let mtime1 = fs::metadata(&main_path).unwrap().modified().unwrap();
        // Second call with identical inputs must not rewrite the files
        // (would bump mtime and invalidate cargo's fingerprint).
        let wrapper2 = generate(&project).expect("second generate");
        assert_eq!(wrapper, wrapper2);
        let mtime2 = fs::metadata(&main_path).unwrap().modified().unwrap();
        assert_eq!(mtime1, mtime2, "idempotent regenerate must not rewrite files");

        let _ = fs::remove_dir_all(&project);
    }

    #[test]
    fn generate_rejects_a_workspace_root() {
        // A bare `[workspace]` with no `[package]` is not a project; the
        // caller turns this Err into a graceful "no catalog" warning.
        let dir = std::env::temp_dir().join(format!(
            "idealyst-catwrap-ws-{}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        fs::write(dir.join("Cargo.toml"), "[workspace]\nmembers = []\n").unwrap();
        assert!(generate(&dir).is_err());
        let _ = fs::remove_dir_all(&dir);
    }
}
