//! `idealyst inspect` — host the Inspector server and open the Inspector
//! in the browser.
//!
//! The server (`inspector-server`) owns every piece of debug state. It
//! discovers running apps under `~/.idealyst/apps`, holds each inspected
//! app's robot-bridge connection, and pushes snapshots to the front end
//! over a WebSocket. The front end is `examples/inspector`, built for the
//! web by this crate's `build.rs` and embedded in the binary
//! ([`INSPECTOR_BUNDLE`]), so the page and the socket come from one
//! local port.
//!
//! One server per machine: if one already answers on the port, this
//! command (and `idealyst dev --inspect`) opens the browser on it instead
//! of starting another.

use std::time::Duration;

use anyhow::{Context, Result};
use inspector_server::{Assets, Config};

mod bundle {
    // Generated by build.rs: `FILES` (the Inspector's web bundle, path →
    // bytes) and `SKIPPED` (why it's empty, when it is).
    include!(concat!(env!("OUT_DIR"), "/inspector_bundle.rs"));
}

/// The Inspector's web bundle, embedded at build time.
pub const INSPECTOR_BUNDLE: Assets = Assets::new(bundle::FILES);

#[derive(clap::Args, Debug)]
pub struct Args {
    /// Port for the Inspector server (page + socket, on 127.0.0.1).
    #[arg(long, default_value_t = inspector_protocol::DEFAULT_PORT)]
    pub port: u16,
    /// Open on this app (its id: the registration's file stem under
    /// `~/.idealyst/apps`, e.g. `Todo-48213`).
    #[arg(long)]
    pub app: Option<String>,
    /// Don't open a browser; just serve.
    #[arg(long)]
    pub no_open: bool,
    /// Serve the front end from this staged web bundle (`idealyst build
    /// --web examples/inspector --out-dir <dir>`) instead of the copy
    /// embedded in this binary. For working on the Inspector itself.
    #[arg(long, value_name = "DIR")]
    pub bundle_dir: Option<std::path::PathBuf>,
}

pub fn run(args: Args) -> Result<()> {
    let assets = match &args.bundle_dir {
        Some(dir) => Assets::Dir(dir.canonicalize().with_context(|| format!("--bundle-dir {}", dir.display()))?),
        None => INSPECTOR_BUNDLE,
    };
    let hosted = ensure_server_with(args.port, assets)?;
    let url = page_url(&base_url(args.port), args.app.as_deref());
    match &hosted {
        Some(_) => eprintln!("[inspect] Inspector at {url} — Ctrl-C to stop"),
        None => eprintln!("[inspect] an Inspector server is already running; opening {url}"),
    }
    if !args.no_open {
        crate::cmd::dev::open_url_in_browser(&url);
    }
    if hosted.is_none() {
        return Ok(());
    }
    // The server runs on its own threads for the life of the process.
    loop {
        std::thread::sleep(Duration::from_secs(3600));
    }
}

/// Start the Inspector server on `port`, or find the one already there.
/// `Ok(None)` means another process serves it (keep using it); `Some`
/// must be held for as long as the server should run.
pub fn ensure_server(port: u16) -> Result<Option<inspector_server::Server>> {
    ensure_server_with(port, INSPECTOR_BUNDLE)
}

fn ensure_server_with(port: u16, assets: Assets) -> Result<Option<inspector_server::Server>> {
    let embedded_missing = if matches!(assets, Assets::Embedded(_)) { bundle::SKIPPED } else { None };
    if let Some(why) = embedded_missing {
        eprintln!(
            "[inspect] this idealyst binary was built without the Inspector's web front end ({why}). \
             The server still runs; rebuild the CLI with the wasm toolchain (wasm32-unknown-unknown, \
             wasm-bindgen, wasm-opt) to get the page."
        );
    }
    if inspector_server::probe(port) {
        return Ok(None);
    }
    let server = inspector_server::start(Config { port, assets, ..Config::default() })
        .with_context(|| format!("starting the Inspector server on 127.0.0.1:{port} (in use? pass --port)"))?;
    Ok(Some(server))
}

pub fn base_url(port: u16) -> String {
    format!("http://127.0.0.1:{port}")
}

/// The page URL, opening on `app` when given (`?app=`, percent-encoded:
/// an app's name, and so its id, can hold any character).
pub fn page_url(base: &str, app: Option<&str>) -> String {
    match app {
        None => format!("{base}/"),
        Some(id) => {
            let mut enc = String::new();
            for b in id.bytes() {
                if b.is_ascii_alphanumeric() || b"-_.~".contains(&b) {
                    enc.push(b as char);
                } else {
                    enc.push_str(&format!("%{b:02X}"));
                }
            }
            format!("{base}/?app={enc}")
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn page_url_encodes_the_app_id() {
        assert_eq!(page_url("http://127.0.0.1:9719", None), "http://127.0.0.1:9719/");
        assert_eq!(page_url("http://127.0.0.1:9719", Some("Todo-48213")), "http://127.0.0.1:9719/?app=Todo-48213");
        assert_eq!(page_url("http://x", Some("My App-1")), "http://x/?app=My%20App-1");
        assert_eq!(page_url("http://x", Some("Café-1")), "http://x/?app=Caf%C3%A9-1");
    }

    /// A second `inspect` (or `dev --inspect`) reuses the running server
    /// instead of failing on the busy port.
    #[test]
    fn a_running_server_is_reused() {
        let first = inspector_server::start(Config { port: 0, apps_dir: None, ..Config::default() }).unwrap();
        let port = first.addr.port();
        assert!(ensure_server(port).unwrap().is_none(), "the running server is found, not rebound");
    }
}
