//! Capturing an app build's manifest for `idealyst ota manifest`: what the
//! app offers bundles (its components and props, host functions, remote
//! mounts and context types), under its id.
//!
//! The manifest only exists inside a linked app: components register
//! themselves into linker-collected lists, and the host functions are the
//! list the app declares (`host_fns` in `[package.metadata.idealyst.ota]`).
//! So, like the MCP catalog ([`super::catalog_wrapper`]), this generates a
//! throwaway program that links the app's library — same lockfile, same
//! `[patch]`, its own target dir — and calls
//! `ota::manifest(&<lib>::<host_fns>())`, the function the app itself
//! runs at startup. Its output is the manifest the installed app reports,
//! as long as the app compiles the same components on the platform it
//! ships to as on this machine. Code behind `cfg(target_os)` can differ;
//! such an app reports its own manifest to a resolution service the first
//! time it asks, so a mismatch costs a round trip, not a wrong answer.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{anyhow, bail, Context, Result};
use build_ios::FrameworkSource;
use ota_index::Manifest;

use super::catalog_wrapper;
use crate::framework_source;

/// Where the capture program builds: its own target dir, so it never waits
/// on (or invalidates) the app's own builds.
const SIDECAR: &str = "idealyst-ota";

/// Build and run the capture program for the app at `dir`, whose host
/// functions are `host_fns` (a path from its library's root). Returns the
/// manifest, checked against its id.
pub fn capture(dir: &Path, host_fns: &str) -> Result<Manifest> {
    let root = fs::canonicalize(dir).with_context(|| format!("canonicalize {}", dir.display()))?;
    let app = build_ios::parse_manifest(&root).context("read the app's Cargo.toml")?;
    let source = framework_source::resolve(&root)?;
    let target_root = catalog_wrapper::catalog_target_root(&source, &root, None);
    let wrapper = target_root.join("idealyst").join(&app.name).join("ota-manifest");
    fs::create_dir_all(wrapper.join("src")).with_context(|| format!("create {}", wrapper.display()))?;

    write_if_changed(&wrapper.join("Cargo.toml"), &cargo_toml(&app.name, &root, &source))?;
    write_if_changed(&wrapper.join("src/main.rs"), &main_rs(host_fns)?)?;
    fs::create_dir_all(wrapper.join(".cargo"))?;
    let config = format!("[build]\ntarget-dir = \"{}\"\n{}", target_root.join(SIDECAR).display(), build_ios::registry_config_block());
    write_if_changed(&wrapper.join(".cargo/config.toml"), &config)?;
    seed_lockfile(&wrapper, &root)?;

    eprintln!("[ota] building {}'s manifest (links the app's library for this machine)…", app.name);
    let out = Command::new("cargo")
        .args(["run", "--quiet", "--manifest-path"])
        .arg(wrapper.join("Cargo.toml"))
        .current_dir(&wrapper)
        .output()
        .context("run cargo")?;
    if !out.status.success() {
        bail!(
            "building the app's manifest failed — is `{host_fns}` a public `fn() -> Vec<HostFnDef>` in {}'s library?\n{}",
            app.name,
            String::from_utf8_lossy(&out.stderr)
        );
    }
    Manifest::parse(&out.stdout).map_err(|e| anyhow!("the capture program's output: {e}"))
}

/// The capture program's manifest: the app by path, and `ota` resolved
/// the way the app resolves it (its version comes from the seeded lock).
fn cargo_toml(name: &str, root: &Path, source: &FrameworkSource) -> String {
    let ota = match source.registry_name() {
        Some(registry) => format!("{{ version = \"*\", registry = \"{registry}\" }}"),
        None => source.dep("crates/ota/client", &[]),
    };
    format!(
        r#"# GENERATED by `idealyst ota manifest`. Do not edit — rewritten on demand.
#
# Links the app's library and prints the manifest it offers bundles
# (`ota::manifest`), so the release location can answer for this build.
# Empty `[workspace]`: standalone, though it lives under a target dir.
[workspace]

[package]
name = "{name}-ota-manifest"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
app = {{ package = "{name}", path = "{root}" }}
ota = {ota}
{patch}"#,
        root = root.display(),
        patch = source.patch_block(),
    )
}

/// The capture program: the app's declared host functions, through the
/// same `ota::manifest` the app runs. The app's library is the dependency
/// `app`, whatever its name.
fn main_rs(host_fns: &str) -> Result<String> {
    let valid = !host_fns.is_empty()
        && !host_fns.starts_with("crate::")
        && host_fns.split("::").all(|seg| !seg.is_empty() && seg.chars().all(|c| c.is_alphanumeric() || c == '_'));
    if !valid {
        bail!("`host_fns = \"{host_fns}\"` isn't a path from the crate root, like \"app::host_fns\"");
    }
    Ok(format!(
        r#"//! GENERATED by `idealyst ota manifest`: print the app's manifest.
fn main() {{
    let manifest = ota::manifest(&app::{host_fns}());
    std::io::Write::write_all(&mut std::io::stdout(), &manifest.to_json()).expect("write the manifest");
}}
"#
    ))
}

/// Pin the program's dependencies to what the app builds against: the
/// app's lockfile, when it is newer than the program's.
fn seed_lockfile(wrapper: &Path, root: &Path) -> Result<()> {
    let Some(lock) = root.ancestors().map(|d| d.join("Cargo.lock")).find(|p| p.is_file()) else { return Ok(()) };
    let mine = wrapper.join("Cargo.lock");
    let newer = match (fs::metadata(&lock).and_then(|m| m.modified()), fs::metadata(&mine).and_then(|m| m.modified())) {
        (Ok(theirs), Ok(ours)) => theirs > ours,
        _ => true,
    };
    if newer {
        fs::copy(&lock, &mine).with_context(|| format!("seed {} from {}", mine.display(), lock.display()))?;
    }
    Ok(())
}

/// Rewrite only on change: cargo's fingerprints follow mtimes.
fn write_if_changed(path: &PathBuf, text: &str) -> Result<()> {
    if fs::read_to_string(path).ok().as_deref() == Some(text) {
        return Ok(());
    }
    fs::write(path, text).with_context(|| format!("write {}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_program_calls_the_declared_host_functions() {
        let main = main_rs("app::host_fns").unwrap();
        assert!(main.contains("ota::manifest(&app::app::host_fns())"), "{main}");
        for bad in ["crate::host_fns", "", "a b", "::x", "x::"] {
            assert!(main_rs(bad).is_err(), "{bad:?}");
        }
    }

    #[test]
    fn the_program_links_the_app_by_path_and_ota_as_the_app_does() {
        let source = FrameworkSource::Workspace { root: "/fw".into() };
        let toml = cargo_toml("shop", Path::new("/apps/shop"), &source);
        assert!(toml.contains("app = { package = \"shop\", path = \"/apps/shop\" }"), "{toml}");
        assert!(toml.contains("ota = { path = \"/fw/crates/ota/client\" }"), "{toml}");
        assert!(toml.contains("[workspace]"));
    }
}
