//! Build script: scan `guides/*.md`, parse each file's TOML
//! front-matter, and generate `OUT_DIR/guides_generated.rs` — a flat
//! list of `inventory::submit!(GuideEntry { … })` calls included from
//! `src/guides.rs`.
//!
//! Front-matter format (per-guide):
//!
//! ```text
//! +++
//! title = "Getting Started"
//! order = 10
//! tags = ["intro", "core"]
//! +++
//!
//! # Body markdown...
//! ```
//!
//! Slug = filename stem (e.g. `getting-started.md` → `getting-started`).
//! Missing front-matter fields fall back to: title=slug, order=999,
//! tags=[]. Body = everything after the second `+++` delimiter.

use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let guides_dir = manifest_dir.join("guides");
    println!("cargo:rerun-if-changed=guides");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let out_file = out_dir.join("guides_generated.rs");

    let mut entries: Vec<(String, String, u32, Vec<String>, PathBuf)> = Vec::new();

    if guides_dir.is_dir() {
        for ent in fs::read_dir(&guides_dir).expect("read guides dir") {
            let ent = ent.expect("dir entry");
            let path = ent.path();
            if path.extension().and_then(|s| s.to_str()) != Some("md") {
                continue;
            }
            let slug = path
                .file_stem()
                .and_then(|s| s.to_str())
                .map(|s| s.to_string())
                .expect("slug");
            // Rebuild when any individual guide file changes.
            println!("cargo:rerun-if-changed={}", path.display());
            let raw = fs::read_to_string(&path).expect("read guide");
            let (title, order, tags) = parse_front_matter(&raw, &slug);
            entries.push((slug, title, order, tags, path));
        }
    }

    entries.sort_by(|a, b| a.2.cmp(&b.2).then_with(|| a.0.cmp(&b.0)));

    let mut out = String::new();
    out.push_str("// AUTO-GENERATED by build.rs from guides/*.md — DO NOT EDIT.\n\n");
    for (slug, title, order, tags, path) in &entries {
        let tag_lits: Vec<String> = tags.iter().map(|t| format!("{:?}", t)).collect();
        let tag_array = tag_lits.join(", ");
        // include_str! reads from the source tree at compile time;
        // path must be a relative path or absolute. Use the absolute
        // path captured during this build so the include resolves
        // regardless of where rustc runs from.
        out.push_str(&format!(
            "inventory::submit! {{\n    crate::GuideEntry {{\n\
             \x20       slug: {:?},\n\
             \x20       title: {:?},\n\
             \x20       order: {},\n\
             \x20       tags: &[{}],\n\
             \x20       body: include_str!({:?}),\n\
             \x20       _seal: (),\n\
             \x20   }}\n}}\n\n",
            slug,
            title,
            order,
            tag_array,
            path.display().to_string(),
        ));
    }

    fs::write(&out_file, out).expect("write guides_generated.rs");
}

/// Parse the optional `+++` … `+++` TOML front-matter from the top of
/// a markdown file. Returns `(title, order, tags)`. Missing or
/// malformed front-matter yields the defaults: title = slug,
/// order = 999, tags = [].
fn parse_front_matter(raw: &str, slug: &str) -> (String, u32, Vec<String>) {
    let default_title = slug.to_string();
    if !raw.starts_with("+++") {
        return (default_title, 999, Vec::new());
    }
    let after_open = &raw[3..];
    let Some(end) = after_open.find("\n+++") else {
        return (default_title, 999, Vec::new());
    };
    let header = &after_open[..end];

    let mut title = default_title;
    let mut order: u32 = 999;
    let mut tags: Vec<String> = Vec::new();

    for line in header.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((key, value)) = line.split_once('=') else { continue };
        let key = key.trim();
        let value = value.trim();
        match key {
            "title" => {
                title = strip_quotes(value).to_string();
            }
            "order" => {
                if let Ok(n) = value.parse::<u32>() {
                    order = n;
                }
            }
            "tags" => {
                // Minimal TOML-array parser for `["a", "b"]`.
                let inner = value.trim_start_matches('[').trim_end_matches(']');
                tags = inner
                    .split(',')
                    .map(|s| strip_quotes(s.trim()).to_string())
                    .filter(|s| !s.is_empty())
                    .collect();
            }
            _ => {}
        }
    }
    (title, order, tags)
}

fn strip_quotes(s: &str) -> &str {
    let s = s.trim();
    if (s.starts_with('"') && s.ends_with('"') && s.len() >= 2)
        || (s.starts_with('\'') && s.ends_with('\'') && s.len() >= 2)
    {
        &s[1..s.len() - 1]
    } else {
        s
    }
}
