//! Emit idea-ui's default theme tokens as CSS custom properties + JSON.
//!
//! This is the deterministic converter behind `/design-sync`: the token
//! set it prints is exactly what `ThemeTokens::tokens()` installs at
//! runtime, so the CSS variable names match the `var(--<token>)` the web
//! backend emits for every `Tokenized<T>` (see `backend-web/src/style.rs`).
//! Nothing is restated by hand — a token added to the theme shows up here
//! on the next run.
//!
//!   cargo run -p idea-theme --example dump_tokens -- css   # :root blocks
//!   cargo run -p idea-theme --example dump_tokens -- json  # {light,dark}

use idea_theme::{
    dark_theme, light_theme, IdeaThemeRef, ThemeTokens, TokenValue, DEFAULT_FONT_STACK,
};
use runtime_core::Length;

fn render(v: &TokenValue) -> String {
    match v {
        TokenValue::Color(c) => c.0.clone(),
        TokenValue::Length(l) => match l {
            Length::Px(n) => format!("{}px", trim(*n)),
            Length::Percent(n) => format!("{}%", trim(*n)),
            Length::Auto => "0".into(),
            // `Length::Full` on a corner radius resolves to `min(w,h)/2`
            // (`Length::resolve_radius`). CSS reaches the same value from a
            // large px radius: the spec scales every radius down until no
            // pair overlaps a side, which clamps at exactly half the shorter
            // side. So 9999px *is* the pill here, not a magic number
            // approximating one — it stays a pill at any box size.
            Length::Full => "9999px".into(),
        },
        TokenValue::Number(n) => trim(*n),
    }
}

/// `12.0` -> `12`; keeps generated CSS free of pointless `.0` suffixes.
fn trim(n: f32) -> String {
    let s = format!("{n}");
    s.strip_suffix(".0").map(str::to_string).unwrap_or(s)
}

fn main() {
    let mode = std::env::args().nth(1).unwrap_or_else(|| "css".into());
    let light = IdeaThemeRef::new(light_theme()).tokens();
    let dark = IdeaThemeRef::new(dark_theme()).tokens();

    if mode == "json" {
        let block = |entries: &[idea_theme::TokenEntry]| {
            entries
                .iter()
                .map(|e| format!("    {:?}: {:?}", e.name, render(&e.value)))
                .collect::<Vec<_>>()
                .join(",\n")
        };
        println!("{{");
        println!("  \"font\": {DEFAULT_FONT_STACK:?},");
        println!("  \"light\": {{\n{}\n  }},", block(&light));
        println!("  \"dark\": {{\n{}\n  }}", block(&dark));
        println!("}}");
        return;
    }

    let decls = |entries: &[idea_theme::TokenEntry]| {
        entries
            .iter()
            .map(|e| format!("  --{}: {};", e.name, render(&e.value)))
            .collect::<Vec<_>>()
            .join("\n")
    };
    println!("/* idea-ui default theme — generated by `cargo run -p idea-theme --example dump_tokens`. Do not edit by hand. */");
    println!(":root {{");
    println!("  --iy-default-font: {DEFAULT_FONT_STACK};");
    println!("{}", decls(&light));
    println!("}}\n");
    println!("[data-theme=\"dark\"] {{");
    println!("{}", decls(&dark));
    println!("}}\n");
    println!("@media (prefers-color-scheme: dark) {{");
    println!("  :root:not([data-theme=\"light\"]) {{");
    println!(
        "{}",
        decls(&dark)
            .lines()
            .map(|l| format!("  {l}"))
            .collect::<Vec<_>>()
            .join("\n")
    );
    println!("  }}");
    println!("}}");
}
