//! # `sync` — offline-first cache + server synchronization
//!
//! A client-side cache layer that synchronizes server artifacts with a
//! device. The app:
//!
//! 1. **Downloads** a named slice of server data — a *partition* (e.g.
//!    `"project:123"`) — into the local cache.
//! 2. **Reads and mutates** it offline; the UI binds to a reactive
//!    `Signal` per partition.
//! 3. **Reconnects**, at which point queued mutations replay (the durable
//!    *outbox*) and server changes reconcile against local edits through a
//!    pluggable per-entity [`Merge`] policy.
//!
//! ## Shape
//!
//! The SDK is **client-side bookkeeping over two RPCs** —
//! [`pull`](protocol::PullRequest) and [`push`](protocol::PushRequest),
//! generic over the app's entity `T`. The app owns its entity types, the
//! server bodies of those two endpoints, and the `Merge` policy; the SDK
//! owns persistence, the outbox, the sync engine, and the protocol. The
//! app connects the two by implementing [`Transport`] (typically generated
//! by the `sync_entity!` macro) — which is why this crate has **no
//! dependency on `server`**: the protocol *types* are the only contract.
//!
//! ## Correctness model (v1)
//!
//! *Correct* means **no silent data loss, crash-safe across restarts, and
//! conflicts surfaced to the app** — under a single-writer-per-device
//! assumption. It does **not** mean automatic multi-device convergence,
//! real-time push, or CRDTs; those layer on top of the same cursor +
//! outbox + merge primitives without reworking them.
//!
//! The crash-safety model rests on one fact about the [`storage`] backing:
//! a single `set` is atomic, nothing spanning two keys is. So every state
//! transition commits via exactly one `set`, and everything else is
//! reconstructed on boot. The invariant, in one line: **the outbox commits
//! before the UI acknowledges; record-state commits before the outbox
//! pops; record-data commits before the cursor advances.**

#![deny(missing_docs)]

pub mod autosync;
mod coord;
mod engine;
mod error;
mod merge;
mod model;
mod outbox;
mod partition;
pub mod policy;
mod protocol;
mod store;
mod sync_store;

#[cfg(feature = "reference-server")]
pub mod reference;

pub use autosync::{PollingTrigger, SyncHandle, SyncTrigger};
pub use coord::SharedPartition;
pub use error::SyncError;
pub use merge::{Merge, MergeCtx, Resolution};
pub use model::{Cursor, Entry, EntryStatus, Id, Intent, Presence, Record, Rev, SyncState};
pub use partition::{Partition, SyncEngine};
pub use protocol::{
    Change, Op, OpKind, OpResult, PullMode, PullRequest, PullResponse, PushRequest, PushResponse,
    Transport, TransportFuture,
};
pub use sync_store::{KvSyncStore, MemorySyncStore, StoreFuture, SyncStore};

/// Generate a [`Transport`] impl that wires the engine to a pair of
/// app-authored `pull`/`push` server functions.
///
/// The app writes the two `#[server]` fns (with the real data access in
/// their bodies) and this macro removes the boilerplate of bridging them
/// to the engine — mapping the server fn's error to [`SyncError`].
///
/// ```ignore
/// // The app's two server fns over its entity `Project`:
/// #[server]
/// pub async fn pull_projects(req: sync::PullRequest)
///     -> Result<sync::PullResponse<Project>, ServerError> { /* DB read */ }
/// #[server]
/// pub async fn push_projects(req: sync::PushRequest<Project>)
///     -> Result<sync::PushResponse<Project>, ServerError> { /* DB write */ }
///
/// // One line wires them into a Transport the engine can call:
/// sync::sync_transport!(ProjectTransport, Project, pull = pull_projects, push = push_projects);
///
/// let transport = std::rc::Rc::new(ProjectTransport);
/// let projects = engine.partition::<Project>("project:123", transport).await?;
/// ```
///
/// Any error from the server fn (network, server 5xx, schema drift) is
/// mapped to [`SyncError::Transport`] via its `Display`. An app that wants
/// to distinguish an incompatible-schema (HTTP 426) response as
/// [`SyncError::IncompatibleVersion`] can detect it inside its own server
/// fn wrapper before returning.
#[macro_export]
macro_rules! sync_transport {
    ($transport:ident, $entity:ty, pull = $pull:path, push = $push:path $(,)?) => {
        /// Engine-to-server bridge generated by [`sync::sync_transport!`].
        pub struct $transport;

        impl $crate::Transport<$entity> for $transport {
            fn pull(
                &self,
                req: $crate::PullRequest,
            ) -> $crate::TransportFuture<'_, $crate::PullResponse<$entity>> {
                ::std::boxed::Box::pin(async move {
                    $pull(req)
                        .await
                        .map_err(|e| $crate::SyncError::Transport(::std::string::ToString::to_string(&e)))
                })
            }

            fn push(
                &self,
                req: $crate::PushRequest<$entity>,
            ) -> $crate::TransportFuture<'_, $crate::PushResponse<$entity>> {
                ::std::boxed::Box::pin(async move {
                    $push(req)
                        .await
                        .map_err(|e| $crate::SyncError::Transport(::std::string::ToString::to_string(&e)))
                })
            }
        }
    };
}
