//! Rebuilding a `#[component]` instance in place.
//!
//! A primitive's literal prop has a setter on the backend seam, so a
//! live patch is one call. A component's does not: its props were
//! consumed and its body already ran. The only way to show a new
//! `Button(label = "…")` without recompiling is to run that component
//! again with the new value and swap its subtree.
//!
//! Running it again needs its props, which are gone. So the call site
//! keeps a COPY — but only when the props type is `Clone`, and a
//! `#[component]` is not required to be. That is what
//! [`Probe`] is for.
//!
//! # Deciding on `Clone` without a bound
//!
//! Autoref specialization. `(&Probe(&props)).rebuilder()` resolves to
//! [`ViaClone`] when the props type satisfies its bounds, and otherwise
//! autorefs once more and lands on [`ViaFallback`], which answers
//! `None`. Method probing tries the receiver type before adding a
//! reference, so the more specific impl wins when it applies and is
//! simply not a candidate when it does not — no specialization feature,
//! no bound on `#[component]`, and a props type that is not `Clone`
//! still compiles.
//!
//! [`OverlayProps`] rather than `Clone` alone is the other half:
//! `__apply_literal` is an INHERENT method, so a generic body cannot
//! call it — it would bind the blanket fallback and apply nothing.
//! `#[component]` generates a real `impl OverlayProps`, which a generic
//! body can call and which a props type the macros never touched simply
//! does not have.
//!
//! # What a rebuild costs
//!
//! Signals created inside that component body are recreated, so state
//! local to the component resets. That is not a new class of surprise:
//! a state-driven rebuild of the parent site already does exactly this,
//! and an author who keeps state that must survive re-renders already
//! has to lift it. It IS worth knowing while editing, which is why the
//! applier reports what it rebuilt.

use std::any::Any;
use std::cell::RefCell;
use std::rc::Rc;

use runtime_scene::Element;
use runtime_template::LiteralValue;

/// Build a component's `Element` again from a remembered copy of its
/// props, with these literals applied.
pub type Rebuilder = Rc<dyn Fn(&[(String, LiteralValue)]) -> Element>;

/// What a props type must offer for its instances to be rebuildable.
///
/// Generated by `#[component]` / `#[props]` as a REAL impl, because a
/// generic rebuild body cannot reach an inherent `__apply_literal`. A
/// props type without the macro does not implement it, which is exactly
/// how [`Probe`] tells the two apart.
pub trait OverlayProps: Sized {
    /// Apply one literal by prop name; `false` when this type has no
    /// such prop, or none of that shape.
    fn overlay_apply(&mut self, name: &str, value: &LiteralValue) -> bool;
    /// Run the component.
    fn overlay_build(self) -> Element;
}

/// The autoref-specialization probe. See the module docs.
pub struct Probe<'a, T: ?Sized>(pub &'a T);

/// The impl that applies when the props are `Clone` and macro-generated.
pub trait ViaClone {
    fn rebuilder(&self) -> Option<Rebuilder>;
}

impl<T: Clone + OverlayProps + 'static> ViaClone for Probe<'_, T> {
    fn rebuilder(&self) -> Option<Rebuilder> {
        let base = self.0.clone();
        Some(Rc::new(move |literals: &[(String, LiteralValue)]| {
            let mut props = base.clone();
            for (name, value) in literals {
                props.overlay_apply(name, value);
            }
            props.overlay_build()
        }))
    }
}

/// The impl that applies otherwise. One more autoref away, so it is
/// only reached when [`ViaClone`] is not a candidate.
pub trait ViaFallback {
    fn rebuilder(&self) -> Option<Rebuilder> {
        None
    }
}

impl<T: ?Sized> ViaFallback for &Probe<'_, T> {}

/// A rebuilder on its way from a `ui!` call site to the mounted node,
/// type-erased so `runtime-scene` can carry it without knowing what a
/// component is.
pub(crate) fn erase(rebuilder: Option<Rebuilder>) -> Option<Rc<dyn Any>> {
    rebuilder.map(|r| Rc::new(r) as Rc<dyn Any>)
}

/// The inverse of [`erase`].
pub(crate) fn recover(erased: &Rc<dyn Any>) -> Option<Rebuilder> {
    erased.downcast_ref::<Rebuilder>().cloned()
}

thread_local! {
    /// Scopes owned by subtrees a patch swapped in, keyed by the
    /// instance they replaced.
    ///
    /// A realized subtree's `Realized` IS its scope; dropping it
    /// unmounts. The tree it replaced had an owner — the enclosing
    /// region — and the replacement has none, so it is held here.
    ///
    /// Keyed per INSTANCE, and replaced rather than cleared per site.
    /// Clearing a site's holds at the start of an apply drops the
    /// subtree the LAST patch put on screen — including when this patch
    /// does not touch that instance at all. That is how a second edit to
    /// the same component made it vanish.
    static REBUILT: RefCell<Vec<(Key, Box<dyn Any>)>> = const {
        RefCell::new(Vec::new())
    };
}

/// Which instance a held scope belongs to: its site, its node index, and
/// which of that pair's live instances it is (a `for` has several).
type Key = (u64, u32, usize);

/// Take ownership of a swapped-in subtree, dropping whatever it
/// replaced.
///
/// The drop happens LAST, after the new scope is stored: the old
/// subtree's nodes are already detached from the backend by the time
/// this is called, and unmounting it before the replacement is recorded
/// would leave a window with neither.
pub(crate) fn hold(key: Key, realized: Box<dyn Any>) {
    let previous = REBUILT.with(|r| {
        let mut r = r.borrow_mut();
        match r.iter().position(|(k, _)| *k == key) {
            Some(at) => Some(std::mem::replace(&mut r[at].1, realized)),
            None => {
                r.push((key, realized));
                None
            }
        }
    });
    drop(previous);
}

pub(crate) fn release_all() {
    REBUILT.with(|r| r.borrow_mut().clear());
}
