//! `lint` — wire the idealyst source linter into rust-analyzer so idiom-drift
//! findings show up as inline editor squiggles alongside `cargo check`.
//!
//! rust-analyzer has no lint-plugin API, but its flycheck runs an arbitrary
//! command and renders the cargo-JSON diagnostics it prints. We point
//! `check.overrideCommand` at a small wrapper script that emits BOTH
//! `cargo check`'s JSON and `idealyst lint --format json`'s, so type errors
//! and lint findings appear together. See `docs/devcontainer.md` and the
//! `crates/tools/lint/README.md` rust-analyzer section for the rationale.
//!
//! Two non-obvious details this encodes (per the 0.3 migration notes):
//! - The command is `["sh", ".vscode/ra-check.sh"]`, and the script passes
//!   `"$PWD"` (the workspace root RA runs it from) as the lint path — RA does
//!   not reliably expand `${workspaceFolder}` inside `overrideCommand`.
//! - `rust-analyzer.diagnostics.disabled` turns off RA's built-in
//!   `non_snake_case`/`incorrect-case` checks: RA can't see the
//!   `#[allow(non_snake_case)]` that `#[component]` injects for PascalCase
//!   component fns, so without this it would falsely flag every component.

use std::path::{Path, PathBuf};

use serde_json::{json, Value};

use crate::vscode::aspect::{AspectContribution, ManagedFile, VscodeAspect};

pub struct Lint;

/// Path (relative to the project) of the rust-analyzer check wrapper.
pub const RA_CHECK_SCRIPT: &str = ".vscode/ra-check.sh";

const RA_CHECK_CONTENTS: &str = "\
#!/bin/sh
# Generated by `idealyst configure vscode` — MANAGED BY IDEALYST.
#
# rust-analyzer runs this as its check command (see the
# `rust-analyzer.check.overrideCommand` setting). It emits BOTH cargo check's
# JSON diagnostics AND idealyst lint's idiom-drift diagnostics as one
# cargo-JSON stream, so type errors and lint findings appear together as
# editor squiggles.
#
# `idealyst lint` needs an ABSOLUTE path: $PWD is the workspace root RA runs
# this script from, and RA does not reliably expand ${workspaceFolder} inside
# overrideCommand. Regenerated by `idealyst configure vscode`.
cargo check --message-format=json
idealyst lint --format json \"$PWD\"
";

impl VscodeAspect for Lint {
    fn id(&self) -> &'static str {
        "lint"
    }
    fn label(&self) -> &'static str {
        "Inline lint (rust-analyzer)"
    }
    fn description(&self) -> &'static str {
        "Run idealyst lint as rust-analyzer's check command so idiom drift shows as squiggles"
    }

    fn contribution(&self, _dir: &Path) -> AspectContribution {
        AspectContribution {
            set_keys: vec![(
                "rust-analyzer.check.overrideCommand".into(),
                json!(["sh", RA_CHECK_SCRIPT]),
            )],
            union_arrays: vec![(
                "rust-analyzer.diagnostics.disabled".into(),
                vec![Value::from("non_snake_case"), Value::from("incorrect-case")],
            )],
            recommendations: Vec::new(),
            files: vec![ManagedFile {
                rel: PathBuf::from(RA_CHECK_SCRIPT),
                contents: RA_CHECK_CONTENTS.to_string(),
                executable: true,
            }],
        }
    }
}
