//! The JavaScript the web-glue build pass writes, from a [`Glue`] that
//! [`crate::glue::extract`] read out of a linked module.
//!
//! Two shapes (see `docs/proposals/own-web-bindings.md`):
//!
//! * [`loader_js`] — **own mode**, no wasm-bindgen: `pkg/<lib>.js` itself,
//!   with wasm-bindgen's `--target web` entry contract (default `init`,
//!   named `initSync`, idempotent re-init returning the raw exports).
//! * [`hybrid_glue_js`] — **hybrid mode**, wasm-bindgen owns
//!   `pkg/<lib>.js`: `pkg/__idealyst_glue.js`, the ES module
//!   wasm-bindgen's output imports for the `./__idealyst_glue.js`
//!   namespace.
//!
//! Both publish `globalThis.__idealystGlue` — the hot-patch loader's two
//! entry points (`compileImport`, `registerRecords`) and, for a hybrid
//! page, the HYBRID-BRIDGE (`web_glue::bridge`).
//!
//! Both shapes also carry the worker contract `web_glue::worker` relies
//! on: the file reports its own URL to the runtime (`G.entry`) and exports
//! `__glueWorkerInit(module?)`, which a Worker that `import()`s the file
//! calls to instantiate the same wasm and get its raw exports. The file a
//! worker imports is the one whose code embeds the runtime — `<lib>.js` in
//! own mode, `__idealyst_glue.js` in hybrid mode — so `import.meta.url` at
//! that point is always the right URL, under every fingerprinted name.
//!
//! Lives here rather than in build-web so that a small tool (the wasm test
//! runner wrapper, `src/bin/wasm-glue-test-runner.rs`) can produce the
//! same file without linking the whole build crate.

use std::fmt::Write as _;

use crate::glue::{Glue, IMPORT_MODULE};

fn indent_block(src: &str) -> String {
    let mut out = String::with_capacity(src.len() + src.len() / 16);
    for line in src.lines() {
        if !line.is_empty() {
            out.push_str("  ");
        }
        out.push_str(line);
        out.push('\n');
    }
    out
}

/// FNV-1a over the UTF-8 bytes: the identity a hot patch's module record
/// is compared against (`registerRecords` computes the same in JS).
pub fn source_hash(src: &str) -> u32 {
    let mut h: u32 = 0x811c_9dc5;
    for b in src.bytes() {
        h ^= b as u32;
        h = h.wrapping_mul(0x0100_0193);
    }
    h
}

/// The runtime + module prelude shared by both modes: defines `G`.
fn prelude_js(glue: &Glue) -> String {
    let mut js = String::new();
    match &glue.runtime {
        Some(runtime) => {
            js.push_str("const G = (function () {\n");
            js.push_str(&indent_block(runtime));
            js.push_str("})();\n");
        }
        None => js.push_str("const G = null;\n"),
    }
    for m in &glue.modules {
        let _ = writeln!(js, "G.module({}, function (G) {{", json_string(&m.name));
        js.push_str(&indent_block(&m.source));
        js.push_str("});\n");
    }
    js
}

/// One `name: (snippet),` entry per glue import.
fn snippet_entries(glue: &Glue, prefix: &str, sep: &str, suffix: &str) -> String {
    let mut js = String::new();
    for imp in &glue.imports {
        let _ = writeln!(js, "// {}", imp.key.replace('\n', " "));
        let body = if imp.catch {
            format!("G.catching((\n{}\n))", imp.js.trim())
        } else {
            format!("(\n{}\n)", imp.js.trim())
        };
        let _ = writeln!(js, "{prefix}{}{sep}{body}{suffix}", imp.short);
    }
    js
}

/// A JS string literal.
pub fn json_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\u{2028}' => out.push_str("\\u2028"),
            '\u{2029}' => out.push_str("\\u2029"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\u{:04x}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// `pkg/<lib>.js` for own mode.
pub fn loader_js(glue: &Glue, lib_name: &str) -> String {
    let mut js = String::from(
        "// Generated by the web-glue build pass from the records and import\n\
         // snippets carried inside the wasm. Do not edit.\n",
    );
    for (i, m) in glue.foreign_import_modules.iter().enumerate() {
        let _ = writeln!(js, "import * as __foreign{i} from {};", json_string(m));
    }
    js.push_str(&prelude_js(glue));
    js.push_str(&global_js(glue));
    js.push_str("const __glue = {\n");
    js.push_str(&snippet_entries(glue, "  ", ": ", ","));
    js.push_str("};\n");
    let _ = write!(js, "const __imports = {{ {}: __glue", json_string(IMPORT_MODULE));
    for (i, m) in glue.foreign_import_modules.iter().enumerate() {
        let _ = write!(js, ", {}: __foreign{i}", json_string(m));
    }
    js.push_str(" };\n");
    let _ = write!(
        js,
        r#"
let wasm;
let __pending;
// The compiled module, when this loader saw it: handed to workers
// (`web_glue::worker`) so they skip the fetch + compile.
let __module;
if (G !== null && typeof G.entry === "function") G.entry(import.meta.url, () => __module);

function __finalize(instance) {{
  if (wasm !== undefined) return wasm;
  wasm = instance.exports;
  if (G !== null) G.attach(wasm);
  // Constructors run exactly once. A reactor exports `__wasm_call_ctors`
  // and it runs here; a command module (how `idealyst build` links a bin)
  // runs them inside `main`'s LLD wrapper, the one export the build leaves
  // wrapped (`wasm_carve::command_exports`).
  if (typeof wasm.__wasm_call_ctors === "function") wasm.__wasm_call_ctors();
  if (typeof wasm.main === "function") wasm.main(0, 0);
  return wasm;
}}

export function initSync(module) {{
  if (wasm !== undefined) return wasm;
  if (module !== undefined && module !== null && Object.getPrototypeOf(module) === Object.prototype) {{
    module = module.module;
  }}
  if (!(module instanceof WebAssembly.Module)) module = new WebAssembly.Module(module);
  __module = module;
  return __finalize(new WebAssembly.Instance(module, __imports));
}}

async function __instantiate(input) {{
  if (input !== undefined && input !== null && Object.getPrototypeOf(input) === Object.prototype) {{
    input = input.module_or_path;
  }}
  if (input === undefined) input = new URL({wasm_name}, import.meta.url);
  if (typeof input === "string" || input instanceof URL ||
      (typeof Request === "function" && input instanceof Request)) {{
    input = fetch(input);
  }}
  input = await input;
  if (input instanceof WebAssembly.Module) {{
    __module = input;
    return new WebAssembly.Instance(input, __imports);
  }}
  let r;
  if (typeof Response === "function" && input instanceof Response) {{
    if (typeof WebAssembly.instantiateStreaming === "function" &&
        input.headers.get("Content-Type") === "application/wasm") {{
      r = await WebAssembly.instantiateStreaming(input, __imports);
    }} else {{
      input = await input.arrayBuffer();
    }}
  }}
  if (r === undefined) r = await WebAssembly.instantiate(input, __imports);
  __module = r.module;
  return r.instance;
}}

export default function init(input) {{
  if (wasm !== undefined) return Promise.resolve(wasm);
  return (__pending ??= __instantiate(input).then(__finalize));
}}

// Worker entry (`web_glue::worker`): instantiate in this worker from the
// parent's compiled module when it sent one, else fetch like `init()`.
export function __glueWorkerInit(module) {{
  if (module instanceof WebAssembly.Module) return Promise.resolve(initSync({{ module }}));
  return init();
}}
"#,
        wasm_name = json_string(&format!("{lib_name}_bg.wasm")),
    );
    js
}

/// Whether a module needs a glue file at all: wasm-bindgen only imports
/// `./__idealyst_glue.js` when some glue import survived linking.
pub fn needs_glue_file(glue: &Glue) -> bool {
    !glue.imports.is_empty() || glue.runtime.is_some()
}

/// `pkg/__idealyst_glue.js` for hybrid mode: the glue namespace as an ES
/// module wasm-bindgen's generated JS imports
/// (`import * as … from "./__idealyst_glue.js"`), where `bindgen_js` is the
/// specifier the PAGE imports that generated JS by (`<lib>.js`;
/// `wasm-bindgen-test`, extension-less, under the test runner). It must
/// match the page's specifier exactly: ES modules are keyed by URL, and a
/// different spelling loads a second, uninitialized copy of wasm-bindgen's
/// module whose `initSync` then instantiates from nothing.
///
/// wasm-bindgen owns instantiation, so `G` attaches lazily through
/// `initSync()`, which returns the raw exports once the instance exists.
/// The import is circular (`<lib>.js` ⇄ this file); that is safe because
/// `initSync` is a hoisted function declaration and is only called at
/// glue-call time — never while either module is still evaluating.
pub fn hybrid_glue_js(glue: &Glue, bindgen_js: &str) -> String {
    let mut js = String::from(
        "// Generated by the web-glue build pass (hybrid mode). Do not edit.\n",
    );
    let spec = json_string(&format!("./{bindgen_js}"));
    let _ = writeln!(js, "import {{ initSync }} from {spec};");
    // A namespace import, not `import init from`: a bindgen output without a
    // default export must still link (the worker entry then reports it).
    let _ = writeln!(js, "import * as __bindgen from {spec};");
    js.push_str(&prelude_js(glue));
    js.push_str("if (G !== null) G.lazyAttach(() => initSync(undefined));\n");
    let stem = bindgen_js.strip_suffix(".js").unwrap_or(bindgen_js);
    js.push_str(&HYBRID_WORKER_JS.replace("__WASM__", &json_string(&format!("{stem}_bg.wasm"))));
    js.push_str(&global_js(glue));
    js.push_str(&snippet_entries(glue, "export const ", " = ", ";"));
    js
}

/// `globalThis.__idealystGlue` plus the record hashes it compares a hot
/// patch's records against. Both shapes carry it: the hot-patch loader
/// (`backend_web::hot_patch`) reaches the page's runtime only through it,
/// in an own-mode dev session as much as in a hybrid one.
fn global_js(glue: &Glue) -> String {
    let mut js = String::from("const __moduleHash = new Map([");
    for m in &glue.modules {
        let _ = write!(js, "[{}, {}], ", json_string(&m.name), source_hash(&m.source));
    }
    js.push_str("]);\n");
    let runtime_hash = glue.runtime.as_deref().map(source_hash).unwrap_or(0);
    let _ = write!(js, "const __runtimeHash = {runtime_hash};\n");
    js.push_str(GLOBAL_JS);
    js
}

/// The worker contract in hybrid mode (see the module docs). wasm-bindgen
/// keeps its compiled module private, so a worker fetches and compiles the
/// wasm itself through wasm-bindgen's `init`, given the URL explicitly:
/// `__WASM__` becomes `"<bindgen stem>_bg.wasm"`, resolved next to this
/// file. Not wasm-bindgen's built-in default — wasm-bindgen-test-runner's
/// output omits it (its page passes the path), and an `init()` without one
/// fails with "Argument 0 must be a buffer source". The literal is also
/// what `build_web::fingerprint_pkg` rewrites to the hashed wasm name (it
/// replaces `.wasm` names anywhere in a pkg JS file).
const HYBRID_WORKER_JS: &str = r#"if (G !== null && typeof G.entry === "function") G.entry(import.meta.url);
export function __glueWorkerInit(module) {
  const init = __bindgen.default;
  if (typeof init !== "function") {
    throw new Error("web-glue: the wasm-bindgen output has no default init export to start a worker with");
  }
  return init({ module_or_path: module instanceof WebAssembly.Module ? module : new URL(__WASM__, import.meta.url) });
}
"#;

/// `globalThis.__idealystGlue` (see [`global_js`]). The record framing below is
/// `web_glue::record`'s (magic `IGLU`, version 1, kind, name, source) —
/// the same one [`crate::glue::parse_records`] reads.
const GLOBAL_JS: &str = r#"function __fnv(s) {
  let h = 0x811c9dc5;
  for (const b of new TextEncoder().encode(s)) h = Math.imul(h ^ b, 0x01000193) >>> 0;
  return h >>> 0;
}
globalThis.__idealystGlue = {
  // HYBRID-BRIDGE (`web_glue::bridge`): a wasm-bindgen value into the glue
  // slab, and a glue handle back out. Only a hybrid page has a caller.
  add: (v) => G.add(v),
  get: (h) => G.get(h),
  // Hot patch: a patch module's glue import, compiled from the JS its
  // import name carries (`<key>\n<flags>\n<js>`). Dev only — the page's
  // hot-patch loader is the one caller.
  compileImport(name) {
    const a = name.indexOf("\n");
    const b = name.indexOf("\n", a + 1);
    if (a < 0 || b < 0) throw new Error(`web-glue: malformed glue import ${JSON.stringify(name)}`);
    const flags = name.slice(a + 1, b).split(",").filter((f) => f !== "");
    for (const f of flags) if (f !== "catch") throw new Error(`web-glue: unknown glue flag ${f}`);
    const f = new Function("G", `return (${name.slice(b + 1)});`)(G);
    return flags.includes("catch") ? G.catching(f) : f;
  },
  // Hot patch: the `__idealyst_glue` records a patch module carries. A
  // module this page already has must carry the SAME source (a changed
  // module needs a reload: its old factory may already have run); a new
  // module is registered.
  registerRecords(bytes) {
    const u8 = new Uint8Array(bytes);
    const dv = new DataView(u8.buffer, u8.byteOffset, u8.byteLength);
    const dec = new TextDecoder();
    let at = 0;
    while (at < u8.length) {
      if (u8.length - at < 12 || dec.decode(u8.subarray(at, at + 4)) !== "IGLU" || u8[at + 4] !== 1) {
        throw new Error("web-glue: the patch's glue section is not IGLU v1 records");
      }
      const kind = u8[at + 5];
      const nl = dv.getUint16(at + 6, true);
      const sl = dv.getUint32(at + 8, true);
      const name = dec.decode(u8.subarray(at + 12, at + 12 + nl));
      const src = dec.decode(u8.subarray(at + 12 + nl, at + 12 + nl + sl));
      at += 12 + nl + sl;
      const hash = __fnv(src);
      if (kind === 0) {
        if (hash !== __runtimeHash) throw new Error("web-glue: the patch carries a different web-glue runtime — reload");
      } else if (__moduleHash.has(name)) {
        if (__moduleHash.get(name) !== hash) throw new Error(`web-glue: the patch changes JS module "${name}" — reload`);
      } else {
        __moduleHash.set(name, hash);
        G.module(name, new Function("G", src));
      }
    }
  },
};
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::glue::{GlueImport, GlueRecord, KIND_MODULE};

    fn glue() -> Glue {
        Glue {
            wasm: Vec::new(),
            imports: vec![
                GlueImport { short: "g0".into(), key: "a::f(u32)".into(), catch: false, js: "(x) => x".into() },
                GlueImport { short: "g1".into(), key: "a::g()".into(), catch: true, js: "() => { throw 1; }".into() },
            ],
            runtime: Some("return { module() {}, attach() {}, lazyAttach() {}, catching(f) { return f; } };".into()),
            modules: vec![GlueRecord { kind: KIND_MODULE, name: "m\"x".into(), source: "return 1;".into() }],
            foreign_import_modules: vec!["./__wasm_split.js".into()],
            section_bytes: 0,
            wasm_bindgen: None,
        }
    }

    #[test]
    fn the_own_loader_keeps_wasm_bindgens_entry_contract() {
        let js = loader_js(&glue(), "my_app");
        assert!(js.contains("export default function init(input)"));
        assert!(js.contains("export function initSync(module)"));
        assert!(js.contains("if (wasm !== undefined) return wasm;"));
        assert!(js.contains("new URL(\"my_app_bg.wasm\", import.meta.url)"));
        assert!(js.contains("import * as __foreign0 from \"./__wasm_split.js\";"));
        assert!(js.contains("G.module(\"m\\\"x\", function (G) {"));
        assert!(js.contains("g0: (\n(x) => x\n),"));
        assert!(js.contains("g1: G.catching(("));
        // The hot-patch loader's entry points, in an own-mode page too.
        assert!(js.contains("globalThis.__idealystGlue = {"));
        assert!(js.contains("compileImport(name)") && js.contains("registerRecords(bytes)"));
        assert!(js.contains(&format!("[\"m\\\"x\", {}]", source_hash("return 1;"))));
        assert!(js.find("const G = ").unwrap() < js.find("globalThis.__idealystGlue").unwrap());
        let attach = js.find("G.attach(wasm)").unwrap();
        let ctors = js.find("wasm.__wasm_call_ctors()").unwrap();
        let main = js.find("wasm.main(0, 0)").unwrap();
        assert!(attach < ctors && ctors < main);
    }

    #[test]
    fn the_hybrid_module_exports_every_snippet_attaches_lazily_and_publishes_the_bridge() {
        let js = hybrid_glue_js(&glue(), "my_app.js");
        assert!(js.contains("import { initSync } from \"./my_app.js\";"));
        assert!(js.contains("G.lazyAttach(() => initSync(undefined));"));
        assert!(js.contains("export const g0 = (\n(x) => x\n);"));
        assert!(js.contains("export const g1 = G.catching(("));
        assert!(js.contains("globalThis.__idealystGlue = {"));
        assert!(js.contains(&format!("[\"m\\\"x\", {}]", source_hash("return 1;"))));
    }

    /// `web_glue::worker`'s contract: the file whose code embeds the runtime
    /// reports its own URL and exports `__glueWorkerInit`. Own mode also hands
    /// the compiled module over, recorded on every instantiation path.
    #[test]
    fn both_shapes_carry_the_worker_contract() {
        let own = loader_js(&glue(), "my_app");
        assert!(own.contains("G.entry(import.meta.url, () => __module)"));
        assert!(own.contains("export function __glueWorkerInit(module)"));
        assert!(own.contains("initSync({ module })"));
        // initSync, a Module input, and both instantiate paths record it.
        assert_eq!(own.matches("__module = ").count(), 3, "{own}");
        let hybrid = hybrid_glue_js(&glue(), "my_app.js");
        assert!(hybrid.contains("import * as __bindgen from \"./my_app.js\";"));
        assert!(hybrid.contains("G.entry(import.meta.url);"));
        assert!(hybrid.contains("new URL(\"my_app_bg.wasm\", import.meta.url)"), "{hybrid}");
        let runner = hybrid_glue_js(&glue(), "wasm-bindgen-test");
        assert!(runner.contains("new URL(\"wasm-bindgen-test_bg.wasm\", import.meta.url)"));
        assert!(hybrid.contains("export function __glueWorkerInit(module)"));
        // `G.entry` must run after `G` exists.
        assert!(hybrid.find("const G = ").unwrap() < hybrid.find("G.entry(").unwrap());
        assert!(own.find("const G = ").unwrap() < own.find("G.entry(").unwrap());
    }

    #[test]
    fn source_hash_is_fnv1a_over_utf8() {
        // Reference values of 32-bit FNV-1a; the JS `__fnv` must agree
        // (checked under node below).
        assert_eq!(source_hash(""), 0x811c_9dc5);
        assert_eq!(source_hash("a"), 0xe40c_292c);
    }

    #[test]
    fn generated_js_parses_and_the_js_hash_agrees_under_node() {
        let Ok(out) = std::process::Command::new("node").arg("--version").output() else { return };
        if !out.status.success() {
            return;
        }
        let dir = std::env::temp_dir().join(format!("glue-js-syntax-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        for (name, js) in [("a.mjs", loader_js(&glue(), "x")), ("b.mjs", hybrid_glue_js(&glue(), "x.js"))] {
            let p = dir.join(name);
            std::fs::write(&p, js).unwrap();
            let st = std::process::Command::new("node").arg("--check").arg(&p).output().unwrap();
            assert!(st.status.success(), "{name}: {}", String::from_utf8_lossy(&st.stderr));
        }
        let src = "é ✓ 🦀 return 1;";
        let fnv = GLOBAL_JS.split("globalThis.__idealystGlue").next().unwrap();
        let probe = format!("{fnv}\nprocess.stdout.write(String(__fnv({})));", json_string(src));
        let out = std::process::Command::new("node").args(["-e", &probe]).output().unwrap();
        assert_eq!(String::from_utf8_lossy(&out.stdout), source_hash(src).to_string());
        let _ = std::fs::remove_dir_all(&dir);
    }
}
