//! The JavaScript the web-glue build pass writes, from a [`Glue`] that
//! [`crate::glue::extract`] read out of a linked module.
//!
//! Two shapes (see `docs/proposals/own-web-bindings.md`):
//!
//! * [`loader_js`] — **own mode**, no wasm-bindgen: `pkg/<lib>.js` itself,
//!   with wasm-bindgen's `--target web` entry contract (default `init`,
//!   named `initSync`, idempotent re-init returning the raw exports).
//! * [`hybrid_glue_js`] — **hybrid mode**, wasm-bindgen owns
//!   `pkg/<lib>.js`: `pkg/__idealyst_glue.js`, the ES module
//!   wasm-bindgen's output imports for the `./__idealyst_glue.js`
//!   namespace. It also publishes `globalThis.__idealystGlue` — the
//!   HYBRID-BRIDGE (`web_glue::bridge`) and the hot-patch loader's two
//!   entry points (`compileImport`, `registerRecords`).
//!
//! Lives here rather than in build-web so that a small tool (the wasm test
//! runner wrapper, `src/bin/wasm-glue-test-runner.rs`) can produce the
//! same file without linking the whole build crate.

use std::fmt::Write as _;

use crate::glue::{Glue, IMPORT_MODULE};

fn indent_block(src: &str) -> String {
    let mut out = String::with_capacity(src.len() + src.len() / 16);
    for line in src.lines() {
        if !line.is_empty() {
            out.push_str("  ");
        }
        out.push_str(line);
        out.push('\n');
    }
    out
}

/// FNV-1a over the UTF-8 bytes: the identity a hot patch's module record
/// is compared against (`registerRecords` computes the same in JS).
pub fn source_hash(src: &str) -> u32 {
    let mut h: u32 = 0x811c_9dc5;
    for b in src.bytes() {
        h ^= b as u32;
        h = h.wrapping_mul(0x0100_0193);
    }
    h
}

/// The runtime + module prelude shared by both modes: defines `G`.
fn prelude_js(glue: &Glue) -> String {
    let mut js = String::new();
    match &glue.runtime {
        Some(runtime) => {
            js.push_str("const G = (function () {\n");
            js.push_str(&indent_block(runtime));
            js.push_str("})();\n");
        }
        None => js.push_str("const G = null;\n"),
    }
    for m in &glue.modules {
        let _ = writeln!(js, "G.module({}, function (G) {{", json_string(&m.name));
        js.push_str(&indent_block(&m.source));
        js.push_str("});\n");
    }
    js
}

/// One `name: (snippet),` entry per glue import.
fn snippet_entries(glue: &Glue, prefix: &str, sep: &str, suffix: &str) -> String {
    let mut js = String::new();
    for imp in &glue.imports {
        let _ = writeln!(js, "// {}", imp.key.replace('\n', " "));
        let body = if imp.catch {
            format!("G.catching((\n{}\n))", imp.js.trim())
        } else {
            format!("(\n{}\n)", imp.js.trim())
        };
        let _ = writeln!(js, "{prefix}{}{sep}{body}{suffix}", imp.short);
    }
    js
}

/// A JS string literal.
pub fn json_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\u{2028}' => out.push_str("\\u2028"),
            '\u{2029}' => out.push_str("\\u2029"),
            c if (c as u32) < 0x20 => {
                let _ = write!(out, "\\u{:04x}", c as u32);
            }
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// `pkg/<lib>.js` for own mode.
pub fn loader_js(glue: &Glue, lib_name: &str) -> String {
    let mut js = String::from(
        "// Generated by the web-glue build pass from the records and import\n\
         // snippets carried inside the wasm. Do not edit.\n",
    );
    for (i, m) in glue.foreign_import_modules.iter().enumerate() {
        let _ = writeln!(js, "import * as __foreign{i} from {};", json_string(m));
    }
    js.push_str(&prelude_js(glue));
    js.push_str("const __glue = {\n");
    js.push_str(&snippet_entries(glue, "  ", ": ", ","));
    js.push_str("};\n");
    let _ = write!(js, "const __imports = {{ {}: __glue", json_string(IMPORT_MODULE));
    for (i, m) in glue.foreign_import_modules.iter().enumerate() {
        let _ = write!(js, ", {}: __foreign{i}", json_string(m));
    }
    js.push_str(" };\n");
    let _ = write!(
        js,
        r#"
let wasm;
let __pending;

function __finalize(instance) {{
  if (wasm !== undefined) return wasm;
  wasm = instance.exports;
  if (G !== null) G.attach(wasm);
  // Reactor module: constructors run once, here, never per export call.
  if (typeof wasm.__wasm_call_ctors === "function") wasm.__wasm_call_ctors();
  if (typeof wasm.main === "function") wasm.main(0, 0);
  return wasm;
}}

export function initSync(module) {{
  if (wasm !== undefined) return wasm;
  if (module !== undefined && module !== null && Object.getPrototypeOf(module) === Object.prototype) {{
    module = module.module;
  }}
  if (!(module instanceof WebAssembly.Module)) module = new WebAssembly.Module(module);
  return __finalize(new WebAssembly.Instance(module, __imports));
}}

async function __instantiate(input) {{
  if (input !== undefined && input !== null && Object.getPrototypeOf(input) === Object.prototype) {{
    input = input.module_or_path;
  }}
  if (input === undefined) input = new URL({wasm_name}, import.meta.url);
  if (typeof input === "string" || input instanceof URL ||
      (typeof Request === "function" && input instanceof Request)) {{
    input = fetch(input);
  }}
  input = await input;
  if (input instanceof WebAssembly.Module) {{
    return new WebAssembly.Instance(input, __imports);
  }}
  if (typeof Response === "function" && input instanceof Response) {{
    if (typeof WebAssembly.instantiateStreaming === "function" &&
        input.headers.get("Content-Type") === "application/wasm") {{
      return (await WebAssembly.instantiateStreaming(input, __imports)).instance;
    }}
    input = await input.arrayBuffer();
  }}
  return (await WebAssembly.instantiate(input, __imports)).instance;
}}

export default function init(input) {{
  if (wasm !== undefined) return Promise.resolve(wasm);
  return (__pending ??= __instantiate(input).then(__finalize));
}}
"#,
        wasm_name = json_string(&format!("{lib_name}_bg.wasm")),
    );
    js
}

/// Whether a module needs a glue file at all: wasm-bindgen only imports
/// `./__idealyst_glue.js` when some glue import survived linking.
pub fn needs_glue_file(glue: &Glue) -> bool {
    !glue.imports.is_empty() || glue.runtime.is_some()
}

/// `pkg/__idealyst_glue.js` for hybrid mode: the glue namespace as an ES
/// module wasm-bindgen's generated JS imports
/// (`import * as … from "./__idealyst_glue.js"`), where `bindgen_js` is the
/// file name of that generated JS (`<lib>.js`; `wasm-bindgen-test.js` under
/// the test runner).
///
/// wasm-bindgen owns instantiation, so `G` attaches lazily through
/// `initSync()`, which returns the raw exports once the instance exists.
/// The import is circular (`<lib>.js` ⇄ this file); that is safe because
/// `initSync` is a hoisted function declaration and is only called at
/// glue-call time — never while either module is still evaluating.
pub fn hybrid_glue_js(glue: &Glue, bindgen_js: &str) -> String {
    let mut js = String::from(
        "// Generated by the web-glue build pass (hybrid mode). Do not edit.\n",
    );
    let _ = writeln!(js, "import {{ initSync }} from {};", json_string(&format!("./{bindgen_js}")));
    js.push_str(&prelude_js(glue));
    js.push_str("if (G !== null) G.lazyAttach(() => initSync(undefined));\n");
    js.push_str("const __moduleHash = new Map([");
    for m in &glue.modules {
        let _ = write!(js, "[{}, {}], ", json_string(&m.name), source_hash(&m.source));
    }
    js.push_str("]);\n");
    let runtime_hash = glue.runtime.as_deref().map(source_hash).unwrap_or(0);
    let _ = write!(js, "const __runtimeHash = {runtime_hash};\n");
    js.push_str(HYBRID_GLOBAL_JS);
    js.push_str(&snippet_entries(glue, "export const ", " = ", ";"));
    js
}

/// `globalThis.__idealystGlue`. The record framing below is
/// `web_glue::record`'s (magic `IGLU`, version 1, kind, name, source) —
/// the same one [`crate::glue::parse_records`] reads.
const HYBRID_GLOBAL_JS: &str = r#"function __fnv(s) {
  let h = 0x811c9dc5;
  for (const b of new TextEncoder().encode(s)) h = Math.imul(h ^ b, 0x01000193) >>> 0;
  return h >>> 0;
}
globalThis.__idealystGlue = {
  // HYBRID-BRIDGE (`web_glue::bridge`): a wasm-bindgen value into the glue
  // slab, and a glue handle back out. Deleted with the bridge in phase 3.
  add: (v) => G.add(v),
  get: (h) => G.get(h),
  // Hot patch: a patch module's glue import, compiled from the JS its
  // import name carries (`<key>\n<flags>\n<js>`). Dev only — the page's
  // hot-patch loader is the one caller.
  compileImport(name) {
    const a = name.indexOf("\n");
    const b = name.indexOf("\n", a + 1);
    if (a < 0 || b < 0) throw new Error(`web-glue: malformed glue import ${JSON.stringify(name)}`);
    const flags = name.slice(a + 1, b).split(",").filter((f) => f !== "");
    for (const f of flags) if (f !== "catch") throw new Error(`web-glue: unknown glue flag ${f}`);
    const f = new Function("G", `return (${name.slice(b + 1)});`)(G);
    return flags.includes("catch") ? G.catching(f) : f;
  },
  // Hot patch: the `__idealyst_glue` records a patch module carries. A
  // module this page already has must carry the SAME source (a changed
  // module needs a reload: its old factory may already have run); a new
  // module is registered.
  registerRecords(bytes) {
    const u8 = new Uint8Array(bytes);
    const dv = new DataView(u8.buffer, u8.byteOffset, u8.byteLength);
    const dec = new TextDecoder();
    let at = 0;
    while (at < u8.length) {
      if (u8.length - at < 12 || dec.decode(u8.subarray(at, at + 4)) !== "IGLU" || u8[at + 4] !== 1) {
        throw new Error("web-glue: the patch's glue section is not IGLU v1 records");
      }
      const kind = u8[at + 5];
      const nl = dv.getUint16(at + 6, true);
      const sl = dv.getUint32(at + 8, true);
      const name = dec.decode(u8.subarray(at + 12, at + 12 + nl));
      const src = dec.decode(u8.subarray(at + 12 + nl, at + 12 + nl + sl));
      at += 12 + nl + sl;
      const hash = __fnv(src);
      if (kind === 0) {
        if (hash !== __runtimeHash) throw new Error("web-glue: the patch carries a different web-glue runtime — reload");
      } else if (__moduleHash.has(name)) {
        if (__moduleHash.get(name) !== hash) throw new Error(`web-glue: the patch changes JS module "${name}" — reload`);
      } else {
        __moduleHash.set(name, hash);
        G.module(name, new Function("G", src));
      }
    }
  },
};
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::glue::{GlueImport, GlueRecord, KIND_MODULE};

    fn glue() -> Glue {
        Glue {
            wasm: Vec::new(),
            imports: vec![
                GlueImport { short: "g0".into(), key: "a::f(u32)".into(), catch: false, js: "(x) => x".into() },
                GlueImport { short: "g1".into(), key: "a::g()".into(), catch: true, js: "() => { throw 1; }".into() },
            ],
            runtime: Some("return { module() {}, attach() {}, lazyAttach() {}, catching(f) { return f; } };".into()),
            modules: vec![GlueRecord { kind: KIND_MODULE, name: "m\"x".into(), source: "return 1;".into() }],
            foreign_import_modules: vec!["./__wasm_split.js".into()],
            section_bytes: 0,
        }
    }

    #[test]
    fn the_own_loader_keeps_wasm_bindgens_entry_contract() {
        let js = loader_js(&glue(), "my_app");
        assert!(js.contains("export default function init(input)"));
        assert!(js.contains("export function initSync(module)"));
        assert!(js.contains("if (wasm !== undefined) return wasm;"));
        assert!(js.contains("new URL(\"my_app_bg.wasm\", import.meta.url)"));
        assert!(js.contains("import * as __foreign0 from \"./__wasm_split.js\";"));
        assert!(js.contains("G.module(\"m\\\"x\", function (G) {"));
        assert!(js.contains("g0: (\n(x) => x\n),"));
        assert!(js.contains("g1: G.catching(("));
        let attach = js.find("G.attach(wasm)").unwrap();
        let ctors = js.find("wasm.__wasm_call_ctors()").unwrap();
        let main = js.find("wasm.main(0, 0)").unwrap();
        assert!(attach < ctors && ctors < main);
    }

    #[test]
    fn the_hybrid_module_exports_every_snippet_attaches_lazily_and_publishes_the_bridge() {
        let js = hybrid_glue_js(&glue(), "my_app.js");
        assert!(js.contains("import { initSync } from \"./my_app.js\";"));
        assert!(js.contains("G.lazyAttach(() => initSync(undefined));"));
        assert!(js.contains("export const g0 = (\n(x) => x\n);"));
        assert!(js.contains("export const g1 = G.catching(("));
        assert!(js.contains("globalThis.__idealystGlue = {"));
        assert!(js.contains(&format!("[\"m\\\"x\", {}]", source_hash("return 1;"))));
    }

    #[test]
    fn source_hash_is_fnv1a_over_utf8() {
        // Reference values of 32-bit FNV-1a; the JS `__fnv` must agree
        // (checked under node below).
        assert_eq!(source_hash(""), 0x811c_9dc5);
        assert_eq!(source_hash("a"), 0xe40c_292c);
    }

    #[test]
    fn generated_js_parses_and_the_js_hash_agrees_under_node() {
        let Ok(out) = std::process::Command::new("node").arg("--version").output() else { return };
        if !out.status.success() {
            return;
        }
        let dir = std::env::temp_dir().join(format!("glue-js-syntax-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        for (name, js) in [("a.mjs", loader_js(&glue(), "x")), ("b.mjs", hybrid_glue_js(&glue(), "x.js"))] {
            let p = dir.join(name);
            std::fs::write(&p, js).unwrap();
            let st = std::process::Command::new("node").arg("--check").arg(&p).output().unwrap();
            assert!(st.status.success(), "{name}: {}", String::from_utf8_lossy(&st.stderr));
        }
        let src = "é ✓ 🦀 return 1;";
        let fnv = HYBRID_GLOBAL_JS.split("globalThis.__idealystGlue").next().unwrap();
        let probe = format!("{fnv}\nprocess.stdout.write(String(__fnv({})));", json_string(src));
        let out = std::process::Command::new("node").args(["-e", &probe]).output().unwrap();
        assert_eq!(String::from_utf8_lossy(&out.stdout), source_hash(src).to_string());
        let _ = std::fs::remove_dir_all(&dir);
    }
}
