//! `#[macro_export]` invocation macros for every component.
//!
//! These are the macros `ui! { Foo(...) }` lowers to —
//! `framework-macros`' `ui!` emitter takes a component name like
//! `VStack`, lowercases it, and emits `vstack!(...)`. Each macro
//! here constructs the matching `*Props` struct and calls the plain
//! function in `components/*`.
//!
//! Why these are hand-written instead of generated by
//! `#[component]`: that proc macro produces a local-scope
//! `macro_rules!` that's invisible to other crates. `idea-ui` is a
//! library, so its component macros need `#[macro_export]` plus
//! `$crate::` paths in their bodies — which is what's here.
//!
//! Macro shape: each macro accepts `name = expr` pairs. `children`
//! is just another field on every props struct (or absent), so the
//! `ui!` emitter's `children = vec![…]` lowering "just works" — the
//! macro doesn't need a separate children arm.
//!
//! Components with by-ref signatures (`fn name(props: &Props)`) put
//! the `&` inside the macro body. Container components (`fn name(props:
//! Props)`) consume their props by value so they can move `children`
//! out — those omit the `&`.

// =============================================================================
// stack / vstack / hstack — by-value (own their children)
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! stack {
    () => {
        $crate::components::stack::stack(
            <$crate::components::stack::StackProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::stack::stack($crate::components::stack::StackProps {
            $( $field: $value, )+
            ..<$crate::components::stack::StackProps as ::core::default::Default>::default()
        })
    };
}

#[macro_export]
#[doc(hidden)]
macro_rules! vstack {
    () => {
        $crate::components::stack::vstack(
            <$crate::components::stack::VStackProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::stack::vstack($crate::components::stack::VStackProps {
            $( $field: $value, )+
            ..<$crate::components::stack::VStackProps as ::core::default::Default>::default()
        })
    };
}

#[macro_export]
#[doc(hidden)]
macro_rules! hstack {
    () => {
        $crate::components::stack::hstack(
            <$crate::components::stack::HStackProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::stack::hstack($crate::components::stack::HStackProps {
            $( $field: $value, )+
            ..<$crate::components::stack::HStackProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// pressable — by-ref
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! pressable {
    () => {
        $crate::components::pressable::pressable(
            &<$crate::components::pressable::PressableProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::pressable::pressable(&$crate::components::pressable::PressableProps {
            $( $field: $value, )+
            ..<$crate::components::pressable::PressableProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// heading / body / caption — by-ref
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! heading {
    () => {
        $crate::components::heading::heading(
            &<$crate::components::heading::HeadingProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::heading::heading(&$crate::components::heading::HeadingProps {
            $( $field: $value, )+
            ..<$crate::components::heading::HeadingProps as ::core::default::Default>::default()
        })
    };
}

#[macro_export]
#[doc(hidden)]
macro_rules! body {
    () => {
        $crate::components::body::body(
            &<$crate::components::body::BodyProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::body::body(&$crate::components::body::BodyProps {
            $( $field: $value, )+
            ..<$crate::components::body::BodyProps as ::core::default::Default>::default()
        })
    };
}

#[macro_export]
#[doc(hidden)]
macro_rules! caption {
    () => {
        $crate::components::caption::caption(
            &<$crate::components::caption::CaptionProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::caption::caption(&$crate::components::caption::CaptionProps {
            $( $field: $value, )+
            ..<$crate::components::caption::CaptionProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// card — by-value (owns children)
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! card {
    () => {
        $crate::components::card::card(
            <$crate::components::card::CardProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::card::card($crate::components::card::CardProps {
            $( $field: $value, )+
            ..<$crate::components::card::CardProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// field — by-ref
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! field {
    () => {
        $crate::components::field::field(
            &<$crate::components::field::FieldProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::field::field(&$crate::components::field::FieldProps {
            $( $field: $value, )+
            ..<$crate::components::field::FieldProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// switch — by-ref
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! switch {
    () => {
        $crate::components::switch::switch(
            &<$crate::components::switch::SwitchProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::switch::switch(&$crate::components::switch::SwitchProps {
            $( $field: $value, )+
            ..<$crate::components::switch::SwitchProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// spinner / divider / badge — by-ref
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! spinner {
    () => {
        $crate::components::spinner::spinner(
            &<$crate::components::spinner::SpinnerProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::spinner::spinner(&$crate::components::spinner::SpinnerProps {
            $( $field: $value, )+
            ..<$crate::components::spinner::SpinnerProps as ::core::default::Default>::default()
        })
    };
}

#[macro_export]
#[doc(hidden)]
macro_rules! divider {
    () => {
        $crate::components::divider::divider(
            &<$crate::components::divider::DividerProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::divider::divider(&$crate::components::divider::DividerProps {
            $( $field: $value, )+
            ..<$crate::components::divider::DividerProps as ::core::default::Default>::default()
        })
    };
}

#[macro_export]
#[doc(hidden)]
macro_rules! badge {
    () => {
        $crate::components::badge::badge(
            &<$crate::components::badge::BadgeProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::badge::badge(&$crate::components::badge::BadgeProps {
            $( $field: $value, )+
            ..<$crate::components::badge::BadgeProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// spacer / center — layout helpers
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! spacer {
    () => {
        $crate::components::spacer::spacer(
            &<$crate::components::spacer::SpacerProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::spacer::spacer(&$crate::components::spacer::SpacerProps {
            $( $field: $value, )+
            ..<$crate::components::spacer::SpacerProps as ::core::default::Default>::default()
        })
    };
}

#[macro_export]
#[doc(hidden)]
macro_rules! center {
    () => {
        $crate::components::center::center(
            <$crate::components::center::CenterProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::center::center($crate::components::center::CenterProps {
            $( $field: $value, )+
            ..<$crate::components::center::CenterProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// iconbutton — by-ref
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! iconbutton {
    () => {
        $crate::components::icon_button::icon_button(
            &<$crate::components::icon_button::IconButtonProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::icon_button::icon_button(
            &$crate::components::icon_button::IconButtonProps {
                $( $field: $value, )+
                ..<$crate::components::icon_button::IconButtonProps as ::core::default::Default>::default()
            }
        )
    };
}

// =============================================================================
// avatar — by-ref
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! avatar {
    () => {
        $crate::components::avatar::avatar(
            &<$crate::components::avatar::AvatarProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::avatar::avatar(&$crate::components::avatar::AvatarProps {
            $( $field: $value, )+
            ..<$crate::components::avatar::AvatarProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// tag — by-ref
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! tag {
    () => {
        $crate::components::tag::tag(
            &<$crate::components::tag::TagProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::tag::tag(&$crate::components::tag::TagProps {
            $( $field: $value, )+
            ..<$crate::components::tag::TagProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// alert — by-ref
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! alert {
    () => {
        $crate::components::alert::alert(
            &<$crate::components::alert::AlertProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::alert::alert(&$crate::components::alert::AlertProps {
            $( $field: $value, )+
            ..<$crate::components::alert::AlertProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// skeleton — by-ref
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! skeleton {
    () => {
        $crate::components::skeleton::skeleton(
            &<$crate::components::skeleton::SkeletonProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::skeleton::skeleton(&$crate::components::skeleton::SkeletonProps {
            $( $field: $value, )+
            ..<$crate::components::skeleton::SkeletonProps as ::core::default::Default>::default()
        })
    };
}

// =============================================================================
// tabs — by-value (owns the Vec<Tab>)
// =============================================================================

#[macro_export]
#[doc(hidden)]
macro_rules! tabs {
    () => {
        $crate::components::tabs::tabs(
            <$crate::components::tabs::TabsProps as ::core::default::Default>::default(),
        )
    };
    ( $( $field:ident = $value:expr ),+ $(,)? ) => {
        $crate::components::tabs::tabs($crate::components::tabs::TabsProps {
            $( $field: $value, )+
            ..<$crate::components::tabs::TabsProps as ::core::default::Default>::default()
        })
    };
}
