//! Process-wide queue backend configuration + the enqueue entry point.
//!
//! Mirrors `server::configure` / `server::install_state`: an app installs one
//! backend at startup, and every `enqueue` (and, by default, the worker
//! runtime) uses it. Kept in a `OnceLock<RwLock<…>>` so it can be set once and
//! read cheaply from every task.

use crate::{JobId, OutgoingJob, QueueBackend, QueueError};
use std::sync::{Arc, OnceLock, RwLock};

static BACKEND: OnceLock<RwLock<Option<Arc<dyn QueueBackend>>>> = OnceLock::new();

fn slot() -> &'static RwLock<Option<Arc<dyn QueueBackend>>> {
    BACKEND.get_or_init(|| RwLock::new(None))
}

/// Install the process-wide queue backend used by [`enqueue`] and, by default,
/// [`crate::worker`]. Call once at startup (server binary and worker binary
/// both do this). Calling again replaces the backend.
pub fn configure<B: QueueBackend + 'static>(backend: B) {
    *slot().write().unwrap() = Some(Arc::new(backend));
}

/// The configured backend, if [`configure`] has been called.
pub fn configured_backend() -> Option<Arc<dyn QueueBackend>> {
    slot().read().unwrap().clone()
}

/// Enqueue a job onto the configured backend. The typed `Job::enqueue(...)`
/// surface generated by `#[job]` ultimately funnels here.
pub async fn enqueue(job: OutgoingJob) -> Result<JobId, QueueError> {
    let backend = configured_backend().ok_or(QueueError::NotConfigured)?;
    backend.enqueue(job).await
}

/// Configure the backend from the environment, then it's ready for `enqueue` /
/// `worker`. Reads `IDEALYST_JOBS_BACKEND` (`memory` | `redis` | `postgres` |
/// `sqs`, default `memory`) and `IDEALYST_JOBS_URL` (the broker connection
/// string). This is the bridge for `idealyst dev` / `idealyst worker`, which
/// set those vars — a worker `main` just calls this at startup.
///
/// Errors if the selected backend's cargo feature isn't compiled in.
pub async fn configure_from_env() -> Result<(), QueueError> {
    let backend = std::env::var("IDEALYST_JOBS_BACKEND").unwrap_or_else(|_| "memory".to_string());
    let url = std::env::var("IDEALYST_JOBS_URL").ok();
    match backend.as_str() {
        "memory" => configure_memory(),
        "redis" => configure_redis(url).await,
        "postgres" => configure_postgres(url).await,
        "sqs" => configure_sqs(url).await,
        other => Err(QueueError::Backend(format!(
            "unknown IDEALYST_JOBS_BACKEND `{other}` (expected memory|redis|postgres|sqs)"
        ))),
    }
}

fn feature_off(name: &str) -> QueueError {
    QueueError::Backend(format!(
        "jobs backend `{name}` selected via IDEALYST_JOBS_BACKEND, but its cargo feature \
         isn't enabled on the `jobs` dependency"
    ))
}

#[allow(dead_code)] // used only by the enabled persistent-backend arms
fn require_url(url: Option<String>, backend: &str) -> Result<String, QueueError> {
    url.ok_or_else(|| {
        QueueError::Backend(format!("IDEALYST_JOBS_URL is required for the `{backend}` backend"))
    })
}

fn configure_memory() -> Result<(), QueueError> {
    #[cfg(feature = "memory")]
    {
        configure(crate::MemoryBackend::new());
        Ok(())
    }
    #[cfg(not(feature = "memory"))]
    {
        Err(feature_off("memory"))
    }
}

async fn configure_redis(url: Option<String>) -> Result<(), QueueError> {
    #[cfg(feature = "redis")]
    {
        configure(crate::RedisBackend::connect(&require_url(url, "redis")?).await?);
        Ok(())
    }
    #[cfg(not(feature = "redis"))]
    {
        let _ = url;
        Err(feature_off("redis"))
    }
}

async fn configure_postgres(url: Option<String>) -> Result<(), QueueError> {
    #[cfg(feature = "postgres")]
    {
        configure(crate::PostgresBackend::connect(&require_url(url, "postgres")?).await?);
        Ok(())
    }
    #[cfg(not(feature = "postgres"))]
    {
        let _ = url;
        Err(feature_off("postgres"))
    }
}

async fn configure_sqs(url: Option<String>) -> Result<(), QueueError> {
    #[cfg(feature = "sqs")]
    {
        configure(crate::SqsBackend::connect(&require_url(url, "sqs")?).await?);
        Ok(())
    }
    #[cfg(not(feature = "sqs"))]
    {
        let _ = url;
        Err(feature_off("sqs"))
    }
}
