// GENERATED by `idealyst run android`. Single Activity that hands a
// Context + parent ViewGroup to the Rust JNI bridge so the framework
// can mount the shared `app()` tree underneath it.
//
// We use `android.app.Activity` (not AppCompat) because AppCompat
// requires the androidx.appcompat AAR, which would force us to pull
// in Maven/Gradle dependency resolution. Stock Activity is good
// enough for everything `backend-android` exercises.

package {{PACKAGE}};

import android.app.Activity;
import android.content.Intent;
import android.content.res.Configuration;
import android.graphics.Color;
import android.net.Uri;
import android.os.Bundle;
import android.util.Log;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;

public class MainActivity extends Activity {
    static {
        // Loading the cdylib fires its JNI_OnLoad, which caches the
        // JavaVM so the backend can attach threads on demand.
        System.loadLibrary("{{LIB_NAME}}");
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Match the status bar to the in-tree Toolbar's white
        // background so the two read as a single header. Dark
        // status-bar icons (battery/clock/signal) for legibility on
        // the light background.
        getWindow().setStatusBarColor(Color.WHITE);
        getWindow().getDecorView().setSystemUiVisibility(
            getWindow().getDecorView().getSystemUiVisibility()
                | View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);

        // Cold-start deep link. If the Activity was launched via an
        // ACTION_VIEW intent (custom scheme or Android App Link), hand
        // the URI's PATH to the framework BEFORE `attach` so the
        // navigator walker resolves the deep-linked screen on its
        // synchronous initial mount. No VIEW intent ⇒ skipped, behavior
        // unchanged.
        Intent launchIntent = getIntent();
        if (launchIntent != null && Intent.ACTION_VIEW.equals(launchIntent.getAction())) {
            Uri data = launchIntent.getData();
            if (data != null) {
                String path = data.getPath();
                if (path == null || path.isEmpty()) {
                    path = "/";
                }
                String query = data.getEncodedQuery();
                if (query != null && !query.isEmpty()) {
                    path += "?" + query;
                }
                NativeBridge.setLaunchPath(path);
            }
        }

        FrameLayout root = new FrameLayout(this);
        root.setLayoutParams(new ViewGroup.LayoutParams(
            ViewGroup.LayoutParams.MATCH_PARENT,
            ViewGroup.LayoutParams.MATCH_PARENT));
        setContentView(root);
        NativeBridge.attach(this, root);
    }

    /**
     * Vestigial: with the NoActionBar theme the system ActionBar
     * never dispatches here. Kept so the legacy
     * `RustActionBarHelper.dispatchHomePress` path compiles; new
     * screen-level toolbars are built inline in
     * `tab_drawer::attach_initial`.
     */
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        if (item.getItemId() == android.R.id.home
            && io.idealyst.runtime.RustActionBarHelper.dispatchHomePress()) {
            return true;
        }
        return super.onOptionsItemSelected(item);
    }

    /**
     * Fired when the device rotates, multi-window resizes, the
     * keyboard shows/hides, dark mode toggles, density changes, etc.
     * — any of the axes listed under `configChanges` in the manifest.
     * Because of that manifest declaration the Activity is *not*
     * recreated, so we just nudge the framework to re-run its layout
     * pass against the host root's new dimensions. The framework
     * already has a retry loop that waits for the host to be measured
     * before applying frames, so a single notify is enough.
     */
    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        NativeBridge.notifyConfigChanged();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        NativeBridge.detach();
    }
}
