// GENERATED by `idealyst run android` in runtime-server mode. Single Activity
// that reads the dev-server URL from the manifest's <meta-data>
// `IdealystRuntimeServerUrl` (baked in by the CLI), hands a Context
// + parent ViewGroup to the Rust runtime-server shell, and runs a
// Handler tick loop calling drainRuntimeServer() on the UI thread.

package {{PACKAGE}};

// FragmentActivity (not AppCompat) — required by the navigator runtime; see the
// local-mode template + the `-jvm` androidx relocation fix in kotlin_runtime.rs.
import androidx.fragment.app.FragmentActivity;
import android.content.pm.ApplicationInfo;
import android.content.pm.PackageManager;
import android.content.res.Configuration;
import android.os.Bundle;
import android.os.Handler;
import android.graphics.Color;
import android.os.Looper;
import android.util.Log;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;

public class MainActivity extends FragmentActivity {
    static {
        // Loading the cdylib fires JNI_OnLoad, which caches the
        // JavaVM so the runtime-server worker thread can attach on demand.
        System.loadLibrary("{{LIB_NAME}}");
    }

    private Handler drainHandler;
    private Runnable drainTick;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Match the status bar to the in-tree Toolbar's white
        // background so the two read as a single header. The
        // `SYSTEM_UI_FLAG_LIGHT_STATUS_BAR` flag switches the
        // status-bar icons (battery / signal / clock) to dark so
        // they remain legible on the now-light background.
        getWindow().setStatusBarColor(Color.WHITE);
        getWindow().getDecorView().setSystemUiVisibility(
            getWindow().getDecorView().getSystemUiVisibility()
                | View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR);

        final FrameLayout root = new FrameLayout(this);
        root.setLayoutParams(new ViewGroup.LayoutParams(
            ViewGroup.LayoutParams.MATCH_PARENT,
            ViewGroup.LayoutParams.MATCH_PARENT));
        setContentView(root);

        // Report the root view's size to the sidecar whenever it
        // changes. The Rust side dedupes redundant calls, so it's
        // safe to fire on every layout pass.
        //
        // This is the only path the sidecar has to learn the real
        // canvas size on Android. `View.getWidth()` is zero in
        // `onCreate` (no layout pass has run yet), so the initial
        // Hello ships `viewport=None` and the sidecar's
        // `RecordingViewOps::frame()` falls back to its hardcoded
        // 393×800 mobile-portrait default. Welcome's planet orbit
        // math (and any other `page_ref.frame()` reader) would
        // then compute against the wrong canvas — visible as
        // text at the top of the screen instead of vertically
        // centered, missing planets, missing sun, etc. The first
        // OnLayoutChangeListener callback (immediately after
        // onCreate returns) lands the real dimensions; subsequent
        // calls catch rotations + multi-window resizes.
        final float density = getResources().getDisplayMetrics().density;
        root.addOnLayoutChangeListener(new View.OnLayoutChangeListener() {
            @Override
            public void onLayoutChange(View v, int l, int t, int r, int b,
                                       int ol, int ot, int or_, int ob) {
                int width = r - l;
                int height = b - t;
                if (width > 0 && height > 0) {
                    NativeBridge.reportViewport(width, height, density);
                }
            }
        });

        // CLI always bakes the dev-server URL into the manifest at
        // `idealyst dev` time. If it's missing, abort loudly — there's
        // no fallback discovery path any more.
        String url = readMetaString("IdealystRuntimeServerUrl");
        if (url == null || url.isEmpty()) {
            throw new RuntimeException(
                "IdealystRuntimeServerUrl not set in manifest — this APK was not built via " +
                "`idealyst dev`. Rebuild via `idealyst dev` to bake the dev-server URL.");
        }
        NativeBridge.attachRuntimeServerUrl(this, root, url);

        // Periodic UI-thread drain. 16ms ≈ 60Hz matches Android's
        // typical vsync. Cheap when the channel is empty — the
        // Rust side's try_recv returns immediately.
        drainHandler = new Handler(Looper.getMainLooper());
        drainTick = new Runnable() {
            @Override
            public void run() {
                NativeBridge.drainRuntimeServer();
                drainHandler.postDelayed(this, 16);
            }
        };
        drainHandler.post(drainTick);
    }

    /**
     * Dispatch ActionBar home-button presses ("hamburger" / "back")
     * to the Rust side. {@link io.idealyst.runtime.RustActionBarHelper}
     * keeps a pointer to the currently-installed callback; if one is
     * present, this consumes the event so the Activity doesn't also
     * pop the back stack.
     */
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Vestigial: the activity now uses a NoActionBar theme, so the
        // system ActionBar never dispatches here. Kept so the
        // RustActionBarHelper hook continues to compile against the
        // legacy path; new screen-level toolbars are built inline by
        // `tab_drawer::attach_initial`.
        if (item.getItemId() == android.R.id.home
            && io.idealyst.runtime.RustActionBarHelper.dispatchHomePress()) {
            return true;
        }
        return super.onOptionsItemSelected(item);
    }

    /**
     * Fired when the device rotates, multi-window resizes, the
     * keyboard shows/hides, dark mode toggles, density changes, etc.
     * — any of the axes listed under `configChanges` in the manifest.
     * Because of that manifest declaration the Activity is *not*
     * recreated, so we just nudge the framework to re-run its layout
     * pass against the host root's new dimensions.
     */
    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        NativeBridge.notifyConfigChanged();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        if (drainHandler != null && drainTick != null) {
            drainHandler.removeCallbacks(drainTick);
        }
        NativeBridge.detach();
    }

    /// Generic getter for a string `<meta-data>` entry in the
    /// manifest's <application>. Returns null for missing/blank.
    private String readMetaString(String key) {
        try {
            ApplicationInfo info = getPackageManager()
                .getApplicationInfo(getPackageName(), PackageManager.GET_META_DATA);
            if (info.metaData != null) {
                String v = info.metaData.getString(key);
                if (v != null && !v.isEmpty()) return v;
            }
        } catch (PackageManager.NameNotFoundException ignored) {
            // Fall through.
        }
        return null;
    }
}
