// GENERATED by `idealyst run android`. Thin facade in front of the
// Rust JNI entry points. Keeps the `native` declarations off the
// Activity itself so MainActivity reads as pure UIKit-ish code.

package {{PACKAGE}};

import android.content.Context;
import android.view.ViewGroup;

public class NativeBridge {
    public static native void attach(Context context, ViewGroup root);
    public static native void detach();

    /// Called from `MainActivity.onConfigurationChanged` (rotation,
    /// multi-window resize, dark-mode toggle, density change, etc.).
    /// Triggers a framework layout pass against the host root's new
    /// dimensions. The host FrameLayout is `MATCH_PARENT` so Android
    /// has already resized it by the time this fires; the framework
    /// just needs to re-run Taffy and reapply the resulting frames.
    public static native void notifyConfigChanged();

    /// Cold-start inbound link: record the launch URL and seed the
    /// navigators' launch path from the launch Intent's full data URI.
    /// Call from `MainActivity.onCreate` BEFORE `attach`.
    public static native void setLaunchUrl(String url);

    /// A link arrived while running (`onNewIntent`): route it through the
    /// live navigators. Full data URI.
    public static native void deliverLink(String url);

    /// Robot bridge: export the relay URL (baked into the manifest meta-data
    /// by `idealyst dev`) so the app DIALS the host relay instead of
    /// self-hosting an on-device TCP bridge. Call BEFORE `attach`. Only
    /// resolved in dev builds; MainActivity guards on the meta-data presence.
    public static native void setRobotRelayUrl(String url);
}
