// GENERATED by `idealyst run android` in runtime-server mode. Thin facade over
// the Rust JNI entry points. Matches the symbol names emitted by
// the generated runtime-server wrapper cdylib (`Java_<pkg>_NativeBridge_*`).

package {{PACKAGE}};

import android.content.Context;
import android.view.ViewGroup;

public class NativeBridge {
    /// Stand up the runtime-server client against the dev-server URL the
    /// CLI baked into the manifest's `IdealystRuntimeServerUrl` meta-data
    /// entry. The Activity reads that value from the manifest and passes
    /// it here. mDNS / Bonjour is no longer used.
    public static native void attachRuntimeServerUrl(Context context, ViewGroup root, String url);

    /// Drain the worker's pending messages and apply them through
    /// the RuntimeServerClient<AndroidBackend>. Call from a UI-thread tick.
    public static native void drainRuntimeServer();

    /// Report the host root view's current size to the sidecar. The
    /// runtime-server shell forwards an `AppToDev::ViewportChanged` only when
    /// the value actually differs from the last report (cheap when
    /// nothing changed). Called from the layout-change listener in
    /// MainActivityAas so the sidecar's viewport-relative math
    /// (welcome's planet orbit, page layout, etc.) tracks rotations,
    /// multi-window resizes, and the initial post-attach layout
    /// pass that's needed because `View.getWidth()` is zero in
    /// `onCreate`.
    public static native void reportViewport(int widthPx, int heightPx, float density);

    /// Tear down the runtime-server client. Stops the drain channel; the
    /// worker thread exits on its next send attempt.
    public static native void detach();

    /// Called from `MainActivity.onConfigurationChanged` (rotation,
    /// multi-window resize, dark-mode toggle, density change, etc.).
    /// Triggers a framework layout pass against the host root's new
    /// dimensions on the runtime-server side's locally-mounted view tree.
    public static native void notifyConfigChanged();
}
