//! # `graphql` — typed GraphQL client + server execution
//!
//! Full GraphQL for the framework, built on the established Rust ecosystem
//! rather than a bespoke engine:
//!
//! - **Client typing** — `graphql_client` codegen. Author `.graphql`
//!   operation files against the schema and derive typed `Variables` /
//!   `ResponseData` with `#[derive(GraphQLQuery)]`.
//! - **Server** — `async-graphql` (behind the [`server`](#features) feature)
//!   for schema definition, validation, execution, introspection, and SDL.
//!
//! ## Decoupled from server functions — works *with* them, doesn't *rely*
//! on them
//!
//! The client is written against one trait, [`Transport`], and nothing
//! else. The crate has **no dependency on the `server` (server-functions)
//! SDK** — exactly like `sync`. Two ways to wire it up:
//!
//! 1. **On the server-functions stack** — the app writes one `#[server]`
//!    fn and bridges it with [`graphql_transport!`]. GraphQL then rides the
//!    server-functions HTTP path and reuses its auth, CSRF, credentials, and
//!    per-platform client configuration:
//!    ```ignore
//!    // shared (both builds):
//!    graphql::graphql_transport!(AppGraphql, graphql_endpoint);
//!    let client = graphql::GraphqlClient::new(std::rc::Rc::new(AppGraphql));
//!
//!    // server build only:
//!    #[server]
//!    pub async fn graphql_endpoint(req: graphql::GraphqlRequest, schema: State<MySchema>)
//!        -> Result<graphql::GraphqlResponse, ServerError> {
//!        Ok(graphql::execute_request(&schema, req).await)
//!    }
//!    ```
//! 2. **Off it** — point [`HttpTransport`] at any GraphQL endpoint, and on
//!    the server run [`execute_request`](server::execute_request) from any
//!    handler:
//!    ```ignore
//!    let client = graphql::GraphqlClient::http("https://api.example.com/graphql");
//!    ```
//!
//! ## Reactive use
//!
//! [`use_query`] and [`use_mutation`] bind operations to the reactive
//! runtime (they wrap `runtime_core`'s `resource` / `mutation`), so a
//! component re-renders as results arrive.
//!
//! ## Scope (v1)
//!
//! Queries + mutations, end to end. Subscriptions are a documented
//! extension seam — `async-graphql` already supports `execute_stream`; a
//! `SubscriptionTransport` over a WebSocket (the `net` SDK, or a
//! server-functions `#[channel]`) layers on without reworking the above.

#![deny(missing_docs)]

mod client;
mod hooks;
mod request;
mod transport;

pub use client::GraphqlClient;
pub use hooks::{use_mutation, use_query};
pub use request::{GqlError, GqlLocation, GraphqlError, GraphqlRequest, GraphqlResponse};
pub use transport::{HttpTransport, Transport, TransportFuture};

/// Re-export so the `graphql_client::GraphQLQuery` derive and trait are
/// reachable without the app adding a direct dependency.
pub use graphql_client;

#[cfg(feature = "server")]
pub mod server;
#[cfg(feature = "server")]
pub use server::{async_graphql, execute_request, execute_request_with, sdl, Schema};

/// Generate a [`Transport`] that bridges an app-authored server function
/// into the GraphQL client — the "works with server functions, without
/// depending on them" seam.
///
/// The app writes one `#[server] async fn(GraphqlRequest) -> Result<GraphqlResponse, E>`
/// (any `E: Display`, e.g. `ServerError`) and this macro removes the
/// boilerplate of adapting it to [`Transport`], mapping the server-fn error
/// to [`GraphqlError::Transport`]. The direct analogue of `sync`'s
/// `sync_transport!`.
///
/// ```ignore
/// // The app's server fn (server build runs the body; client build is a stub):
/// #[server]
/// pub async fn graphql_endpoint(req: graphql::GraphqlRequest)
///     -> Result<graphql::GraphqlResponse, ServerError> { /* execute_request */ }
///
/// // One line wires it into a client transport on both builds:
/// graphql::graphql_transport!(AppGraphql, graphql_endpoint);
/// let client = graphql::GraphqlClient::new(std::rc::Rc::new(AppGraphql));
/// ```
#[macro_export]
macro_rules! graphql_transport {
    ($transport:ident, $endpoint:path $(,)?) => {
        /// Server-function-backed GraphQL transport generated by
        /// [`graphql::graphql_transport!`].
        pub struct $transport;

        impl $crate::Transport for $transport {
            fn execute(
                &self,
                request: $crate::GraphqlRequest,
            ) -> $crate::TransportFuture<'_, $crate::GraphqlResponse> {
                ::std::boxed::Box::pin(async move {
                    $endpoint(request).await.map_err(|e| {
                        $crate::GraphqlError::Transport(::std::string::ToString::to_string(&e))
                    })
                })
            }
        }
    };
}
