import { useState } from "react";
// Typed wrappers generated by `idealyst export` (resolved from the
// `external-export-suite-components` file: dependency).
import { Greeter } from "external-export-suite-components/react/Greeter";
import { Stepper } from "external-export-suite-components/react/Stepper";

export function App() {
  const [greets, setGreets] = useState(0);
  const [value, setValue] = useState(0); // host owns the stepper's value

  return (
    <main style={{ fontFamily: "system-ui, sans-serif", margin: "2rem", maxWidth: "40rem" }}>
      <h1>React 19 consumer</h1>

      <section>
        <h2>&lt;Greeter&gt;</h2>
        <Greeter name="World" onGreet={() => setGreets((n) => n + 1)} />
        <p>greet events: <strong>{greets}</strong></p>
      </section>

      <section>
        <h2>&lt;Stepper&gt; (controlled)</h2>
        {/* onStep asks for the next value; we own + set it back. */}
        <Stepper label="Count" value={value} onStep={(next) => setValue(next)} />
        <p>value: <strong>{value}</strong></p>
      </section>
    </main>
  );
}
