// GENERATED by `idealyst run ios --aas`. Identical for every idealyst app —
// stands up a UIWindow + ViewController. Runtime-server mode renders a tree
// streamed from the dev server, so inbound links are not forwarded here:
// the shell has no local navigators to route them through.

import UIKit

@main
class AppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?

    func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {
        let window = UIWindow(frame: UIScreen.main.bounds)
        let vc = ViewController()
        window.rootViewController = vc
        window.makeKeyAndVisible()
        self.window = window
        return true
    }
}
