// GENERATED by `idealyst run ios`. Identical for every idealyst app —
// nothing project-specific. Stands up a UIWindow + ViewController and
// forwards inbound links (custom-scheme deep links, universal links) to
// the framework.

import UIKit

@main
class AppDelegate: UIResponder, UIApplicationDelegate {
    var window: UIWindow?

    /// The URL that launched the app, until UIKit re-delivers it. A link
    /// that launches the app arrives TWICE: in `launchOptions` here, and
    /// again through `application(_:open:options:)` /
    /// `application(_:continue:restorationHandler:)` right after launch.
    /// The first copy already opened its screen on the initial mount, so
    /// the re-delivery is swallowed once — otherwise `on_link` observers
    /// would see the launch link as a second, warm link.
    private var launchURL: URL?

    func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {
        // Cold-start link. Hand it to the framework BEFORE the
        // ViewController mounts (its `viewDidLoad` calls `ios_main`): the
        // navigators read the launch path on their synchronous initial
        // mount and open the linked screen. No launch URL ⇒ skipped.
        if let url = launchOptions?[.url] as? URL {
            launch(url)
        } else if
            let activityDict = launchOptions?[.userActivityDictionary] as? [AnyHashable: Any],
            let activity = activityDict.values.compactMap({ $0 as? NSUserActivity }).first,
            activity.activityType == NSUserActivityTypeBrowsingWeb,
            let webURL = activity.webpageURL
        {
            launch(webURL)
        }

        let window = UIWindow(frame: UIScreen.main.bounds)
        let vc = ViewController()
        window.rootViewController = vc
        window.makeKeyAndVisible()
        self.window = window
        return true
    }

    /// Custom-scheme link (`myapp://…`) while running.
    func application(
        _ app: UIApplication,
        open url: URL,
        options: [UIApplication.OpenURLOptionsKey: Any] = [:]
    ) -> Bool {
        deliver(url)
        return true
    }

    /// Universal link (`https://your.domain/…`) while running.
    func application(
        _ application: UIApplication,
        continue userActivity: NSUserActivity,
        restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void
    ) -> Bool {
        guard userActivity.activityType == NSUserActivityTypeBrowsingWeb,
              let url = userActivity.webpageURL
        else { return false }
        deliver(url)
        return true
    }

    private func launch(_ url: URL) {
        launchURL = url
        url.absoluteString.withCString { ios_launch_url($0) }
    }

    private func deliver(_ url: URL) {
        if let launched = launchURL, launched == url {
            launchURL = nil
            return
        }
        launchURL = nil
        url.absoluteString.withCString { ios_open_url($0) }
    }
}
