// GENERATED by `idealyst run ios`. Exposes the Rust C-exported
// symbols to Swift. The wrapper crate guarantees both functions are
// always present in the linked staticlib.

void ios_main(void *root_view);
void ios_teardown(void);
// Cold-start deep link: seed the navigator's initial path from a launch
// URL. Call BEFORE `ios_main`. `path` is the URL's path component
// (e.g. "/encounters/abc"), NUL-terminated UTF-8, or null for none.
void ios_set_launch_path(const char *path);
