// GENERATED by `idealyst run ios`. Splash values are substituted
// from `[package.metadata.idealyst.app.splash]` at build time.
// Set `duration_ms = 0` in TOML to skip the splash entirely.

import UIKit

class ViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()

        let splashDurationMs: Int = {{SPLASH_DURATION_MS}}
        if splashDurationMs == 0 {
            view.backgroundColor = .white
            mountFramework()
        } else {
            showSplashThenMount(durationMs: splashDurationMs)
        }
    }

    deinit {
        ios_teardown()
    }

    private func mountFramework() {
        let rawPtr = Unmanaged.passUnretained(view).toOpaque()
        ios_main(rawPtr)
    }

    private func showSplashThenMount(durationMs: Int) {
        view.backgroundColor = UIColor(hexString: "{{SPLASH_BG}}")

        let title = UILabel()
        title.text = "{{SPLASH_TITLE}}"
        title.textAlignment = .center
        title.textColor = UIColor(hexString: "{{SPLASH_TITLE_COLOR}}")
        title.font = .systemFont(ofSize: 36, weight: .bold)
        title.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(title)
        NSLayoutConstraint.activate([
            title.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            title.centerYAnchor.constraint(equalTo: view.centerYAnchor),
            title.leadingAnchor.constraint(greaterThanOrEqualTo: view.leadingAnchor, constant: 24),
            title.trailingAnchor.constraint(lessThanOrEqualTo: view.trailingAnchor, constant: -24),
        ])

        let delay = TimeInterval(durationMs) / 1000.0
        DispatchQueue.main.asyncAfter(deadline: .now() + delay) { [weak self] in
            guard let self = self else { return }
            UIView.animate(withDuration: 0.25, animations: {
                title.alpha = 0
                self.view.backgroundColor = .white
            }, completion: { _ in
                title.removeFromSuperview()
                self.mountFramework()
            })
        }
    }
}

private extension UIColor {
    /// Parse "#RRGGBB" or "RRGGBB" into a UIColor. Falls back to
    /// magenta on parse errors so problems are visually obvious.
    convenience init(hexString: String) {
        let trimmed = hexString
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .replacingOccurrences(of: "#", with: "")
        var rgb: UInt64 = 0
        guard Scanner(string: trimmed).scanHexInt64(&rgb), trimmed.count == 6 else {
            self.init(red: 1, green: 0, blue: 1, alpha: 1)
            return
        }
        let r = CGFloat((rgb & 0xFF0000) >> 16) / 255
        let g = CGFloat((rgb & 0x00FF00) >> 8) / 255
        let b = CGFloat(rgb & 0x0000FF) / 255
        self.init(red: r, green: g, blue: b, alpha: 1.0)
    }
}
