//! Code generation: the typed `Locale` enum + one function per message.
//!
//! Generated code references the `i18n` crate as `::i18n` (the runtime
//! half re-exports everything the output needs, including `Reactive`), so
//! a call site only needs `i18n` in scope.

use crate::parse::{I18nInput, Message};
use crate::validate::Model;
use proc_macro2::TokenStream;
use quote::quote;

pub fn emit(input: &I18nInput, model: &Model) -> TokenStream {
    let locale_enum = emit_locale_enum(input, model);
    let message_fns = input.messages.iter().map(|m| emit_message_fn(input, model, m));
    quote! {
        #locale_enum
        #( #message_fns )*
    }
}

fn emit_locale_enum(input: &I18nInput, model: &Model) -> TokenStream {
    let variants: Vec<_> = input.locales.iter().map(|l| &l.variant).collect();
    let codes: Vec<String> = input.locales.iter().map(|l| l.code.value()).collect();
    let bundled_variants: Vec<_> =
        input.locales.iter().filter(|l| !l.is_lazy).map(|l| &l.variant).collect();
    let lazy_flags: Vec<bool> = input.locales.iter().map(|l| l.is_lazy).collect();
    let default_variant = &input.locales[model.default_idx].variant;

    let code_arms = variants.iter().zip(&codes).map(|(v, c)| quote! { Locale::#v => #c });
    let from_code_arms = variants
        .iter()
        .zip(&codes)
        .map(|(v, c)| quote! { #c => ::std::option::Option::Some(Locale::#v) });
    let is_lazy_arms =
        variants.iter().zip(&lazy_flags).map(|(v, lz)| quote! { Locale::#v => #lz });

    quote! {
        /// Every declared locale. Generated by `i18n!`.
        #[derive(
            ::std::clone::Clone, ::std::marker::Copy, ::std::fmt::Debug,
            ::std::cmp::PartialEq, ::std::cmp::Eq, ::std::hash::Hash
        )]
        #[allow(non_camel_case_types)]
        pub enum Locale {
            #( #variants ),*
        }

        #[allow(dead_code)]
        impl Locale {
            /// Every declared locale, in declaration order.
            pub const ALL: &'static [Locale] = &[ #( Locale::#variants ),* ];
            /// The bundled (non-`lazy`) locales — strings compiled into the binary.
            pub const BUNDLED: &'static [Locale] = &[ #( Locale::#bundled_variants ),* ];
            /// The reference + fallback locale.
            pub const DEFAULT: Locale = Locale::#default_variant;

            /// This locale's code string (e.g. `"en"`).
            pub fn code(self) -> &'static str {
                match self { #( #code_arms ),* }
            }

            /// Parse a locale from its code string, or `None` if unknown.
            pub fn from_code(code: &str) -> ::std::option::Option<Locale> {
                match code {
                    #( #from_code_arms ),*,
                    _ => ::std::option::Option::None,
                }
            }

            /// Whether this is an opt-in (`lazy`) locale whose strings load at runtime.
            pub fn is_lazy(self) -> bool {
                match self { #( #is_lazy_arms ),* }
            }
        }

        /// Switch the active locale. For a `lazy` locale this also kicks off
        /// loading its opt-in pack (a no-op if already loaded or in flight).
        #[allow(dead_code)]
        pub fn set_locale(locale: Locale) {
            ::i18n::set_locale_code(locale.code());
            if locale.is_lazy() {
                ::i18n::ensure_pack_loaded(locale.code());
            }
        }

        /// The active locale, falling back to `DEFAULT` for an unknown code.
        #[allow(dead_code)]
        pub fn current_locale() -> Locale {
            Locale::from_code(&::i18n::current_locale_code()).unwrap_or(Locale::DEFAULT)
        }

        /// Seed the active locale to `DEFAULT`. Call once at app startup.
        #[allow(dead_code)]
        pub fn init() {
            ::i18n::set_locale_code(Locale::DEFAULT.code());
        }
    }
}

fn emit_message_fn(input: &I18nInput, model: &Model, msg: &Message) -> TokenStream {
    let name = &msg.name;
    let msg_key = name.to_string();

    let params = msg.args.iter().map(|a| quote! { #a: impl ::std::fmt::Display });
    let bindings = msg.args.iter().map(|a| quote! { let #a = #a.to_string(); });
    let arg_entries = msg.args.iter().map(|a| {
        let s = a.to_string();
        quote! { (#s, &#a as &dyn ::std::fmt::Display) }
    });

    // One match arm per bundled locale (validation guarantees each has an entry).
    let bundled_arms = input.locales.iter().filter(|l| !l.is_lazy).map(|loc| {
        let code = loc.code.value();
        let entry = msg
            .entries
            .iter()
            .find(|e| e.variant == loc.variant)
            .expect("validation guarantees a bundled translation exists");
        let template = &entry.template;
        quote! { #code => ::std::borrow::Cow::Borrowed(#template) }
    });

    // Fallback when the active code is opt-in and its pack hasn't arrived:
    // the default locale's string.
    let default_variant = &input.locales[model.default_idx].variant;
    let default_template = &msg
        .entries
        .iter()
        .find(|e| &e.variant == default_variant)
        .expect("validation guarantees the default translation exists")
        .template;

    quote! {
        #[allow(dead_code)]
        pub fn #name( #( #params ),* ) -> ::i18n::Reactive<String> {
            #( #bindings )*
            ::i18n::Reactive::derive(move || {
                let __code = ::i18n::current_locale_code();
                let __tmpl: ::std::borrow::Cow<'static, str> = match &*__code {
                    #( #bundled_arms , )*
                    __other => match ::i18n::opt_in_template(#msg_key, __other) {
                        ::std::option::Option::Some(__s) => ::std::borrow::Cow::Owned(__s),
                        ::std::option::Option::None => ::std::borrow::Cow::Borrowed(#default_template),
                    },
                };
                ::i18n::format(&__tmpl, &[ #( #arg_entries ),* ])
            })
        }
    }
}
