//! Regression (CrewForge build-dir report, 2026-10-08): `backend-ios-mobile`
//! declared `crate-type = ["staticlib", "rlib"]`, so every build depending
//! on it archived the whole dependency graph into a `libbackend_ios-<hash>.a`
//! nothing links — 255–290 MB per variant in a wrapper target, 192 MB in a
//! simulator RS-shell build. The only staticlibs an iOS app links are the
//! per-app wrapper's (generated by build-ios) and the runtime-server shell's.
//! This pins the manifests so the extra archive can't come back unnoticed.

use std::path::Path;

fn lib_table(rel: &str) -> toml::Table {
    let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../..");
    let text = std::fs::read_to_string(root.join(rel).join("Cargo.toml")).unwrap();
    let manifest: toml::Table = text.parse().unwrap();
    manifest["lib"].as_table().unwrap().clone()
}

fn crate_types(lib: &toml::Table) -> Vec<String> {
    lib["crate-type"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect()
}

#[test]
fn regression_backend_ios_builds_an_unused_staticlib() {
    for rel in ["crates/backend/ios/mobile", "crates/backend/ios/tv"] {
        assert_eq!(crate_types(&lib_table(rel)), ["rlib"], "{rel} must not build a staticlib");
    }
}

/// The runtime-server shell IS linked by Swift (`-lbackend_ios`), so it
/// keeps both the staticlib and that lib name.
#[test]
fn the_runtime_server_shell_still_builds_libbackend_ios() {
    let lib = lib_table("crates/backend/ios/rs-shell");
    assert!(crate_types(&lib).contains(&"staticlib".to_string()));
    assert_eq!(lib["name"].as_str(), Some("backend_ios"));
}
