//! Build script that generates `pub const IconData` items from SVG files
//! in the `assets/` directory.
//!
//! Each `.svg` file becomes one `pub const FILENAME: IconData = ...;` in
//! the generated output. The SVG parser is intentionally minimal — it
//! extracts `viewBox` and `<path d="...">` attributes and nothing else.
//! This keeps build deps at zero (no XML crate needed).

use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("icons_generated.rs");
    let assets_dir = Path::new("assets");

    println!("cargo:rerun-if-changed=assets");

    let mut output = String::new();
    output.push_str("// Auto-generated by build.rs — do not edit.\n");
    output.push_str("use runtime_core::{IconData, FillRule};\n\n");

    if !assets_dir.exists() {
        // No assets yet — generate an empty file.
        fs::write(&dest, &output).unwrap();
        return;
    }

    let mut entries: Vec<_> = fs::read_dir(assets_dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().map_or(false, |ext| ext == "svg"))
        .collect();
    entries.sort_by_key(|e| e.file_name());

    for entry in entries {
        let path = entry.path();
        let stem = path.file_stem().unwrap().to_str().unwrap();
        let const_name = to_screaming_snake(stem);
        let svg_content = fs::read_to_string(&path).unwrap();

        let view_box = extract_view_box(&svg_content).unwrap_or((24, 24));
        let paths = extract_paths(&svg_content);
        let fill_rule = if svg_content.contains("evenodd") {
            "FillRule::EvenOdd"
        } else {
            "FillRule::NonZero"
        };

        output.push_str(&format!(
            "pub const {}: IconData = IconData {{\n    view_box: ({}, {}),\n    paths: &[",
            const_name, view_box.0, view_box.1
        ));
        for (i, p) in paths.iter().enumerate() {
            if i > 0 {
                output.push_str(", ");
            }
            // Escape any quotes in path data (shouldn't happen, but safe).
            let escaped = p.replace('\\', "\\\\").replace('"', "\\\"");
            output.push_str(&format!("\"{}\"", escaped));
        }
        output.push_str(&format!(
            "],\n    fill_rule: {},\n}};\n\n",
            fill_rule
        ));
    }

    let mut file = fs::File::create(&dest).unwrap();
    file.write_all(output.as_bytes()).unwrap();
}

/// Convert kebab-case or snake_case icon name to SCREAMING_SNAKE_CASE.
fn to_screaming_snake(s: &str) -> String {
    let mut result = String::with_capacity(s.len());
    for ch in s.chars() {
        if ch == '-' || ch == ' ' {
            result.push('_');
        } else {
            result.push(ch.to_ascii_uppercase());
        }
    }
    // Rust identifiers can't start with a digit.
    if result.starts_with(|c: char| c.is_ascii_digit()) {
        result.insert(0, '_');
    }
    result
}

/// Extract viewBox="x y w h" → (w, h). Minimal parser.
fn extract_view_box(svg: &str) -> Option<(u16, u16)> {
    let vb_start = svg.find("viewBox=\"")? + "viewBox=\"".len();
    let vb_end = svg[vb_start..].find('"')? + vb_start;
    let vb = &svg[vb_start..vb_end];
    let parts: Vec<&str> = vb.split_whitespace().collect();
    if parts.len() == 4 {
        let w: u16 = parts[2].parse().ok()?;
        let h: u16 = parts[3].parse().ok()?;
        Some((w, h))
    } else {
        None
    }
}

/// Extract all `<path d="...">` attribute values.
fn extract_paths(svg: &str) -> Vec<String> {
    let mut paths = Vec::new();
    let mut search_from = 0;
    while let Some(pos) = svg[search_from..].find("<path") {
        let abs_pos = search_from + pos;
        // Find the d="..." attribute within this <path> tag.
        let tag_end = svg[abs_pos..].find('>').unwrap_or(svg.len() - abs_pos) + abs_pos;
        let tag = &svg[abs_pos..tag_end];

        if let Some(d_start) = tag.find(" d=\"") {
            let d_val_start = d_start + " d=\"".len();
            if let Some(d_end) = tag[d_val_start..].find('"') {
                paths.push(tag[d_val_start..d_val_start + d_end].to_string());
            }
        }
        search_from = tag_end;
    }
    paths
}
