//! Build script that generates `pub const IconData` items from SVG files
//! in the `assets/` directory.
//!
//! Each `.svg` file becomes one `pub const FILENAME: IconData = ...;` in the
//! generated output. The SVG parser is intentionally minimal — it extracts
//! `viewBox` plus every drawable element (`path`, `circle`, `ellipse`,
//! `line`, `polyline`, `polygon`, `rect`) and normalizes them to path `d`
//! strings (see `build_support.rs`). This keeps build deps at zero (no XML
//! crate) and means dropping any raw Lucide SVG into `assets/` Just Works.

use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

// Pure conversion helpers, shared with `tests/svg_convert.rs`.
include!("build_support.rs");

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("icons_generated.rs");
    let assets_dir = Path::new("assets");

    println!("cargo:rerun-if-changed=assets");
    println!("cargo:rerun-if-changed=build_support.rs");

    let mut output = String::new();
    output.push_str("// Auto-generated by build.rs — do not edit.\n");
    output.push_str("use runtime_core::{IconData, FillRule};\n\n");

    if !assets_dir.exists() {
        fs::write(&dest, &output).unwrap();
        return;
    }

    let mut entries: Vec<_> = fs::read_dir(assets_dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().extension().map_or(false, |ext| ext == "svg"))
        .collect();
    entries.sort_by_key(|e| e.file_name());

    let mut count = 0usize;
    // (kebab name, const name) pairs for the `registry`-gated `ALL` slice.
    let mut registry: Vec<(String, String)> = Vec::new();
    for entry in entries {
        let path = entry.path();
        let stem = path.file_stem().unwrap().to_str().unwrap();
        let const_name = to_screaming_snake(stem);
        registry.push((stem.to_string(), const_name.clone()));
        let svg_content = fs::read_to_string(&path).unwrap();

        let view_box = extract_view_box(&svg_content).unwrap_or((24, 24));
        let paths = svg_to_paths(&svg_content);
        let fill_rule = if svg_content.contains("evenodd") {
            "FillRule::EvenOdd"
        } else {
            "FillRule::NonZero"
        };

        output.push_str(&format!(
            "pub const {}: IconData = IconData {{\n    view_box: ({}, {}),\n    paths: &[",
            const_name, view_box.0, view_box.1
        ));
        for (i, p) in paths.iter().enumerate() {
            if i > 0 {
                output.push_str(", ");
            }
            let escaped = p.replace('\\', "\\\\").replace('"', "\\\"");
            output.push_str(&format!("\"{}\"", escaped));
        }
        // Lucide icons are outlined (stroke-only); `filled: false` preserves
        // the stroke rendering. A future filled icon pack would set this true.
        output.push_str(&format!(
            "],\n    fill_rule: {},\n    filled: false,\n}};\n\n",
            fill_rule
        ));
        count += 1;
    }

    output.push_str(&format!("\n/// Number of icons in this pack.\npub const ICON_COUNT: usize = {};\n", count));

    // The full registry, gated behind `registry` so it never defeats
    // tree-shaking for normal consumers (see the feature doc in Cargo.toml).
    output.push_str("\n#[cfg(feature = \"registry\")]\n");
    output.push_str("/// Every icon in the pack as `(name, data)`. Requires the `registry` feature.\n");
    output.push_str("pub static ALL: &[crate::IconEntry] = &[\n");
    for (name, const_name) in &registry {
        output.push_str(&format!(
            "    crate::IconEntry {{ name: {:?}, data: {} }},\n",
            name, const_name
        ));
    }
    output.push_str("];\n");

    // The `(name, ident)` name table the MCP catalog's `IconSetEntry`
    // points at, gated behind `catalog` so it's only paid for in catalog
    // builds (same rationale as `ALL` above — referencing it retains
    // every name string). `ident` is the generated `const` name, carried
    // verbatim so the catalog never has to re-derive the kebab→SCREAMING
    // transform (and its leading-digit edge case) downstream.
    output.push_str("\n#[cfg(feature = \"catalog\")]\n");
    output.push_str("/// Every icon as `(name, ident)` — the MCP catalog name table.\n");
    output.push_str("/// Requires the `catalog` feature.\n");
    output.push_str("pub static ICON_REFS: &[mcp_catalog::IconRef] = &[\n");
    for (name, const_name) in &registry {
        output.push_str(&format!(
            "    mcp_catalog::IconRef {{ name: {:?}, ident: {:?} }},\n",
            name, const_name
        ));
    }
    output.push_str("];\n");

    let mut file = fs::File::create(&dest).unwrap();
    file.write_all(output.as_bytes()).unwrap();
}
