//! iOS / iPadOS implementation of the menu-bar SDK.
//!
//! Mounts the supplied [`MenuBarSpec`] into UIKit's `UIMenuSystem`,
//! which is the surface the **Cmd-held keyboard HUD on iPad** uses
//! (and which iPhone falls back to as keyboard-shortcut hints when
//! a hardware keyboard is attached). The same `menu::install(...)`
//! call site works across macOS / Windows / Linux / iPad without
//! source change.
//!
//! # How UIKit menus differ from AppKit
//!
//! On macOS we call `NSApplication.setMainMenu:` once and AppKit
//! re-reads our supplied NSMenu on every paint. UIKit is the
//! opposite: the OS *asks the app* to build its menu via
//! `-[UIResponder buildMenuWithBuilder:]` whenever it wants to
//! present the HUD. We can't push a menu in; we can only **answer**
//! when asked, and force-ask via
//! `UIMenuSystem.mainSystem.setNeedsRebuild`.
//!
//! So `install` here:
//! 1. Stores the spec in a thread-local slot.
//! 2. Calls `setNeedsRebuild` to make UIKit re-ask soon.
//! 3. Expects the **host** to forward the eventual rebuild call into
//!    our [`apply_to_builder`] function from inside its AppDelegate's
//!    `buildMenuWithBuilder:` override.
//!
//! The host integration shim (in Swift or Obj-C; generated by the
//! CLI's iOS wrapper if you go that route) looks like:
//!
//! ```objc
//! - (void)buildMenuWithBuilder:(id<UIMenuBuilder>)builder {
//!     [super buildMenuWithBuilder:builder];
//!     idealyst_menu_apply_to_builder((__bridge void *)builder);
//! }
//! ```
//!
//! # Action routing
//!
//! Each command becomes a `UIAction` whose `handler` block fires
//! the stored Rust closure. UIAction is iOS 13+; iOS 12 and below
//! aren't supported by this SDK (the backend already requires 13+
//! for its scheduler / animation work, so this isn't a new floor).

use crate::{Menu, MenuBarSpec, MenuCommand, MenuItem, Modifiers, Shortcut};
use backend_ios::IosBackend;
use block2::{Block, RcBlock};
use objc2::rc::Retained;
use objc2::runtime::{AnyClass, AnyObject};
use objc2::{class, msg_send};
use objc2_foundation::{NSArray, NSObject, NSString};
use std::cell::RefCell;
use std::os::raw::c_void;

/// Install (or replace) the iPad menu system contribution. Stores
/// `spec` in a process-local slot and forces UIKit to re-ask for
/// menus via `UIMenuSystem.mainSystem.setNeedsRebuild`. The host's
/// AppDelegate must call [`apply_to_builder`] from its
/// `buildMenuWithBuilder:` override for the menus to actually
/// appear.
pub fn install(_backend: &mut IosBackend, spec: MenuBarSpec) {
    STORED_SPEC.with(|cell| {
        *cell.borrow_mut() = Some(spec);
    });
    force_rebuild();
}

/// Force UIKit to re-run the responder chain's
/// `buildMenuWithBuilder:` overrides. Apps can call this after
/// mutating menu-affecting state (e.g. toggling between view modes)
/// to refresh the HUD; `install` calls it automatically.
pub fn force_rebuild() {
    // `+[UIMenuSystem mainSystem]` returns the singleton; calling
    // `setNeedsRebuild` schedules a rebuild for the next runloop
    // turn. No-op if the symbol's missing (iOS < 13, vanishingly
    // unlikely in 2026).
    let Some(cls) = AnyClass::get("UIMenuSystem") else {
        return;
    };
    let main_system: *mut NSObject = unsafe { msg_send![cls, mainSystem] };
    if main_system.is_null() {
        return;
    }
    let _: () = unsafe { msg_send![main_system, setNeedsRebuild] };
}

thread_local! {
    /// The most-recently-installed MenuBarSpec. Read from
    /// [`apply_to_builder`] when UIKit calls back through the host's
    /// AppDelegate. Replaced atomically on each `install` call.
    static STORED_SPEC: RefCell<Option<MenuBarSpec>> = const { RefCell::new(None) };
}

/// FFI entry point the host's AppDelegate calls from inside
/// `-[AppDelegate buildMenuWithBuilder:]`. `builder` is the
/// `id<UIMenuBuilder>` UIKit passes — opaque to Rust, but we use
/// `msg_send` against the conforming protocol's selectors:
/// `insertChildMenu:atStartOfMenuForIdentifier:`,
/// `removeMenuForIdentifier:`, etc.
///
/// Safety: `builder` must be a live `id<UIMenuBuilder>` pointer,
/// non-null. Calling with anything else is undefined behavior.
#[no_mangle]
pub unsafe extern "C" fn idealyst_menu_apply_to_builder(builder: *mut c_void) {
    if builder.is_null() {
        return;
    }
    apply_to_builder_inner(builder.cast::<NSObject>());
}

/// Pure-Rust counterpart for host code that has a typed
/// `id<UIMenuBuilder>` (e.g. one extracted from an `objc2`-built
/// AppDelegate). The FFI variant above is the same path with the
/// pointer cast pushed to the boundary.
pub fn apply_to_builder(builder: &NSObject) {
    apply_to_builder_inner(builder as *const NSObject as *mut NSObject);
}

fn apply_to_builder_inner(builder: *mut NSObject) {
    STORED_SPEC.with(|cell| {
        let spec_ref = cell.borrow();
        let Some(spec) = spec_ref.as_ref() else {
            return;
        };

        // Insert each user-defined menu as a child of the root menu.
        // UIKit's root identifier is the empty NSString (per its
        // headers; the standard "UIMenuRoot" constant resolves to
        // `@""`). Inserting "at start" puts our menus before the
        // system's default Application / File / Edit / View chain.
        // Apps that want to insert AFTER specific identifiers can
        // call us multiple times with different scopes (future
        // API).
        let root_id = NSString::from_str("");
        for menu in &spec.menus {
            let nsmenu = build_uimenu(menu);
            unsafe {
                let _: () = msg_send![
                    builder,
                    insertChildMenu: &*nsmenu,
                    atStartOfMenuForIdentifier: &*root_id,
                ];
            }
        }
    });
}

// =========================================================================
// UIMenu / UIAction construction
// =========================================================================

fn build_uimenu(menu: &Menu) -> Retained<NSObject> {
    let title = NSString::from_str(&menu.title);
    let children = build_children(&menu.items);
    let menu_class = class!(UIMenu);
    // `+[UIMenu menuWithTitle:children:]` is the iOS 13+ class
    // method. Returns autoreleased; we retain via from_raw +
    // explicit retain to take ownership for our use.
    unsafe {
        let raw: *mut AnyObject = msg_send![
            menu_class,
            menuWithTitle: &*title,
            children: &*children,
        ];
        let retained: *mut AnyObject = msg_send![raw, retain];
        Retained::from_raw(retained.cast::<NSObject>())
            .expect("UIMenu menuWithTitle:children: returned nil")
    }
}

fn build_children(items: &[MenuItem]) -> Retained<NSArray<NSObject>> {
    let mut elements: Vec<Retained<NSObject>> = Vec::with_capacity(items.len());
    for item in items {
        match item {
            MenuItem::Command(cmd) => {
                elements.push(build_uiaction(cmd));
            }
            MenuItem::Separator => {
                // UIMenu sections aren't first-class — to render a
                // separator the idiomatic UIKit move is to nest the
                // items in a child UIMenu with `displayInline`
                // options. For v1 we skip separator rendering on
                // iPad (the HUD's visual grouping is less critical
                // than on a real menu bar). A follow-up can wrap
                // adjacent items in display-inline UIMenus.
            }
            MenuItem::Submenu(sub) => {
                // `build_uimenu` already returns Retained<NSObject>;
                // no upcast needed (UIMenu : UIMenuElement : NSObject
                // but our typed surface stops at NSObject).
                elements.push(build_uimenu(sub));
            }
        }
    }
    NSArray::from_vec(elements)
}

fn build_uiaction(cmd: &MenuCommand) -> Retained<NSObject> {
    let title = NSString::from_str(&cmd.label);
    let identifier = NSString::from_str(""); // empty = UIKit auto-generates
    let _ = cmd.enabled; // UIAction inherits enabled state from `attributes`
    let action_class = class!(UIAction);

    // Build the handler block. UIAction's `handler` parameter is a
    // `void (^)(UIAction *action)` block — `block2::RcBlock` gives
    // us a Rust-owned block that calls our closure.
    let cb_opt = cmd.on_click.clone();
    let block = RcBlock::new(move |_action: *mut AnyObject| {
        if let Some(cb) = &cb_opt {
            cb();
        }
    });
    let block_ptr: &Block<dyn Fn(*mut AnyObject)> = &block;

    let action: Retained<NSObject> = unsafe {
        let raw: *mut AnyObject = msg_send![
            action_class,
            actionWithTitle: &*title,
            image: std::ptr::null::<NSObject>(),
            identifier: &*identifier,
            handler: block_ptr,
        ];
        let retained: *mut AnyObject = msg_send![raw, retain];
        Retained::from_raw(retained.cast::<NSObject>())
            .expect("UIAction actionWithTitle:image:identifier:handler: returned nil")
    };

    // Disabled state: UIAction.attributes is a bitflag set; bit 1
    // is UIMenuElementAttributesDisabled (iOS 13+).
    if !cmd.enabled {
        let disabled_bit: usize = 1;
        let _: () = unsafe { msg_send![&*action, setAttributes: disabled_bit] };
    }

    // Shortcut: UIAction doesn't carry one directly, but if we
    // wanted Cmd-key hints in the HUD we'd convert to UIKeyCommand
    // (a sibling UIMenuElement type). For v1 the keyboard shortcut
    // is documented but not wired — the HUD just shows the label.
    let _ = cmd.shortcut.as_ref().map(format_shortcut);

    action
}

/// Format a `Shortcut` for UIKit display. Currently unused — left
/// as a hook for the follow-up UIKeyCommand integration. Maps our
/// `Modifiers` to `UIKeyModifierFlags` semantics:
/// - Cmd  → UIKeyModifierCommand  (1 << 20)
/// - Shift→ UIKeyModifierShift    (1 << 17)
/// - Option→ UIKeyModifierAlternate (1 << 19)
/// - Control→ UIKeyModifierControl (1 << 18)
#[allow(dead_code)]
fn format_shortcut(s: &Shortcut) -> (String, usize) {
    let mut mods: usize = 0;
    if s.modifiers.contains(Modifiers::COMMAND) {
        mods |= 1 << 20;
    }
    if s.modifiers.contains(Modifiers::SHIFT) {
        mods |= 1 << 17;
    }
    if s.modifiers.contains(Modifiers::OPTION) {
        mods |= 1 << 19;
    }
    if s.modifiers.contains(Modifiers::CONTROL) {
        mods |= 1 << 18;
    }
    let mut buf = [0u8; 4];
    let lower = s.key.to_ascii_lowercase();
    let key_str = lower.encode_utf8(&mut buf).to_string();
    (key_str, mods)
}
