// GENERATED by `idealyst run android` in AAS mode. Thin facade over
// the Rust JNI entry points. Matches the symbol names emitted by
// the generated AAS wrapper cdylib (`Java_<pkg>_NativeBridge_*`).

package {{PACKAGE}};

import android.content.Context;
import android.view.ViewGroup;

public class NativeBridge {
    /// Stand up the AAS client and discover the dev-host via Bonjour.
    /// Used when the device can see the host's mDNS broadcasts (most
    /// physical devices on the same Wi-Fi as the dev machine).
    public static native void attachAas(Context context, ViewGroup root, String appId);

    /// Direct-URL variant for the Android Studio emulator, whose
    /// QEMU user-mode network doesn't forward mDNS multicast. The
    /// CLI sets up `adb reverse` and bakes the resulting URL into
    /// Info.plist-style manifest meta-data (`IdealystAasUrl`);
    /// MainActivity reads that value and calls this instead.
    public static native void attachAasUrl(Context context, ViewGroup root, String url);

    /// Drain the worker's pending messages and apply them through
    /// the AasClient<AndroidBackend>. Call from a UI-thread tick.
    public static native void drainAas();

    /// Tear down the AAS client. Stops the drain channel; the
    /// worker thread exits on its next send attempt.
    public static native void detach();

    /// Called from `MainActivity.onConfigurationChanged` (rotation,
    /// multi-window resize, dark-mode toggle, density change, etc.).
    /// Triggers a framework layout pass against the host root's new
    /// dimensions on the AAS side's locally-mounted view tree.
    public static native void notifyConfigChanged();
}
