//! The wire-behavior gate: scenes realized through
//! `dev_server::newcore::SceneSession` (per-session `World` +
//! `runtime_vocabulary::register_builtins` + `realize`) must produce
//! wire command streams that reconstruct the expected client tree over
//! the real `wire::codec`.
//!
//! # Frozen snapshot
//!
//! The snapshot test compares the recorder's canonical catch-up stream
//! against the **frozen old-core snapshot** committed under
//! `tests/goldens/`, generated by the pre-runtime-v2 walker before it
//! was deleted. That is the strongest form of the compatibility claim:
//! a late-joining client receives byte-identical JSON to what the old
//! walker produced for the same logical scene, so it cannot tell which
//! implementation recorded the session. See `tests/goldens/README.md`;
//! the artifact is frozen testimony and cannot be regenerated.

use mock_backend::{NodeKind, WireHarness};
use runtime_scene::Element as SceneElement;
use runtime_vocabulary::builders::{button, text, view};

// ---------------------------------------------------------------------------
// Scene builders (vocabulary builders — the new-core Element form).
// ---------------------------------------------------------------------------

fn static_tree() -> SceneElement {
    view()
        .child(text().content("alpha"))
        .child(button().label("Tap me").on_press(|| {}))
        .child(view().child(text().content("nested")))
        .build()
}

// ---------------------------------------------------------------------------
// Structure: realize → wire → receiver reconstructs the tree.
// ---------------------------------------------------------------------------

#[test]
fn static_tree_reconstructs_structure_and_text() {
    let harness = WireHarness::mount(static_tree);
    let scene = harness.scene();

    // Pre-order text content — proves both structure AND ordering
    // survived realize + codec + receiver.
    assert_eq!(
        scene.texts(),
        vec!["alpha".to_string(), "Tap me".to_string(), "nested".to_string()],
        "reconstructed text (pre-order) is wrong:\n{}",
        scene.dump(),
    );

    assert_eq!(scene.count_kind(NodeKind::View), 2, "outer + nested view");
    assert_eq!(scene.count_kind(NodeKind::Text), 2);
    assert_eq!(scene.count_kind(NodeKind::Button), 1);
    assert_eq!(scene.roots().len(), 1, "exactly one finished root");

    let root = scene.roots()[0];
    assert_eq!(scene.children(root).len(), 3, "tree:\n{}", scene.dump());
}

// ---------------------------------------------------------------------------
// Reactivity: a world-signal mutation reaches the client as an
// update over the wire — the new-core reactive path end-to-end.
// ---------------------------------------------------------------------------

#[test]
fn reactive_text_update_propagates_over_wire() {
    use std::cell::Cell;
    use std::rc::Rc;

    // The signal is created INSIDE the session world (the mount closure
    // runs under `World::enter`); smuggle the Copy handle out so the
    // test can write it — the kernel routes the write to the signal's
    // own world, and `sync()`'s `World::flush` commits it (the same
    // dispatch-then-flush the sidecar's event loop performs).
    let count_slot: Rc<Cell<Option<runtime_world::Signal<i32>>>> = Rc::new(Cell::new(None));
    let slot_for_app = count_slot.clone();
    let mut harness = WireHarness::mount(move || {
        let count = runtime_world::signal(0_i32);
        slot_for_app.set(Some(count));
        view()
            .child(text().content(move || format!("count: {}", count.get())))
            .build()
    });

    assert!(
        harness.scene().contains_text("count: 0"),
        "initial reactive text must render; got:\n{}",
        harness.scene().dump(),
    );

    let count = count_slot.get().expect("signal captured during mount");
    count.set(5);
    let applied = harness.sync();
    assert!(applied >= 1, "a signal change must produce at least one wire command");

    let scene = harness.scene();
    assert!(
        scene.contains_text("count: 5"),
        "reactive update must reach the client; got:\n{}",
        scene.dump(),
    );
    assert!(
        !scene.contains_text("count: 0"),
        "stale text must have been replaced, not duplicated",
    );
}

#[test]
fn reactive_button_label_update_propagates_over_wire() {
    use std::cell::Cell;
    use std::rc::Rc;

    let label_slot: Rc<Cell<Option<runtime_world::Signal<i32>>>> = Rc::new(Cell::new(None));
    let slot_for_app = label_slot.clone();
    let mut harness = WireHarness::mount(move || {
        let label = runtime_world::signal(0_i32);
        slot_for_app.set(Some(label));
        button()
            .label(move || format!("clicked {}x", label.get()))
            .on_press(|| {})
            .build()
    });

    assert!(harness.scene().contains_text("clicked 0x"));

    let label = label_slot.get().expect("signal captured during mount");
    label.set(3);
    harness.sync();
    assert!(
        harness.scene().contains_text("clicked 3x"),
        "reactive button label must update over the wire; got:\n{}",
        harness.scene().dump(),
    );
}

// ---------------------------------------------------------------------------
// THE compatibility gate: the recorder's canonical catch-up snapshot for
// a fixed logical scene must match the frozen artifact byte for byte. A
// late-joining client receives `SceneModel::snapshot_commands`; if this
// JSON is unchanged, no client can tell that the implementation behind
// the recorder was replaced.
// ---------------------------------------------------------------------------

#[test]
fn snapshot_matches_the_frozen_catchup_artifact() {
    let harness = WireHarness::mount(static_tree);
    let snapshot = serde_json::to_value(harness.snapshot()).expect("serialize snapshot");
    let goldens = parity_goldens::Goldens::new(env!("CARGO_MANIFEST_DIR"));
    goldens.check_text(
        "static_tree_catchup_snapshot.json",
        &serde_json::to_string_pretty(&snapshot).unwrap(),
    );
}
