// GENERATED by `idealyst run android`. Single Activity that hands a
// Context + parent ViewGroup to the Rust JNI bridge so the framework
// can mount the shared `app()` tree underneath it.
//
// We use `android.app.Activity` (not AppCompat) because AppCompat
// requires the androidx.appcompat AAR, which would force us to pull
// in Maven/Gradle dependency resolution. Stock Activity is good
// enough for everything `backend-android` exercises.

package {{PACKAGE}};

import android.app.Activity;
import android.os.Bundle;
import android.view.ViewGroup;
import android.widget.FrameLayout;

public class MainActivity extends Activity {
    static {
        // Loading the cdylib fires its JNI_OnLoad, which caches the
        // JavaVM so the backend can attach threads on demand.
        System.loadLibrary("{{LIB_NAME}}");
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        FrameLayout root = new FrameLayout(this);
        root.setLayoutParams(new ViewGroup.LayoutParams(
            ViewGroup.LayoutParams.MATCH_PARENT,
            ViewGroup.LayoutParams.MATCH_PARENT));
        setContentView(root);
        NativeBridge.attach(this, root);
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        NativeBridge.detach();
    }
}
