// GENERATED by `idealyst run android`. Thin facade in front of the
// Rust JNI entry points. Keeps the `native` declarations off the
// Activity itself so MainActivity reads as pure UIKit-ish code.

package {{PACKAGE}};

import android.content.Context;
import android.view.ViewGroup;

public class NativeBridge {
    public static native void attach(Context context, ViewGroup root);
    public static native void detach();
}
