//! Android-side AAS shell glue.
//!
//! Mirrors `backend-ios::aas` but bridges to the Android UI thread
//! instead of UIKit's main queue. The cross-platform pieces — mDNS
//! discovery, WebSocket connect/reconnect, wire replay — live in
//! `dev-client::AasShell`; this module supplies only the Android-
//! specific parts:
//!
//! - Building an [`AndroidBackend`] from JNI-supplied `Context` +
//!   `ViewGroup` global refs and wrapping it in an `AasShell`.
//! - Holding the shell in a thread-local that survives across JNI
//!   calls, so a periodic Kotlin `Handler` tick can drain the
//!   worker's pending messages on the UI thread.
//!
//! The consuming staticlib crate (one will be generated by
//! `run-android --aas`) supplies the JNI exports themselves — their
//! symbols need to bake in the user's bundle id (`Java_<pkg>_…`)
//! which we can't predict from here. Each exported function is a
//! thin trampoline into one of the three entry points below.

#![cfg(all(target_os = "android", feature = "aas-shell"))]

use std::cell::RefCell;

use aas_shell_native::AasShell;
use jni::objects::JObject;
use jni::JNIEnv;

use crate::AndroidBackend;

thread_local! {
    /// The AAS shell lives on the UI thread for the lifetime of the
    /// hosting Activity. Held across JNI calls so [`drain`] can
    /// reach the same shell every tick. `RefCell` because both
    /// [`attach`] (mutating, takes-over the slot) and [`drain`]
    /// (read-only borrow plus internal mutation of the AasClient)
    /// need access at different times.
    static SHELL: RefCell<Option<AasShell<AndroidBackend>>> = const { RefCell::new(None) };
}

/// Stand up an AAS shell against a fresh [`AndroidBackend`] over the
/// Java-supplied `Context` + parent `ViewGroup`. Idempotent: any
/// previously installed shell is torn down before the new one stands
/// up. Spawns the background WebSocket worker that browses Bonjour
/// for a dev-server matching `app_id` and ferries wire frames onto
/// the UI thread's drain channel.
///
/// Called from the consuming staticlib's
/// `Java_<pkg>_NativeBridge_attachAas` JNI entry — that entry's
/// only job is to decode the `app_id_utf8` JString and delegate
/// here.
/// Install a one-time panic hook that routes Rust panics to logcat
/// via `log::error!`. Without this, panics print to stderr (fd 2),
/// which Android closes for app processes — so the panic message is
/// invisible and only the abort survives in tombstone. Idempotent.
fn install_panic_hook_once() {
    use std::sync::Once;
    static ONCE: Once = Once::new();
    ONCE.call_once(|| {
        let prev = std::panic::take_hook();
        std::panic::set_hook(Box::new(move |info| {
            log::error!("[aas-shell-android] PANIC: {info}");
            // Chain to whatever was installed before us (the default
            // hook, typically) so stderr also gets the message —
            // helps when capturing via `adb shell` directly.
            prev(info);
        }));
    });
}

pub fn attach<'l>(
    env: &mut JNIEnv<'l>,
    context: JObject<'l>,
    root: JObject<'l>,
    app_id: &str,
) {
    install_panic_hook_once();
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        // Promote both refs to globals so they survive past this
        // JNI call. Without globals, JNI tears down local refs as
        // soon as the frame unwinds.
        let context_global = env
            .new_global_ref(&context)
            .expect("new_global_ref(context)");
        let root_global = env
            .new_global_ref(&root)
            .expect("new_global_ref(root)");

        // Tear down any prior shell. Drops the previous worker
        // thread's outbound channel — the worker eventually notices
        // and exits when it next tries to send.
        SHELL.with(|slot| slot.borrow_mut().take());

        let backend = AndroidBackend::new(context_global, root_global);
        let shell = AasShell::spawn(backend, app_id.to_string());
        SHELL.with(|slot| *slot.borrow_mut() = Some(shell));

        log::info!(
            "[aas-shell-android] attach complete, browsing for app_id={:?}",
            app_id
        );
    }));
}

/// Same as [`attach`] but skips Bonjour discovery and points the
/// worker at a fixed WebSocket URL. The CLI uses this in concert
/// with `adb reverse` to make an Android-Studio-emulator client
/// reach the host: the emulator can't see the host's mDNS
/// advertisements (it lives behind QEMU's user-mode NAT), but
/// `adb reverse tcp:<port> tcp:<port>` makes the host's port
/// available at `127.0.0.1:<port>` inside the emulator, and that's
/// what the CLI bakes into Info.plist-style manifest meta-data
/// (`IdealystAasUrl`) for the Java side to pass here.
pub fn attach_with_url<'l>(
    env: &mut JNIEnv<'l>,
    context: JObject<'l>,
    root: JObject<'l>,
    url: &str,
) {
    install_panic_hook_once();
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let context_global = env
            .new_global_ref(&context)
            .expect("new_global_ref(context)");
        let root_global = env
            .new_global_ref(&root)
            .expect("new_global_ref(root)");

        SHELL.with(|slot| slot.borrow_mut().take());

        let backend = AndroidBackend::new(context_global, root_global);
        let shell = AasShell::spawn_with_url(backend, url.to_string());
        SHELL.with(|slot| *slot.borrow_mut() = Some(shell));

        log::info!(
            "[aas-shell-android] attach_with_url complete, connecting to {:?}",
            url
        );
    }));
}

/// Drain the worker thread's pending `DevToApp` messages and apply
/// them through the [`AasClient`](dev_client::AasClient).
///
/// Designed to be called from a `Handler.postDelayed` loop on the UI
/// thread (16ms cadence is fine). Cheap when there's nothing to do —
/// the inner `try_recv` returns immediately on an empty channel.
///
/// On Android, command application is synchronous: each `Backend`
/// trait call updates the View hierarchy directly. So there's no
/// post-batch layout flush hook to add here — the platform takes
/// care of measure/layout on the next vsync via its own dirty
/// tracking.
pub fn drain() {
    // `extern "system"` (JNI) ABI is `nounwind` — letting a panic
    // escape this function aborts the whole app process. The
    // wrapping `catch_unwind` traps any panic from inside the AAS
    // client's wire replay (mostly framework bugs hit during
    // command apply) so the worst case is a logged error instead of
    // a sudden disappearance.
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        SHELL.with(|slot| {
            if let Some(shell) = slot.borrow().as_ref() {
                shell.drain();
            }
        });
    }));
}

/// Tear down the active AAS shell. Called from the consuming
/// staticlib's `Java_<pkg>_NativeBridge_detach` JNI entry, typically
/// from the Activity's `onDestroy`.
pub fn detach() {
    SHELL.with(|slot| slot.borrow_mut().take());
}
