//! Android-side runtime-server shell glue.
//!
//! Mirrors `backend-ios::aas` but bridges to the Android UI thread
//! instead of UIKit's main queue. The cross-platform pieces —
//! WebSocket connect/reconnect, wire replay — live in
//! `RuntimeServerShell`; this module supplies only the Android-
//! specific parts:
//!
//! - Building an [`AndroidBackend`] from JNI-supplied `Context` +
//!   `ViewGroup` global refs and wrapping it in an `RuntimeServerShell`.
//! - Holding the shell in a thread-local that survives across JNI
//!   calls, so a periodic Kotlin `Handler` tick can drain the
//!   worker's pending messages on the UI thread.
//!
//! The consuming staticlib crate (one will be generated by
//! `run-android --aas`) supplies the JNI exports themselves — their
//! symbols need to bake in the user's bundle id (`Java_<pkg>_…`)
//! which we can't predict from here. Each exported function is a
//! thin trampoline into one of the entry points below.
//!
//! The dev-server URL comes from the manifest's `IdealystRuntimeServerUrl`
//! meta-data entry, which the CLI bakes in at `idealyst dev` time.

#![cfg(all(target_os = "android", feature = "runtime-server"))]

use std::cell::RefCell;

use runtime_server_shell_native::{RuntimeServerShell, RuntimeServerShellOptions, WirePlatform, WireViewport};
use jni::objects::JObject;
use jni::JNIEnv;

use crate::AndroidBackend;

/// Sample the parent `ViewGroup`'s `getWidth()` / `getHeight()` and
/// convert to CSS pixels. Both return `int` in device pixels post-
/// layout. We divide by `Resources.getSystem().getDisplayMetrics()
/// .density` so the value the sidecar sees matches the dp/css-px
/// space the wire protocol uses (web/iOS already report css px).
///
/// Returns `None` when called pre-layout (both dimensions are 0)
/// or if any JNI call fails — the sidecar will fall back to its
/// hardcoded 393×800 mobile-portrait default, which on a typical
/// phone is close enough that visual misalignment isn't dramatic.
/// A future revision can hook the ViewGroup's `OnLayoutChangeListener`
/// and emit `AppToDev::ViewportChanged` for accurate live sizing.
fn sample_viewport<'l>(
    env: &mut JNIEnv<'l>,
    root: &JObject<'l>,
) -> Option<WireViewport> {
    let width_px = env.call_method(root, "getWidth", "()I", &[]).ok()?.i().ok()?;
    let height_px = env.call_method(root, "getHeight", "()I", &[]).ok()?.i().ok()?;
    if width_px <= 0 || height_px <= 0 {
        return None;
    }
    // Density via `Resources.getSystem().getDisplayMetrics().density`.
    let resources_cls = env.find_class("android/content/res/Resources").ok()?;
    let system_resources = env
        .call_static_method(
            &resources_cls,
            "getSystem",
            "()Landroid/content/res/Resources;",
            &[],
        )
        .ok()?
        .l()
        .ok()?;
    let metrics = env
        .call_method(
            &system_resources,
            "getDisplayMetrics",
            "()Landroid/util/DisplayMetrics;",
            &[],
        )
        .ok()?
        .l()
        .ok()?;
    let density = env.get_field(&metrics, "density", "F").ok()?.f().ok()?;
    if density <= 0.0 {
        return None;
    }
    Some(WireViewport {
        width: width_px as f32 / density,
        height: height_px as f32 / density,
    })
}

thread_local! {
    /// The runtime-server shell lives on the UI thread for the lifetime of the
    /// hosting Activity. Held across JNI calls so [`drain`] can
    /// reach the same shell every tick. `RefCell` because both
    /// [`attach`] (mutating, takes-over the slot) and [`drain`]
    /// (read-only borrow plus internal mutation of the RuntimeServerClient)
    /// need access at different times.
    static SHELL: RefCell<Option<RuntimeServerShell<AndroidBackend>>> = const { RefCell::new(None) };
}

/// Install a one-time panic hook that routes Rust panics to logcat
/// via `log::error!`. Without this, panics print to stderr (fd 2),
/// which Android closes for app processes — so the panic message is
/// invisible and only the abort survives in tombstone. Idempotent.
fn install_panic_hook_once() {
    use std::sync::Once;
    static ONCE: Once = Once::new();
    ONCE.call_once(|| {
        let prev = std::panic::take_hook();
        std::panic::set_hook(Box::new(move |info| {
            log::error!("[runtime-server-android] PANIC: {info}");
            // Chain to whatever was installed before us (the default
            // hook, typically) so stderr also gets the message —
            // helps when capturing via `adb shell` directly.
            prev(info);
        }));
    });
}

/// Stand up a runtime-server shell against a fresh [`AndroidBackend`]
/// over the Java-supplied `Context` + parent `ViewGroup`. Idempotent:
/// any previously installed shell is torn down before the new one
/// stands up. Spawns the background WebSocket worker that connects to
/// the dev-server at `url` and ferries wire frames onto the UI
/// thread's drain channel.
///
/// `url` is `ws://host:port` baked into the manifest's
/// `IdealystRuntimeServerUrl` meta-data entry by `idealyst dev`.
/// For the Android emulator the CLI sets up `adb reverse` and bakes
/// `ws://127.0.0.1:<port>`; for physical devices on the same Wi-Fi
/// it's `ws://<lan-ip>:<port>`.
///
/// Called from the consuming staticlib's
/// `Java_<pkg>_NativeBridge_attachRuntimeServerUrl` JNI entry.
pub fn attach_with_url<'l>(
    env: &mut JNIEnv<'l>,
    context: JObject<'l>,
    root: JObject<'l>,
    url: &str,
) {
    install_panic_hook_once();
    let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let context_global = env
            .new_global_ref(&context)
            .expect("new_global_ref(context)");
        let root_global = env
            .new_global_ref(&root)
            .expect("new_global_ref(root)");

        SHELL.with(|slot| slot.borrow_mut().take());

        let viewport = sample_viewport(env, &root);
        let backend = AndroidBackend::new(context_global, root_global);
        let shell = RuntimeServerShell::spawn_with_options(
            backend,
            url.to_string(),
            RuntimeServerShellOptions {
                platform: WirePlatform::Android,
                device_label: None,
                viewport,
            },
        );
        SHELL.with(|slot| *slot.borrow_mut() = Some(shell));

        log::info!(
            "[runtime-server-android] attach complete, connecting to {:?}",
            url,
        );
    }));
    if result.is_err() {
        // catch_unwind here exists to print the panic before we abort
        // \u{2014} JNI return ABI is nounwind. Project policy is
        // crash-loud (the panic hook installed above logged the
        // message already, so we just need to abort).
        std::process::abort();
    }
}

/// Drain the worker thread's pending `DevToApp` messages and apply
/// them through the [`RuntimeServerClient`](dev_client::RuntimeServerClient).
///
/// Designed to be called from a `Handler.postDelayed` loop on the UI
/// thread (16ms cadence is fine). Cheap when there's nothing to do —
/// the inner `try_recv` returns immediately on an empty channel.
///
/// On Android, command application is synchronous: each `Backend`
/// trait call updates the View hierarchy directly. So there's no
/// post-batch layout flush hook to add here — the platform takes
/// care of measure/layout on the next vsync via its own dirty
/// tracking.
pub fn drain() {
    // `extern "system"` (JNI) ABI is `nounwind` \u{2014} letting a
    // Rust panic escape this function is UB. `catch_unwind` here
    // exists only to let the installed panic hook log the message
    // first; we then abort. Project policy is crash-loud (no
    // surviving the broken state that produced the panic).
    //
    // `RuntimeServerShell::tick` is the cross-platform "do everything per
    // frame" entry — report viewport, drain inbound (which sends
    // `RequestFrame`), run layout if anything was applied. Android
    // doesn't have a per-tick viewport channel here (Kotlin pushes
    // it separately via [`report_viewport`] from
    // `OnLayoutChangeListener`), so we pass `None` and let the
    // shell's last-reported value stand.
    let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        SHELL.with(|slot| {
            if let Some(shell) = slot.borrow().as_ref() {
                shell.tick(None);
            }
        });
    }));
    if result.is_err() {
        std::process::abort();
    }
}

/// Tear down the active runtime-server shell. Called from the consuming
/// staticlib's `Java_<pkg>_NativeBridge_detach` JNI entry, typically
/// from the Activity's `onDestroy`.
pub fn detach() {
    SHELL.with(|slot| slot.borrow_mut().take());
}

/// Report the host FrameLayout's current size to the sidecar.
/// Called from MainActivityRuntimeServer's `OnLayoutChangeListener` via the
/// generated `Java_<pkg>_NativeBridge_reportViewport` JNI entry —
/// the device-pixel width/height + the current density are passed
/// straight from the Java side. We divide by density to convert
/// to dp (== CSS px, the unit the wire protocol uses) so the
/// sidecar's `RecordingViewOps::frame()` returns the same kind of
/// number the iOS/web/macOS clients ship.
///
/// No-op if the shell hasn't been attached yet, density is
/// non-positive, or dimensions are zero (pre-layout call).
pub fn report_viewport(width_px: jni::sys::jint, height_px: jni::sys::jint, density: jni::sys::jfloat) {
    if width_px <= 0 || height_px <= 0 || density <= 0.0 {
        return;
    }
    let width_dp = width_px as f32 / density;
    let height_dp = height_px as f32 / density;
    // Mirror into the framework's reactive viewport signal — same dp
    // unit the wire protocol uses, so `viewport_size()` subscribers
    // see the same numbers a wire-replay backend would compute
    // against.
    runtime_core::set_viewport_size(runtime_core::ViewportSize {
        width: width_dp,
        height: height_dp,
    });
    let viewport = runtime_server_shell_native::WireViewport {
        width: width_dp,
        height: height_dp,
    };
    SHELL.with(|slot| {
        if let Some(shell) = slot.borrow().as_ref() {
            shell.report_viewport(viewport);
        }
    });
}
