//! `Lazy` primitive — wasm code-splitting boundaries.
//!
//! Declares a point in the UI tree where the subtree below is shipped
//! as a separate wasm chunk (web, via [`wasm-split`]) and inlined as
//! a regular function call on native targets. The chunk loads on first
//! mount; the author observes lifecycle via the `on_state` callback,
//! and a placeholder primitive is shown during the load.
//!
//! See `docs/proposals/lazy-primitive.md` for the full design.
//!
//! # Author API
//!
//! ```ignore
//! use runtime_core::lazy;
//! use runtime_core::ui;
//!
//! ui! {
//!     Text { "always loaded" }
//!     lazy! {
//!         Text { "loaded on demand from a chunk" }
//!     }
//! }
//! ```
//!
//! The `lazy!` macro expands its block into a `#[wasm_split]`-annotated
//! async function and emits a [`Element::Lazy`] that drives the
//! load+mount lifecycle.
//!
//! [`wasm-split`]: https://crates.io/crates/wasm-splitter

use crate::accessibility::AccessibilityProps;
use crate::builder::IntoElement;
use crate::handles::RefFill;
use crate::element::Element;
use crate::sources::{IntoStyleSource, StyleSource};
use std::future::Future;
use std::pin::Pin;
use std::rc::Rc;

// ---------------------------------------------------------------------------
// LazyState — lifecycle observable to author code via on_state.
// ---------------------------------------------------------------------------

/// Lifecycle phases of a `Element::Lazy`. Author code subscribes
/// via [`LazyBuilder::on_state`] to render its own loading / error
/// UI; the framework also mounts the [placeholder](LazyBuilder::placeholder)
/// during `Loading` / `Loaded` as an immediate fallback.
///
/// On native targets the chunk is compiled in and rendered inline —
/// the callback fires once with [`Rendered`](Self::Rendered) and
/// never observes [`Loading`](Self::Loading) or [`Loaded`](Self::Loaded).
#[derive(Clone, Debug)]
pub enum LazyState {
    /// Chunk fetch in flight. Web only — never observed on native.
    Loading,
    /// Chunk fetched and instantiated; the wrapper's async fn is
    /// being awaited. A brief window; many authors won't bother
    /// distinguishing this from `Loading`.
    Loaded,
    /// The chunk's `app()` returned and the subtree was mounted.
    Rendered,
    /// Fetch or invocation failed. The string is the underlying
    /// error, suitable for logging. Author decides whether to retry,
    /// fall back permanently, or surface to the user.
    Error(String),
}

impl LazyState {
    /// Convenience predicate for "show the placeholder" UI states.
    pub fn is_loading(&self) -> bool {
        matches!(self, LazyState::Loading | LazyState::Loaded)
    }

    /// Convenience predicate for "load failed" UI state.
    pub fn is_error(&self) -> bool {
        matches!(self, LazyState::Error(_))
    }
}

// ---------------------------------------------------------------------------
// LazyLoader — the load closure carried by Element::Lazy.
// ---------------------------------------------------------------------------

/// Future that resolves to the chunk's `Element`. Pinned + boxed
/// so the framework can carry many shapes through one slot.
pub type LazyFuture = Pin<Box<dyn Future<Output = Element>>>;

/// Closure that begins loading the chunk and returns a future for
/// the result. On native this resolves synchronously (the chunk
/// crate's `app()` is compiled in); on wasm the future awaits the
/// `wasm-split` runtime's `LazyLoader::load` + `.call` sequence
/// before yielding the chunk's `Element`.
///
/// Generated by the `lazy!` macro — author code should never
/// construct this by hand.
pub type LazyLoader = Box<dyn Fn() -> LazyFuture>;

// ---------------------------------------------------------------------------
// LazyBuilder + lazy_split() constructor — author surface (via macro).
// ---------------------------------------------------------------------------

/// Builder produced by [`lazy_split`]. Use `.on_state(...)`,
/// `.placeholder(...)`, and `.with_style(...)` to configure, then
/// drop into a `ui!` block or call `.into_element()`.
///
/// Authors don't typically touch this directly — the `lazy!` macro
/// constructs it. Public so the macro's emitted code (which expands
/// in user crates) can reach it.
#[must_use]
pub struct LazyBuilder {
    loader: LazyLoader,
    on_state: Option<Rc<dyn Fn(LazyState)>>,
    placeholder: Option<Box<dyn Fn() -> Element>>,
    style: Option<StyleSource>,
    ref_fill: Option<RefFill>,
    accessibility: AccessibilityProps,
}

impl LazyBuilder {
    /// Subscribe to lifecycle transitions. Fires synchronously on
    /// each state change; the callback should be cheap (typically
    /// a single `Signal::set`). Use this to drive a placeholder /
    /// error UI elsewhere in the tree.
    pub fn on_state<F>(mut self, f: F) -> Self
    where
        F: Fn(LazyState) + 'static,
    {
        // Born batched — see `reactive::cycle`.
        self.on_state = Some(Rc::new(move |s: LazyState| crate::cycle(|| f(s))));
        self
    }

    /// Set the placeholder rendered while the chunk loads. On native
    /// the placeholder is never visible (the chunk mounts
    /// synchronously). Default: nothing (an empty view).
    pub fn placeholder<F>(mut self, build: F) -> Self
    where
        F: Fn() -> Element + 'static,
    {
        self.placeholder = Some(Box::new(build));
        self
    }

    /// Attach a style to the container view (placeholder wrapper on
    /// web, mounted subtree's root on native).
    pub fn with_style<S: IntoStyleSource>(mut self, style: S) -> Self {
        self.style = Some(style.into_style_source());
        self
    }

    /// Attach accessibility props to the container.
    pub fn with_accessibility(mut self, a11y: AccessibilityProps) -> Self {
        self.accessibility = a11y;
        self
    }
}

impl IntoElement for LazyBuilder {
    fn into_element(self) -> Element {
        Element::Lazy {
            loader: self.loader,
            on_state: self.on_state,
            placeholder: self.placeholder,
            style: self.style,
            ref_fill: self.ref_fill,
            accessibility: self.accessibility,
        }
    }
}

/// Construct a lazy boundary from a load closure. Called by the
/// `lazy!` macro — author code typically uses the macro, not this
/// function directly. Public so the macro's expansion (in user
/// crates) can reach it.
pub fn lazy_split<F>(load: F) -> LazyBuilder
where
    F: Fn() -> LazyFuture + 'static,
{
    LazyBuilder {
        loader: Box::new(load),
        on_state: None,
        placeholder: None,
        style: None,
        ref_fill: None,
        accessibility: AccessibilityProps::default(),
    }
}

// ---------------------------------------------------------------------------
// Web dynamic-split loader seam
// ---------------------------------------------------------------------------
//
// In `--dynamic-split` web builds the `lazy!` body is NOT compiled into the
// main module — it's a separate PIC `--shared` side module, fetched and
// dynamically linked on demand. The macro's web expansion emits a stub that
// calls [`__dynlink_load`] with the body's hash; the web backend installs the
// actual loader (fetch + link the side, invoke its body fn, return the built
// `Element`) via [`install_dynlink_loader`] at boot. Same thin-seam pattern
// as `install_url_opener` — keeps the macro free of any backend dependency
// and core free of any web specifics.

thread_local! {
    static DYNLINK_LOADER: std::cell::RefCell<Option<Rc<dyn Fn(&'static str) -> LazyFuture>>> =
        const { std::cell::RefCell::new(None) };
}

/// Install the loader that fetches + dynamically links a `lazy!` body's side
/// module and resolves to its `Element`. Installed once by the web backend
/// at boot. No-op seam on every other backend — native targets compile lazy
/// bodies inline and never call [`__dynlink_load`].
#[doc(hidden)]
pub fn install_dynlink_loader(loader: Rc<dyn Fn(&'static str) -> LazyFuture>) {
    DYNLINK_LOADER.with(|c| *c.borrow_mut() = Some(loader));
}

/// Drive the installed dynamic-split loader for the body identified by
/// `hash`. Emitted by the `lazy!` macro's dynamic-split expansion (web builds
/// only) — author code never calls this. Degrades to an empty view if no
/// loader is installed, so a misconfigured build renders nothing rather than
/// panicking.
#[doc(hidden)]
pub fn __dynlink_load(hash: &'static str) -> LazyFuture {
    let loader = DYNLINK_LOADER.with(|c| c.borrow().clone());
    match loader {
        Some(f) => f(hash),
        None => Box::pin(async move {
            crate::logging::log(
                crate::logging::LogLevel::Error,
                "lazy! dynamic-split: no dynlink loader installed; rendering empty placeholder",
            );
            crate::builder::view(Vec::new()).into_element()
        }),
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::{view, Element};

    fn make_loader() -> LazyLoader {
        Box::new(|| {
            Box::pin(async {
                // Simulate the chunk's `app()` returning a primitive.
                view(Vec::new()).into_element()
            })
        })
    }

    #[test]
    fn constructor_emits_lazy_variant() {
        let p = lazy_split(|| {
            Box::pin(async { view(Vec::new()).into_element() })
        })
        .into_element();
        match p {
            Element::Lazy {
                on_state,
                placeholder,
                ..
            } => {
                assert!(on_state.is_none(), "default has no state observer");
                assert!(placeholder.is_none(), "default has no placeholder");
            }
            _ => panic!("expected Element::Lazy"),
        }
    }

    #[test]
    fn builder_methods_compose() {
        let state_calls = std::rc::Rc::new(std::cell::Cell::new(0u32));
        let counter = state_calls.clone();
        let p = lazy_split(|| Box::pin(async { view(Vec::new()).into_element() }))
            .on_state(move |_s| counter.set(counter.get() + 1))
            .placeholder(|| view(Vec::new()).into_element())
            .into_element();
        let Element::Lazy {
            on_state,
            placeholder,
            ..
        } = p
        else {
            panic!("expected Element::Lazy");
        };
        assert!(on_state.is_some());
        assert!(placeholder.is_some());
        on_state.unwrap()(LazyState::Loading);
        assert_eq!(state_calls.get(), 1);
    }

    #[test]
    fn lazy_state_predicates() {
        assert!(LazyState::Loading.is_loading());
        assert!(LazyState::Loaded.is_loading());
        assert!(!LazyState::Rendered.is_loading());
        assert!(!LazyState::Error("x".into()).is_loading());
        assert!(LazyState::Error("x".into()).is_error());
    }

    // Silence unused warning while keeping the helper around for
    // future tests of the load-and-mount integration.
    #[test]
    fn loader_helper_compiles() {
        let _ = make_loader();
    }

    // Poll a `LazyFuture` once; our seam futures are ready on first poll
    // (no real awaits in the test loaders / the fallback).
    fn poll_once(mut fut: LazyFuture) -> Option<Element> {
        use std::task::{Context, Poll};
        let waker = std::task::Waker::noop();
        let mut cx = Context::from_waker(waker);
        match fut.as_mut().poll(&mut cx) {
            Poll::Ready(p) => Some(p),
            Poll::Pending => None,
        }
    }

    #[test]
    fn dynlink_load_without_loader_degrades_to_view() {
        // Fresh test thread → no loader installed → empty-view fallback
        // instead of a panic.
        let p = poll_once(__dynlink_load("deadbeef")).expect("fallback future is ready");
        assert!(matches!(p, Element::View { .. }));
    }

    #[test]
    fn dynlink_load_invokes_installed_loader_with_hash() {
        use std::cell::Cell;
        let seen_hash = Rc::new(Cell::new(""));
        let h = seen_hash.clone();
        install_dynlink_loader(Rc::new(move |hash: &'static str| {
            h.set(hash);
            Box::pin(async { view(Vec::new()).into_element() })
        }));
        let p = poll_once(__dynlink_load("abc123")).expect("loader future is ready");
        assert_eq!(seen_hash.get(), "abc123", "loader must receive the body hash");
        assert!(matches!(p, Element::View { .. }));
    }
}
