//! Android secure store: AES-256-GCM with a key held in the
//! **AndroidKeyStore** (TEE / StrongBox-backed on supported devices, so
//! the key never leaves secure hardware), ciphertext parked in a private
//! `SharedPreferences` file. Framework classes only — no androidx, no
//! gradle-cache dependency.
//!
//! Per secret: a fresh GCM IV is generated by the cipher, and the stored
//! value is `base64(iv) ":" base64(ciphertext)` (`:` is outside the base64
//! alphabet, so it's an unambiguous separator).
//!
//! VERIFICATION: this backend is compile-checked here but **not yet
//! device-verified** — JNI method signatures are resolved at runtime, so a
//! typo surfaces only on-device. Every failure is returned as
//! [`CredError::Backend`] with the JNI message to make that diagnosis
//! quick. (See the crate README's verification note.)

use jni::objects::{JByteArray, JObject, JValue};
use jni::JavaVM;

use crate::{CredError, Credentials};

const MODE_PRIVATE: i32 = 0; // Context.MODE_PRIVATE
const PURPOSE_ENCRYPT_DECRYPT: i32 = 1 | 2; // KeyProperties.PURPOSE_ENCRYPT | PURPOSE_DECRYPT
const ENCRYPT_MODE: i32 = 1; // Cipher.ENCRYPT_MODE
const DECRYPT_MODE: i32 = 2; // Cipher.DECRYPT_MODE
const GCM_TAG_BITS: i32 = 128; // GCM authentication tag length
const KEY_SIZE_BITS: i32 = 256;
const BASE64_NO_WRAP: i32 = 2; // android.util.Base64.NO_WRAP

/// A [`Credentials`] over an AndroidKeyStore AES key + a prefs file.
pub struct KeystoreCredentials {
    /// AndroidKeyStore key alias (one wrapping key per store).
    alias: String,
    /// SharedPreferences file holding the ciphertext blobs.
    prefs: String,
}

impl KeystoreCredentials {
    pub fn new(namespace: &str) -> Self {
        Self {
            alias: format!("idealyst.credentials.{namespace}"),
            prefs: format!("idealyst.credentials.{namespace}"),
        }
    }
}

fn java_vm() -> Result<JavaVM, CredError> {
    let ctx = ndk_context::android_context();
    let vm_ptr = ctx.vm() as *mut jni::sys::JavaVM;
    unsafe { JavaVM::from_raw(vm_ptr) }
        .map_err(|e| CredError::Backend(format!("invalid JavaVM pointer: {e}")))
}

fn jni_err(e: jni::errors::Error) -> CredError {
    CredError::Backend(format!("JNI: {e}"))
}

impl Credentials for KeystoreCredentials {
    fn get(&self, key: &str) -> Result<Option<String>, CredError> {
        let vm = java_vm()?;
        let mut env = vm.attach_current_thread().map_err(jni_err)?;
        let blob = match prefs_get(&mut env, &self.prefs, key)? {
            Some(b) => b,
            None => return Ok(None),
        };
        let secret_key = ensure_key(&mut env, &self.alias)?;
        decrypt(&mut env, &secret_key, &blob).map(Some)
    }

    fn set(&self, key: &str, value: &str) -> Result<(), CredError> {
        let vm = java_vm()?;
        let mut env = vm.attach_current_thread().map_err(jni_err)?;
        let secret_key = ensure_key(&mut env, &self.alias)?;
        let blob = encrypt(&mut env, &secret_key, value)?;
        prefs_put(&mut env, &self.prefs, key, &blob)
    }

    fn remove(&self, key: &str) -> Result<(), CredError> {
        let vm = java_vm()?;
        let mut env = vm.attach_current_thread().map_err(jni_err)?;
        prefs_remove(&mut env, &self.prefs, key)
    }
}

// ---------------------------------------------------------------------------
// AndroidKeyStore key management
// ---------------------------------------------------------------------------

/// Load (or generate) the AES key for `alias` in the AndroidKeyStore and
/// return the `SecretKey` (as a `java.security.Key` local ref).
fn ensure_key<'a>(env: &mut jni::JNIEnv<'a>, alias: &str) -> Result<JObject<'a>, CredError> {
    // KeyStore ks = KeyStore.getInstance("AndroidKeyStore"); ks.load(null);
    let ks = env
        .call_static_method(
            "java/security/KeyStore",
            "getInstance",
            "(Ljava/lang/String;)Ljava/security/KeyStore;",
            &[(&env.new_string("AndroidKeyStore").map_err(jni_err)?).into()],
        )
        .map_err(jni_err)?
        .l()
        .map_err(jni_err)?;
    env.call_method(
        &ks,
        "load",
        "(Ljava/security/KeyStore$LoadStoreParameter;)V",
        &[JValue::Object(&JObject::null())],
    )
    .map_err(jni_err)?;

    let alias_j = env.new_string(alias).map_err(jni_err)?;
    let exists = env
        .call_method(
            &ks,
            "containsAlias",
            "(Ljava/lang/String;)Z",
            &[(&alias_j).into()],
        )
        .map_err(jni_err)?
        .z()
        .map_err(jni_err)?;

    if !exists {
        generate_key(env, alias)?;
    }

    // SecretKey key = (SecretKey) ks.getKey(alias, null);
    let alias_j = env.new_string(alias).map_err(jni_err)?;
    env.call_method(
        &ks,
        "getKey",
        "(Ljava/lang/String;[C)Ljava/security/Key;",
        &[(&alias_j).into(), JValue::Object(&JObject::null())],
    )
    .map_err(jni_err)?
    .l()
    .map_err(jni_err)
}

/// Generate a new AES-GCM key in the AndroidKeyStore under `alias`.
fn generate_key(env: &mut jni::JNIEnv<'_>, alias: &str) -> Result<(), CredError> {
    // KeyGenerator kg = KeyGenerator.getInstance("AES", "AndroidKeyStore");
    let kg = env
        .call_static_method(
            "javax/crypto/KeyGenerator",
            "getInstance",
            "(Ljava/lang/String;Ljava/lang/String;)Ljavax/crypto/KeyGenerator;",
            &[
                (&env.new_string("AES").map_err(jni_err)?).into(),
                (&env.new_string("AndroidKeyStore").map_err(jni_err)?).into(),
            ],
        )
        .map_err(jni_err)?
        .l()
        .map_err(jni_err)?;

    // new KeyGenParameterSpec.Builder(alias, PURPOSE_ENCRYPT | PURPOSE_DECRYPT)
    let alias_j = env.new_string(alias).map_err(jni_err)?;
    let builder = env
        .new_object(
            "android/security/keystore/KeyGenParameterSpec$Builder",
            "(Ljava/lang/String;I)V",
            &[(&alias_j).into(), JValue::Int(PURPOSE_ENCRYPT_DECRYPT)],
        )
        .map_err(jni_err)?;

    // .setBlockModes("GCM")
    let gcm = string_array(env, &["GCM"])?;
    env.call_method(
        &builder,
        "setBlockModes",
        "([Ljava/lang/String;)Landroid/security/keystore/KeyGenParameterSpec$Builder;",
        &[(&gcm).into()],
    )
    .map_err(jni_err)?;

    // .setEncryptionPaddings("NoPadding")
    let pad = string_array(env, &["NoPadding"])?;
    env.call_method(
        &builder,
        "setEncryptionPaddings",
        "([Ljava/lang/String;)Landroid/security/keystore/KeyGenParameterSpec$Builder;",
        &[(&pad).into()],
    )
    .map_err(jni_err)?;

    // .setKeySize(256)
    env.call_method(
        &builder,
        "setKeySize",
        "(I)Landroid/security/keystore/KeyGenParameterSpec$Builder;",
        &[JValue::Int(KEY_SIZE_BITS)],
    )
    .map_err(jni_err)?;

    // KeyGenParameterSpec spec = builder.build();
    let spec = env
        .call_method(
            &builder,
            "build",
            "()Landroid/security/keystore/KeyGenParameterSpec;",
            &[],
        )
        .map_err(jni_err)?
        .l()
        .map_err(jni_err)?;

    // kg.init(spec); kg.generateKey();
    env.call_method(
        &kg,
        "init",
        "(Ljava/security/spec/AlgorithmParameterSpec;)V",
        &[(&spec).into()],
    )
    .map_err(jni_err)?;
    env.call_method(&kg, "generateKey", "()Ljavax/crypto/SecretKey;", &[])
        .map_err(jni_err)?;
    Ok(())
}

// ---------------------------------------------------------------------------
// AES-GCM encrypt / decrypt via javax.crypto.Cipher
// ---------------------------------------------------------------------------

/// Encrypt `plaintext` → `base64(iv):base64(ciphertext)`.
fn encrypt(
    env: &mut jni::JNIEnv<'_>,
    key: &JObject<'_>,
    plaintext: &str,
) -> Result<String, CredError> {
    let cipher = cipher_instance(env)?;
    // c.init(ENCRYPT_MODE, key)
    env.call_method(
        &cipher,
        "init",
        "(ILjava/security/Key;)V",
        &[JValue::Int(ENCRYPT_MODE), JValue::Object(key)],
    )
    .map_err(jni_err)?;

    // byte[] iv = c.getIV();
    let iv = env
        .call_method(&cipher, "getIV", "()[B", &[])
        .map_err(jni_err)?
        .l()
        .map_err(jni_err)?;

    // byte[] ct = c.doFinal(plaintext);
    let pt_arr = env
        .byte_array_from_slice(plaintext.as_bytes())
        .map_err(jni_err)?;
    let ct = env
        .call_method(&cipher, "doFinal", "([B)[B", &[(&pt_arr).into()])
        .map_err(jni_err)?
        .l()
        .map_err(jni_err)?;

    let iv_b64 = base64_encode(env, &JByteArray::from(iv))?;
    let ct_b64 = base64_encode(env, &JByteArray::from(ct))?;
    Ok(format!("{iv_b64}:{ct_b64}"))
}

/// Decrypt `base64(iv):base64(ciphertext)` → plaintext.
fn decrypt(
    env: &mut jni::JNIEnv<'_>,
    key: &JObject<'_>,
    blob: &str,
) -> Result<String, CredError> {
    let (iv_b64, ct_b64) = blob
        .split_once(':')
        .ok_or_else(|| CredError::Backend("stored secret is malformed (no iv separator)".into()))?;
    let iv = base64_decode(env, iv_b64)?;
    let ct = base64_decode(env, ct_b64)?;

    // GCMParameterSpec spec = new GCMParameterSpec(128, iv);
    let spec = env
        .new_object(
            "javax/crypto/spec/GCMParameterSpec",
            "(I[B)V",
            &[JValue::Int(GCM_TAG_BITS), (&iv).into()],
        )
        .map_err(jni_err)?;

    let cipher = cipher_instance(env)?;
    // c.init(DECRYPT_MODE, key, spec)
    env.call_method(
        &cipher,
        "init",
        "(ILjava/security/Key;Ljava/security/spec/AlgorithmParameterSpec;)V",
        &[JValue::Int(DECRYPT_MODE), JValue::Object(key), (&spec).into()],
    )
    .map_err(jni_err)?;

    // byte[] pt = c.doFinal(ct);
    let pt = env
        .call_method(&cipher, "doFinal", "([B)[B", &[(&ct).into()])
        .map_err(jni_err)?
        .l()
        .map_err(jni_err)?;
    let bytes = env
        .convert_byte_array(JByteArray::from(pt))
        .map_err(jni_err)?;
    String::from_utf8(bytes).map_err(|e| CredError::Backend(format!("secret not valid UTF-8: {e}")))
}

/// `Cipher.getInstance("AES/GCM/NoPadding")`.
fn cipher_instance<'a>(env: &mut jni::JNIEnv<'a>) -> Result<JObject<'a>, CredError> {
    env.call_static_method(
        "javax/crypto/Cipher",
        "getInstance",
        "(Ljava/lang/String;)Ljavax/crypto/Cipher;",
        &[(&env.new_string("AES/GCM/NoPadding").map_err(jni_err)?).into()],
    )
    .map_err(jni_err)?
    .l()
    .map_err(jni_err)
}

// ---------------------------------------------------------------------------
// android.util.Base64 + helpers
// ---------------------------------------------------------------------------

fn base64_encode(env: &mut jni::JNIEnv<'_>, bytes: &JByteArray<'_>) -> Result<String, CredError> {
    let s = env
        .call_static_method(
            "android/util/Base64",
            "encodeToString",
            "([BI)Ljava/lang/String;",
            &[bytes.into(), JValue::Int(BASE64_NO_WRAP)],
        )
        .map_err(jni_err)?
        .l()
        .map_err(jni_err)?;
    Ok(env.get_string(&s.into()).map_err(jni_err)?.into())
}

fn base64_decode<'a>(
    env: &mut jni::JNIEnv<'a>,
    s: &str,
) -> Result<JByteArray<'a>, CredError> {
    let s_j = env.new_string(s).map_err(jni_err)?;
    let arr = env
        .call_static_method(
            "android/util/Base64",
            "decode",
            "(Ljava/lang/String;I)[B",
            &[(&s_j).into(), JValue::Int(BASE64_NO_WRAP)],
        )
        .map_err(jni_err)?
        .l()
        .map_err(jni_err)?;
    Ok(JByteArray::from(arr))
}

/// Build a `String[]` from Rust strs (for `setBlockModes` / paddings).
fn string_array<'a>(
    env: &mut jni::JNIEnv<'a>,
    items: &[&str],
) -> Result<jni::objects::JObjectArray<'a>, CredError> {
    let first = env.new_string(items[0]).map_err(jni_err)?;
    let arr = env
        .new_object_array(items.len() as i32, "java/lang/String", &first)
        .map_err(jni_err)?;
    for (i, s) in items.iter().enumerate().skip(1) {
        let v = env.new_string(s).map_err(jni_err)?;
        env.set_object_array_element(&arr, i as i32, &v)
            .map_err(jni_err)?;
    }
    Ok(arr)
}

// ---------------------------------------------------------------------------
// SharedPreferences (ciphertext store)
// ---------------------------------------------------------------------------

fn open_prefs<'a>(env: &mut jni::JNIEnv<'a>, name: &str) -> Result<JObject<'a>, CredError> {
    let ctx = ndk_context::android_context();
    let activity = unsafe { JObject::from_raw(ctx.context().cast()) };
    let name_j = env.new_string(name).map_err(jni_err)?;
    env.call_method(
        &activity,
        "getSharedPreferences",
        "(Ljava/lang/String;I)Landroid/content/SharedPreferences;",
        &[(&name_j).into(), JValue::Int(MODE_PRIVATE)],
    )
    .map_err(jni_err)?
    .l()
    .map_err(jni_err)
}

fn prefs_get(
    env: &mut jni::JNIEnv<'_>,
    prefs_name: &str,
    key: &str,
) -> Result<Option<String>, CredError> {
    let prefs = open_prefs(env, prefs_name)?;
    let key_j = env.new_string(key).map_err(jni_err)?;
    let value = env
        .call_method(
            &prefs,
            "getString",
            "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;",
            &[(&key_j).into(), JValue::Object(&JObject::null())],
        )
        .map_err(jni_err)?
        .l()
        .map_err(jni_err)?;
    if value.is_null() {
        Ok(None)
    } else {
        Ok(Some(env.get_string(&value.into()).map_err(jni_err)?.into()))
    }
}

fn prefs_put(
    env: &mut jni::JNIEnv<'_>,
    prefs_name: &str,
    key: &str,
    value: &str,
) -> Result<(), CredError> {
    let prefs = open_prefs(env, prefs_name)?;
    let editor = env
        .call_method(&prefs, "edit", "()Landroid/content/SharedPreferences$Editor;", &[])
        .map_err(jni_err)?
        .l()
        .map_err(jni_err)?;
    let key_j = env.new_string(key).map_err(jni_err)?;
    let val_j = env.new_string(value).map_err(jni_err)?;
    env.call_method(
        &editor,
        "putString",
        "(Ljava/lang/String;Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;",
        &[(&key_j).into(), (&val_j).into()],
    )
    .map_err(jni_err)?;
    env.call_method(&editor, "apply", "()V", &[]).map_err(jni_err)?;
    Ok(())
}

fn prefs_remove(env: &mut jni::JNIEnv<'_>, prefs_name: &str, key: &str) -> Result<(), CredError> {
    let prefs = open_prefs(env, prefs_name)?;
    let editor = env
        .call_method(&prefs, "edit", "()Landroid/content/SharedPreferences$Editor;", &[])
        .map_err(jni_err)?
        .l()
        .map_err(jni_err)?;
    let key_j = env.new_string(key).map_err(jni_err)?;
    env.call_method(
        &editor,
        "remove",
        "(Ljava/lang/String;)Landroid/content/SharedPreferences$Editor;",
        &[(&key_j).into()],
    )
    .map_err(jni_err)?;
    env.call_method(&editor, "apply", "()V", &[]).map_err(jni_err)?;
    Ok(())
}
