//! AAS dev-host build orchestration for `idealyst build aas`.
//!
//! AAS (Application-as-a-Server) runs the user's reactive runtime on
//! a dev-host process and lets browsers / native shells connect as
//! thin clients that ship primitive commands over a WebSocket. The
//! protocol and recording backend already live in the `dev-server`
//! crate — what's missing is the project-side wrapper that pulls in
//! the user's `app()` and stands the server up around it.
//!
//! Same shape as [`build-ios`](../build_ios/index.html): we generate
//! a tiny wrapper crate at:
//!
//! ```text
//! <workspace>/target/idealyst/<project>/aas/host/
//! ```
//!
//! …whose `Cargo.toml` declares a host-target binary and whose
//! `main.rs` is identical for every project modulo the
//! `<project>::app()` call site and the user-source watch path. We
//! cargo-build the wrapper for the host (no cross-compile — this
//! binary runs locally on the dev machine), and return the path to
//! the resulting executable.
//!
//! Regenerated every build. `idealyst scaffold aas` (future) will
//! materialize an editable copy into the repo for users who want to
//! customize the host.
//!
//! What's still TODO before AAS is "runnable":
//!
//! - The browser-side wasm shim — already buildable via the user
//!   crate's `dev-hot-reload` feature, but the CLI doesn't drive it
//!   yet. Lives in a future `run-aas` command.
//! - HTTP serving of the shim alongside the WebSocket host. Same
//!   command will glue `dev-http` + the host binary into one
//!   `idealyst dev --mode aas`.

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result};
use build_ios::{find_workspace_root, parse_manifest, Manifest};

#[derive(Clone, Debug)]
pub struct BuildOptions {
    /// Compile with `--release`. Default: debug. The host binary
    /// runs locally — release is almost never worth the slower
    /// rebuild cycle here.
    pub release: bool,
}

#[derive(Debug)]
pub struct BuildArtifact {
    /// Path to the produced host executable.
    pub host_binary: PathBuf,
    /// Wrapper crate directory. The host knows how to rebuild
    /// itself via this manifest path on source changes.
    pub wrapper_dir: PathBuf,
}

/// Bind address the generated host uses unless overridden via its
/// first CLI arg. `0.0.0.0:0` means "OS picks a free port and listen
/// on every interface" — the chosen port is published over mDNS so
/// clients (iOS, Android, …) discover the host without anyone having
/// to coordinate a fixed number. Listening on all interfaces matters
/// for physical devices on a LAN; loopback would only work for the
/// simulator.
const DEFAULT_BIND_ADDR: &str = "0.0.0.0:0";

pub fn build(project_dir: &Path, opts: BuildOptions) -> Result<BuildArtifact> {
    let project_dir = fs::canonicalize(project_dir)
        .with_context(|| format!("resolve project dir {}", project_dir.display()))?;
    let manifest = parse_manifest(&project_dir)?;
    let workspace_root = find_workspace_root(&project_dir)?;

    let wrapper_dir = workspace_root
        .join("target/idealyst")
        .join(&manifest.name)
        .join("aas/host");
    generate_wrapper(&wrapper_dir, &project_dir, &workspace_root, &manifest)?;

    cargo_build(&wrapper_dir, opts.release)?;

    let profile = if opts.release { "release" } else { "debug" };
    let bin_name = host_binary_name(&manifest.name);
    let host_binary = wrapper_dir
        .join("target")
        .join(profile)
        .join(&bin_name);

    if !host_binary.is_file() {
        anyhow::bail!(
            "cargo build reported success but host binary not at {}",
            host_binary.display(),
        );
    }

    Ok(BuildArtifact {
        host_binary,
        wrapper_dir,
    })
}

fn host_binary_name(project_name: &str) -> String {
    // Cargo names the binary after the package; we keep the hyphens
    // (cargo allows them in package names AND binary filenames).
    format!("{project_name}-aas-host")
}

// ---------------------------------------------------------------------------
// Wrapper generation
// ---------------------------------------------------------------------------

fn generate_wrapper(
    wrapper_dir: &Path,
    project_dir: &Path,
    workspace_root: &Path,
    manifest: &Manifest,
) -> Result<()> {
    fs::create_dir_all(wrapper_dir.join("src"))
        .with_context(|| format!("create {}", wrapper_dir.display()))?;

    let wrapper_name = host_binary_name(&manifest.name);
    let fcore = workspace_root.join("crates/framework/core");
    let dev_server = workspace_root.join("crates/framework/dev-server");

    let cargo_toml = format!(
        r#"# GENERATED by `idealyst build aas`. Do not edit — rewritten
# every build. Run `idealyst scaffold aas` to materialize an editable
# copy of this wrapper into your repo (once that command lands).

# Empty `[workspace]` declares this wrapper as a standalone project
# even though it physically lives under the main workspace's
# `target/idealyst/...`. Without it, cargo refuses to build because
# the parent Cargo.toml has `[workspace]` and would otherwise claim
# this directory as a member.
[workspace]

[package]
name = "{wrapper_name}"
version = "0.0.1"
edition = "2021"

[dependencies]
framework-core = {{ path = "{fcore}" }}
dev-server = {{ path = "{dev_server}" }}
{user_name} = {{ path = "{user_path}" }}
serde_json = "1"
"#,
        fcore = fcore.display(),
        dev_server = dev_server.display(),
        user_name = manifest.name,
        user_path = project_dir.display(),
    );

    let main_rs = format!(
        r#"//! GENERATED by `idealyst build aas`. Hosts `{lib}::app()` against
//! `dev-server::WireRecordingBackend`, serving the resulting wire
//! command stream over a WebSocket. Source changes under the user's
//! `src/` trigger a rebuild + self-exec; per-navigator URL stacks
//! are snapshotted across the process swap so the running UI state
//! survives a hot reload.
//!
//! The host binds an ephemeral port on every interface and
//! publishes itself over mDNS as `_idealyst-dev._tcp.` with a TXT
//! record carrying `{app_id}` — clients on the LAN (iOS sim,
//! physical device, etc.) discover it without anyone hard-coding a
//! port. Override the bind address by passing a different one as
//! the first CLI argument; useful for forcing loopback on machines
//! that don't want LAN exposure.

use std::cell::RefCell;
use std::path::PathBuf;
use std::rc::Rc;

use framework_core::render;
use {lib}::app;
use dev_server::{{
    serve, spawn_rebuild_loop, NavStateSnapshot, RebuildCommand, RebuildConfig,
    WireRecordingBackend,
}};

const DEFAULT_ADDR: &str = "{default_addr}";
/// mDNS-published app identifier. Clients discover this host by
/// matching their bundle id against the TXT record's app_id; that
/// way multiple idealyst projects can advertise on the same LAN
/// without colliding.
const APP_ID: &str = "{app_id}";

fn main() -> std::io::Result<()> {{
    let addr = std::env::args().nth(1).unwrap_or_else(|| DEFAULT_ADDR.to_string());

    let recorder = WireRecordingBackend::new();
    let backend_rc = Rc::new(RefCell::new(recorder.clone()));

    // Drive the user's tree through the real walker once at startup.
    // The recorder accumulates wire commands as an append-only log;
    // new clients catch up from offset 0, existing clients advance
    // a per-client cursor as events fire reactivity.
    let owner = render(backend_rc, app());
    // Keep the framework runtime alive for the lifetime of the
    // process — dropping `owner` would tear down every scope and
    // free every signal that backs reactive UI.
    std::mem::forget(owner);

    eprintln!("[aas-host] initial render done");

    // If we were exec'd by a previous instance after a source
    // change, the previous host passed its navigator stack forward
    // in `IDEALYST_AAS_NAV_STATE`. Read it now and replay the pushes
    // against the freshly-built navigators so the hierarchy comes
    // back exactly where it left off.
    if let Ok(json) = std::env::var("IDEALYST_AAS_NAV_STATE") {{
        match serde_json::from_str::<NavStateSnapshot>(&json) {{
            Ok(saved) if !saved.is_empty() => {{
                eprintln!(
                    "[aas-host] restoring nav state for {{}} navigator(s)",
                    saved.len()
                );
                recorder.restore_nav_state(&saved);
            }}
            Ok(_) => {{}}
            Err(e) => eprintln!("[aas-host] could not parse saved nav state: {{}}", e),
        }}
    }}

    // File watcher + auto-rebuild. We watch the USER's `src/` (not
    // the wrapper's) because that's where iteration happens; the
    // wrapper itself is regenerated only when `idealyst build aas`
    // is re-run.
    let watch_path = PathBuf::from("{user_src}");
    let wrapper_manifest = PathBuf::from("{wrapper_manifest}");
    let nav_mirror = recorder.nav_state_mirror();
    spawn_rebuild_loop(RebuildConfig {{
        // The wrapper crate has its own `[workspace]`, so cargo can
        // build it directly via `--manifest-path` without any cwd
        // contract.
        command: RebuildCommand {{
            program: "cargo".into(),
            args: vec![
                "build".into(),
                "--manifest-path".into(),
                wrapper_manifest.display().to_string(),
            ],
        }},
        watch_paths: vec![watch_path],
        // Tight enough to feel snappy, wide enough to coalesce
        // editor save-bursts (file-watchers commonly see multiple
        // events for one save on macOS).
        debounce: std::time::Duration::from_millis(100),
        before_exec: Some(Box::new(move || {{
            let snapshot = match nav_mirror.lock() {{
                Ok(g) => g.clone(),
                Err(_) => return Vec::new(),
            }};
            if snapshot.is_empty() {{
                return Vec::new();
            }}
            match serde_json::to_string(&snapshot) {{
                Ok(json) => {{
                    eprintln!(
                        "[aas-host] snapshotting nav state for {{}} navigator(s) before exec",
                        snapshot.len()
                    );
                    vec![("IDEALYST_AAS_NAV_STATE".to_string(), json)]
                }}
                Err(_) => Vec::new(),
            }}
        }})),
    }});

    eprintln!("[aas-host] starting (advertising app_id={{}} via mDNS)", APP_ID);
    serve(addr, recorder, APP_ID)
}}
"#,
        lib = manifest.lib_name,
        default_addr = DEFAULT_BIND_ADDR,
        app_id = manifest.app.require_bundle_id()?,
        user_src = project_dir.join("src").display(),
        wrapper_manifest = wrapper_dir.join("Cargo.toml").display(),
    );

    fs::write(wrapper_dir.join("Cargo.toml"), cargo_toml)?;
    fs::write(wrapper_dir.join("src/main.rs"), main_rs)?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Cargo invocation
// ---------------------------------------------------------------------------

fn cargo_build(wrapper_dir: &Path, release: bool) -> Result<()> {
    let mut cmd = Command::new("cargo");
    cmd.args(["build"]).current_dir(wrapper_dir);
    if release {
        cmd.arg("--release");
    }

    eprintln!(
        "[build-aas] cargo build{} (in {})",
        if release { " --release" } else { "" },
        wrapper_dir.display(),
    );
    let status = cmd
        .status()
        .with_context(|| "spawn `cargo` — is it on your PATH?")?;
    if !status.success() {
        anyhow::bail!("cargo build exited with {status}");
    }
    Ok(())
}
