//! Core concepts — app vs host crates, Primitive, signals, ui!, the Backend trait.

use runtime_core::{ui, Primitive, Ref, ViewHandle};
use idea_ui::{stack, typography, StackGap};

use crate::pages::common::{code_panel, page_header, page_section};
use crate::routes::{BACKENDS_ROUTE, WHY_RUST_ROUTE};
use crate::shell::{layout_with_toc, TocEntry};

pub fn page() -> Primitive {
    let app_vs_host_ref: Ref<ViewHandle> = Ref::new();
    let primitives_ref: Ref<ViewHandle> = Ref::new();
    let reactivity_ref: Ref<ViewHandle> = Ref::new();
    let ui_macro_ref: Ref<ViewHandle> = Ref::new();
    let builders_ref: Ref<ViewHandle> = Ref::new();
    let backend_ref: Ref<ViewHandle> = Ref::new();
    let building_ref: Ref<ViewHandle> = Ref::new();
    let next_ref: Ref<ViewHandle> = Ref::new();

    let toc = vec![
        TocEntry { handle: app_vs_host_ref, label: "App vs host crate" },
        TocEntry { handle: primitives_ref, label: "Primitives are the vocabulary" },
        TocEntry { handle: reactivity_ref, label: "Signals (reactivity)" },
        TocEntry { handle: ui_macro_ref, label: "The ui! macro" },
        TocEntry { handle: builders_ref, label: "Builders and Primitive" },
        TocEntry { handle: backend_ref, label: "The Backend trait" },
        TocEntry { handle: building_ref, label: "Building your own" },
        TocEntry { handle: next_ref, label: "Where to go from here" },
    ];

    let content = ui! {
        Stack(gap = StackGap::Xl) {
            { page_header(
                "Core concepts",
                "The ideas you need to hold in your head to read or write idealyst \
                 code: the app/host split, Primitive, signals, the `ui!` macro, the \
                 builder/Primitive distinction, the Backend trait, and the path to \
                 building your own component library and theme system on top."
            ) }
            { page_section(app_vs_host_ref, vec![app_vs_host()]) }
            { page_section(primitives_ref, vec![primitives()]) }
            { page_section(reactivity_ref, vec![reactivity()]) }
            { page_section(ui_macro_ref, vec![ui_macro()]) }
            { page_section(builders_ref, vec![builders()]) }
            { page_section(backend_ref, vec![backend_trait()]) }
            { page_section(building_ref, vec![building_your_own()]) }
            { page_section(next_ref, vec![where_next()]) }
        }
    };
    layout_with_toc(content, toc)
}

fn app_vs_host() -> Primitive {
    let children: Vec<Primitive> = vec![
        ui! { Typography(content = "App crate vs host crate".to_string(), kind = idea_ui::typography_kind::H2.into()) },
        ui! {
            Typography(content = "Your code lives in an app crate that depends only on \
                `runtime-core`. It declares components, styles, and a root tree, and knows \
                nothing about the platform it will run on.".to_string())
        },
        ui! {
            Typography(content = "A host crate is the tiny per-target wrapper that picks \
                a backend and mounts the app. Hosts are generated by the CLI under \
                `target/idealyst/<platform>/wrapper/` and are usually a single file. The \
                same `app()` function compiles into each host unchanged.".to_string())
        },
        ui! {
            Typography(content = "This separation is what makes \"one codebase, every \
                platform\" mean what it says \u{2014} the platform code is the host, and \
                you don't write it.".to_string())
        },
    ];
    ui! { Stack(gap = StackGap::Md) { children } }
}

fn primitives() -> Primitive {
    let snippet = "// Built-in primitives in runtime-core::Primitive:\n\
                   View · Text · Button · Image · TextInput · TextArea · ScrollView\n\
                   Slider · Toggle · Icon · Link · ActivityIndicator · Graphics\n\
                   Video · Virtualizer · Navigator · External (third-party SDKs)";
    let children: Vec<Primitive> = vec![
        ui! { Typography(content = "Primitives are the vocabulary".to_string(), kind = idea_ui::typography_kind::H2.into()) },
        ui! {
            Typography(content = "Every UI tree is built from a fixed set of `Primitive` \
                variants. The framework tells each backend \"create one of these, \
                update its props, attach these children\" \u{2014} the backend translates \
                that into a UIKit view, a DOM element, a wgpu draw call, whatever it owns.".to_string())
        },
        code_panel(snippet),
        ui! {
            Typography(content = "Components are functions that return a `Primitive` \
                tree. `#[component] fn welcome(props: &Props) -> Primitive` is the \
                whole contract. Composition is function composition; there's no class, \
                no lifecycle, no special framework method to override.".to_string())
        },
    ];
    ui! { Stack(gap = StackGap::Md) { children } }
}

fn reactivity() -> Primitive {
    let snippet = "let count = signal!(0);\n\
                   \n\
                   // `text_fmt!` builds a reactive text source. `bind!(signal)`\n\
                   // marks the args the framework subscribes to:\n\
                   ui! { Text { text_fmt!(\"Count: {}\", bind!(count)) } }\n\
                   \n\
                   // Update fires every subscribed dependent and nothing else:\n\
                   count.update(|n| *n += 1);";
    let children: Vec<Primitive> = vec![
        ui! { Typography(content = "Signals (the reactive layer)".to_string(), kind = idea_ui::typography_kind::H2.into()) },
        ui! {
            Typography(content = "`Signal<T>` is the framework's reactive primitive. Reads \
                inside a reactive scope (a component body, an effect, a style closure) \
                subscribe the surrounding scope to the signal's change set. Writes fire \
                every subscriber once \u{2014} no re-render passes, no diffing, no \
                reconciler.".to_string())
        },
        code_panel(snippet),
        ui! {
            Typography(content = "Effects, derived signals, and batched writes are all \
                exposed (see `framework_core::reactive`). The model is fine-grained: only \
                the primitives whose dependencies changed get touched.".to_string())
        },
    ];
    ui! { Stack(gap = StackGap::Md) { children } }
}

fn ui_macro() -> Primitive {
    let snippet = "// `ui!` is sugar over plain function calls.\n\
                   ui! {\n    \
                       View(style = card) {\n        \
                           Text { \"Hello\" }\n        \
                           Button(label = \"OK\", on_click = on_ok)\n    \
                       }\n\
                   }\n\
                   \n\
                   // ...desugars to roughly this:\n\
                   view(card, vec![\n    \
                       text(\"Hello\".to_string()),\n    \
                       button(&ButtonProps {\n        \
                           label: \"OK\".to_string(),\n        \
                           on_click: on_ok,\n        \
                           ..Default::default()\n    \
                       }),\n\
                   ])";
    let children: Vec<Primitive> = vec![
        ui! { Typography(content = "The `ui!` macro".to_string(), kind = idea_ui::typography_kind::H2.into()) },
        ui! {
            Typography(content = "`ui!` is the declarative authoring syntax. It's a \
                proc-macro that desugars to plain function calls against props structs \
                and `Primitive` constructors. Both forms compile to the same code; the \
                macro is opt-in (but recommended) sugar.".to_string())
        },
        code_panel(snippet),
        ui! {
            Typography(content = "The same author surface includes `#[component]` (turn \
                a function into a memoizable component), `stylesheet!` (typed \
                stylesheets with variants), `signal!` (allocate a reactive value), and \
                `jsx!` (an alternate angle-bracket syntax for authors who prefer it).".to_string())
        },
    ];
    ui! { Stack(gap = StackGap::Md) { children } }
}

fn builders() -> Primitive {
    let chain = "text(move || format!(\"Count: {}\", count.get()))\n    \
                     .bind(label_ref)             // attach a Ref<TextHandle>\n    \
                     .with_style(my_style)        // apply a stylesheet\n    \
                     .accessibility(a11y_props)   // accessibility metadata";
    let unwrap = "// Inside `ui!`, the macro inserts the unwrap for you.\n\
                  // Outside `ui!`, you spell it yourself:\n\
                  let label = text(move || format!(\"Count: {}\", count.get()))\n    \
                      .into_primitive();\n\
                  \n\
                  // `label` is now a Primitive \u{2014} can go into a Vec<Primitive>\n\
                  // or be passed as a child.";
    let children: Vec<Primitive> = vec![
        ui! { Typography(content = "Builders and `Primitive`".to_string(), kind = idea_ui::typography_kind::H2.into()) },
        ui! {
            Typography(content = "The `ui!` macro hides one detail you'll meet the \
                moment you step outside it. Primitive constructors don't return \
                `Primitive` directly \u{2014} they return a builder wrapper, typically \
                `Bound<H>`, where `H` is the primitive's handle type (`TextHandle`, \
                `ButtonHandle`, etc.). The wrapper exists so you can chain configuration \
                before committing to the final value.".to_string())
        },
        code_panel(chain),
        ui! {
            Typography(content = "Each method takes `self` and returns `Self`, so the \
                chain accumulates state. At the end of the chain you still have a \
                `Bound<TextHandle>`, not a `Primitive`.".to_string())
        },
        ui! {
            Typography(content = "Inside the `ui!` macro, an `.into_primitive()` call is \
                inserted at every leaf so the framework's tree sees `Primitive` values. \
                Outside `ui!`, you call it yourself.".to_string())
        },
        code_panel(unwrap),
        ui! {
            Typography(content = "If you forget the unwrap and try to use the builder \
                where a `Primitive` is expected, the compiler tells you exactly that: \
                `expected Primitive, found Bound<TextHandle>`. The fix is one method \
                call.".to_string())
        },
        ui! {
            Typography(content = "The same shape applies to every builder-returning \
                function in the framework \u{2014} `text`, `pressable`, `image`, \
                `anchored_overlay`, `code_block`, and the idea-ui components that wrap \
                them. If a function returns a builder, treat `.into_primitive()` as its \
                terminator when you need the bare `Primitive`.".to_string())
        },
    ];
    ui! { Stack(gap = StackGap::Md) { children } }
}

fn backend_trait() -> Primitive {
    let snippet = "// Sketch of the Backend trait (real surface is larger):\n\
                   pub trait Backend {\n    \
                       type Node;\n    \
                       fn create_view(&mut self, ...) -> Self::Node;\n    \
                       fn create_text(&mut self, ...) -> Self::Node;\n    \
                       fn create_button(&mut self, ...) -> Self::Node;\n    \
                       fn update_text(&mut self, node: &Self::Node, ...);\n    \
                       fn insert(&mut self, parent: &Self::Node, child: Self::Node, idx: usize);\n    \
                       // ...one method per primitive + property update path\n\
                   }";
    let children: Vec<Primitive> = vec![
        ui! { Typography(content = "The Backend trait".to_string(), kind = idea_ui::typography_kind::H2.into()) },
        ui! {
            Typography(content = "The framework's only seam to the platform. Implement \
                this trait once per target and the entire existing app surface runs \
                there. Web is `<div>`s and DOM mutations; iOS is `UIView` + `addSubview`; \
                Android is `android.view.View` + `addView`; wgpu is GPU draw calls.".to_string())
        },
        code_panel(snippet),
        ui! {
            Typography(content = "Adding a new platform is implementing a trait, not \
                forking the framework. Most backends fit in a single crate of moderate \
                size.".to_string())
        },
    ];
    ui! { Stack(gap = StackGap::Md) { children } }
}

fn building_your_own() -> Primitive {
    let component_snippet = "// A component is a function returning a Primitive.\n\
                             // That's the whole contract \u{2014} no class, no lifecycle\n\
                             // method, no framework-side registration.\n\
                             #[component]\n\
                             pub fn my_button(props: &MyButtonProps) -> Primitive {\n    \
                                 let on_click = props.on_click.clone();\n    \
                                 let label = props.label.clone();\n    \
                                 let style = MyButton().intent(props.intent);\n    \
                                 ui! {\n        \
                                     Pressable(on_click = move || (on_click)()) {\n            \
                                         Text(style = style) { label }\n        \
                                     }\n    \
                                 }\n\
                             }";
    let theme_snippet = "// 1. Define a theme trait \u{2014} the surface your library reads from.\n\
                         pub trait MyTheme: 'static {\n    \
                             fn accent(&self) -> Color;\n    \
                             fn radius_sharp(&self) -> f32;\n    \
                             fn brand_font(&self) -> FontFamily;\n\
                         }\n\
                         \n\
                         // 2. Stylesheets close over your theme type. The closure receives\n\
                         //    a typed reference to your concrete `MyTheme`-implementing struct.\n\
                         stylesheet! {\n    \
                             pub MyButton<MyThemeRef> {\n        \
                                 base(t) {\n            \
                                     background: t.accent(),\n            \
                                     border_radius: t.radius_sharp(),\n            \
                                     font_family: t.brand_font(),\n        \
                                 }\n    \
                             }\n\
                         }\n\
                         \n\
                         // 3. The app installs a concrete implementation at bootstrap.\n\
                         install_theme(MyConcreteTheme::default());";
    let children: Vec<Primitive> = vec![
        ui! { Typography(content = "Building your own".to_string(), kind = idea_ui::typography_kind::H2.into()) },
        ui! {
            Typography(content = "The framework's core is small on purpose. Most of what \
                idealyst-the-shipping-product is \u{2014} `idea-ui`, the navigator SDKs, \
                the icon registry \u{2014} sits on top of the framework as ordinary user \
                code. Your own component library and theme system slot in the same way.".to_string())
        },
        ui! { Typography(content = "Custom component libraries".to_string(), kind = idea_ui::typography_kind::H3.into()) },
        ui! {
            Typography(content = "A component library is a crate full of `#[component]` \
                functions. Each one takes a props struct, builds a `ui!` tree, returns a \
                `Primitive`. There's nothing privileged about idea-ui's components versus \
                yours \u{2014} they all go through the same path.".to_string())
        },
        code_panel(component_snippet),
        ui! {
            Typography(content = "Bundle a crate full of these, export them, and your \
                library's consumers `use my_lib::my_button` like any other Rust function. \
                The macros and primitives the framework ships are designed to be \
                composed; there's no framework-side registration step, no metadata to \
                ship, no plugin manifest.".to_string())
        },
        ui! { Typography(content = "Custom theme systems".to_string(), kind = idea_ui::typography_kind::H3.into()) },
        ui! {
            Typography(content = "A theme is a trait, not a struct. Your library defines \
                the trait \u{2014} which colors / sizes / weights / radii it reads from \
                \u{2014} and downstream apps implement the trait on their own concrete \
                type. The framework's stylesheet system handles the rest: token reads \
                are reactive, dark/light swaps re-fire every dependent rule, and the \
                same component code adapts to whatever theme is currently installed.".to_string())
        },
        code_panel(theme_snippet),
        ui! {
            Typography(content = "The pattern is straight from `idea-ui`. Its `IdeaTheme` \
                trait is what every shipped component reads; `light_theme()` / \
                `dark_theme()` are concrete implementations the app installs. Apps that \
                want more fields than the built-ins implement `IdeaTheme` on their own \
                struct \u{2014} same path, just extended.".to_string())
        },
        ui! {
            Typography(content = "Read idea-ui's source as the canonical reference. It's \
                an entire component library + theme system written against the framework's \
                primitives \u{2014} nothing more privileged than what your own code can do.".to_string())
        },
    ];
    ui! { Stack(gap = StackGap::Md) { children } }
}

fn where_next() -> Primitive {
    let title = ui! { Typography(content = "Where to go from here".to_string(), kind = idea_ui::typography_kind::H2.into()) };
    let para_a = ui! {
        Typography(content = "If you want the language-shape argument \u{2014} why this is \
            written in Rust rather than TypeScript or Kotlin \u{2014} read the Why Rust page.".to_string())
    };
    let cta_a = ui! {
        Link(route = &WHY_RUST_ROUTE, params = ()) {
            Typography(content = "Why Rust \u{2192}".to_string())
        }
    };
    let para_b = ui! {
        Typography(content = "If you want the per-target implementation status \u{2014} which \
            primitives are wired on which backends \u{2014} the Backends page has the matrix.".to_string())
    };
    let cta_b = ui! {
        Link(route = &BACKENDS_ROUTE, params = ()) {
            Typography(content = "Backends \u{2192}".to_string())
        }
    };
    let children: Vec<Primitive> = vec![title, para_a, cta_a, para_b, cta_b];
    ui! { Stack(gap = StackGap::Md) { children } }
}
