//! Core concepts — app vs host crates, Element, signals, ui!, the Backend trait.

use runtime_core::{ui, Element, Ref, ViewHandle};
use idea_ui::{Stack, Typography, StackGap};

use crate::pages::common::{CodePanel, PageHeader, PageSection};
use crate::routes::{BACKENDS_ROUTE, WHY_RUST_ROUTE};
use crate::shell::{layout_with_toc, TocEntry};

pub fn page() -> Element {
    let app_vs_host_ref: Ref<ViewHandle> = Ref::new();
    let primitives_ref: Ref<ViewHandle> = Ref::new();
    let reactivity_ref: Ref<ViewHandle> = Ref::new();
    let ui_macro_ref: Ref<ViewHandle> = Ref::new();
    let builders_ref: Ref<ViewHandle> = Ref::new();
    let backend_ref: Ref<ViewHandle> = Ref::new();
    let building_ref: Ref<ViewHandle> = Ref::new();
    let next_ref: Ref<ViewHandle> = Ref::new();

    let toc = vec![
        TocEntry { handle: app_vs_host_ref, label: "App vs host crate" },
        TocEntry { handle: primitives_ref, label: "Primitives are the vocabulary" },
        TocEntry { handle: reactivity_ref, label: "Signals (reactivity)" },
        TocEntry { handle: ui_macro_ref, label: "The ui! macro" },
        TocEntry { handle: builders_ref, label: "Builders and Element" },
        TocEntry { handle: backend_ref, label: "The Backend trait" },
        TocEntry { handle: building_ref, label: "Building your own" },
        TocEntry { handle: next_ref, label: "Where to go from here" },
    ];

    let content = ui! {
        Stack(gap = StackGap::Xl) {
            PageHeader(
                title = "Core concepts",
                blurb = "The ideas you need to hold in your head to read or write idealyst \
                 code: the app/host split, Element, signals, the `ui!` macro, the \
                 builder/Element distinction, the Backend trait, and the path to \
                 building your own component library and theme system on top.",
            )
            PageSection(handle = app_vs_host_ref) { app_vs_host() }
            PageSection(handle = primitives_ref) { primitives() }
            PageSection(handle = reactivity_ref) { reactivity() }
            PageSection(handle = ui_macro_ref) { ui_macro() }
            PageSection(handle = builders_ref) { builders() }
            PageSection(handle = backend_ref) { backend_trait() }
            PageSection(handle = building_ref) { building_your_own() }
            PageSection(handle = next_ref) { where_next() }
        }
    };
    layout_with_toc(content, toc)
}

fn app_vs_host() -> Element {
    let children: Vec<Element> = vec![
        ui! { Typography(content = "App crate vs host crate".to_string(), kind = idea_ui::typography_kind::H2) },
        ui! {
            Typography(content = "Your code lives in an app crate that depends only on \
                `runtime-core`. It declares components, styles, and a root tree, and knows \
                nothing about the platform it will run on.".to_string())
        },
        ui! {
            Typography(content = "A host crate is the tiny per-target wrapper that picks \
                a backend and mounts the app. Hosts are generated by the CLI under \
                `target/idealyst/<platform>/wrapper/` and are usually a single file. The \
                same `app()` function compiles into each host unchanged.".to_string())
        },
        ui! {
            Typography(content = "This separation is what makes \"one codebase, every \
                platform\" mean what it says \u{2014} the platform code is the host, and \
                you don't write it.".to_string())
        },
    ];
    ui! { Stack(gap = StackGap::Md) { children } }
}

fn primitives() -> Element {
    let snippet = "// Built-in primitives in runtime-core::Element:\n\
                   View · Text · Button · Image · TextInput · TextArea · ScrollView\n\
                   Slider · Toggle · Icon · Link · ActivityIndicator · Graphics\n\
                   Video · Virtualizer · Navigator · External (third-party SDKs)";
    let children: Vec<Element> = vec![
        ui! { Typography(content = "Primitives are the vocabulary".to_string(), kind = idea_ui::typography_kind::H2) },
        ui! {
            Typography(content = "Every UI tree is built from a fixed set of `Element` \
                variants. The framework tells each backend \"create one of these, \
                update its props, attach these children\" \u{2014} the backend translates \
                that into a UIKit view, a DOM element, a wgpu draw call, whatever it owns.".to_string())
        },
        ui! { CodePanel(src = snippet) },
        ui! {
            Typography(content = "Components are functions that return a `Element` \
                tree. `#[component] fn Welcome(props: &Props) -> Element` is the \
                whole contract. Composition is function composition; there's no class, \
                no lifecycle, no special framework method to override.".to_string())
        },
    ];
    ui! { Stack(gap = StackGap::Md) { children } }
}

fn reactivity() -> Element {
    let snippet = "let count = signal!(0);\n\
                   \n\
                   // `text_fmt!` builds a reactive text source. `bind!(signal)`\n\
                   // marks the args the framework subscribes to:\n\
                   ui! { text { text_fmt!(\"Count: {}\", bind!(count)) } }\n\
                   \n\
                   // Update fires every subscribed dependent and nothing else:\n\
                   count.update(|n| *n += 1);";
    let children: Vec<Element> = vec![
        ui! { Typography(content = "Signals (the reactive layer)".to_string(), kind = idea_ui::typography_kind::H2) },
        ui! {
            Typography(content = "`Signal<T>` is the framework's reactive primitive. Reads \
                inside a reactive scope (a component body, an effect, a style closure) \
                subscribe the surrounding scope to the signal's change set. Writes fire \
                every subscriber once \u{2014} no re-render passes, no diffing, no \
                reconciler.".to_string())
        },
        ui! { CodePanel(src = snippet) },
        ui! {
            Typography(content = "Effects, derived signals, and batched writes are all \
                exposed (see `framework_core::reactive`). The model is fine-grained: only \
                the primitives whose dependencies changed get touched.".to_string())
        },
    ];
    ui! { Stack(gap = StackGap::Md) { children } }
}

fn ui_macro() -> Element {
    let snippet = "// `ui!` is sugar over plain function calls.\n\
                   ui! {\n    \
                       view(style = card) {\n        \
                           text { \"Hello\" }\n        \
                           button(label = \"OK\", on_click = on_ok)\n    \
                       }\n\
                   }\n\
                   \n\
                   // ...desugars to roughly this:\n\
                   view(card, vec![\n    \
                       text(\"Hello\".to_string()),\n    \
                       button(&ButtonProps {\n        \
                           label: \"OK\".to_string(),\n        \
                           on_click: on_ok,\n        \
                           ..Default::default()\n    \
                       }),\n\
                   ])";
    let children: Vec<Element> = vec![
        ui! { Typography(content = "The `ui!` macro".to_string(), kind = idea_ui::typography_kind::H2) },
        ui! {
            Typography(content = "`ui!` is the declarative authoring syntax. It's a \
                proc-macro that desugars to plain function calls against props structs \
                and `Element` constructors. Both forms compile to the same code; the \
                macro is opt-in (but recommended) sugar.".to_string())
        },
        ui! { CodePanel(src = snippet) },
        ui! {
            Typography(content = "The same author surface includes `#[component]` (turn \
                a function into a memoizable component), `stylesheet!` (typed \
                stylesheets with variants), `signal!` (allocate a reactive value), and \
                `jsx!` (an alternate angle-bracket syntax for authors who prefer it).".to_string())
        },
    ];
    ui! { Stack(gap = StackGap::Md) { children } }
}

fn builders() -> Element {
    let chain = "text(move || format!(\"Count: {}\", count.get()))\n    \
                     .bind(label_ref)             // attach a Ref<TextHandle>\n    \
                     .with_style(my_style)        // apply a stylesheet\n    \
                     .accessibility(a11y_props)   // accessibility metadata";
    let unwrap = "// Inside `ui!`, the macro inserts the unwrap for you.\n\
                  // Outside `ui!`, you spell it yourself:\n\
                  let label = text(move || format!(\"Count: {}\", count.get()))\n    \
                      .into_element();\n\
                  \n\
                  // `label` is now a Element \u{2014} can go into a Vec<Element>\n\
                  // or be passed as a child.";
    let children: Vec<Element> = vec![
        ui! { Typography(content = "Builders and `Element`".to_string(), kind = idea_ui::typography_kind::H2) },
        ui! {
            Typography(content = "The `ui!` macro hides one detail you'll meet the \
                moment you step outside it. Element constructors don't return \
                `Element` directly \u{2014} they return a builder wrapper, typically \
                `Bound<H>`, where `H` is the primitive's handle type (`TextHandle`, \
                `ButtonHandle`, etc.). The wrapper exists so you can chain configuration \
                before committing to the final value.".to_string())
        },
        ui! { CodePanel(src = chain) },
        ui! {
            Typography(content = "Each method takes `self` and returns `Self`, so the \
                chain accumulates state. At the end of the chain you still have a \
                `Bound<TextHandle>`, not a `Element`.".to_string())
        },
        ui! {
            Typography(content = "Inside the `ui!` macro, an `.into_element()` call is \
                inserted at every leaf so the framework's tree sees `Element` values. \
                Outside `ui!`, you call it yourself.".to_string())
        },
        ui! { CodePanel(src = unwrap) },
        ui! {
            Typography(content = "If you forget the unwrap and try to use the builder \
                where a `Element` is expected, the compiler tells you exactly that: \
                `expected Element, found Bound<TextHandle>`. The fix is one method \
                call.".to_string())
        },
        ui! {
            Typography(content = "The same shape applies to every builder-returning \
                function in the framework \u{2014} `text`, `pressable`, `image`, \
                `anchored_overlay`, `code_block`, and the idea-ui components that wrap \
                them. If a function returns a builder, treat `.into_element()` as its \
                terminator when you need the bare `Element`.".to_string())
        },
    ];
    ui! { Stack(gap = StackGap::Md) { children } }
}

fn backend_trait() -> Element {
    let snippet = "// Sketch of the Backend trait (real surface is larger):\n\
                   pub trait Backend {\n    \
                       type Node;\n    \
                       fn create_view(&mut self, ...) -> Self::Node;\n    \
                       fn create_text(&mut self, ...) -> Self::Node;\n    \
                       fn create_button(&mut self, ...) -> Self::Node;\n    \
                       fn update_text(&mut self, node: &Self::Node, ...);\n    \
                       fn insert(&mut self, parent: &Self::Node, child: Self::Node, idx: usize);\n    \
                       // ...one method per primitive + property update path\n\
                   }";
    let children: Vec<Element> = vec![
        ui! { Typography(content = "The Backend trait".to_string(), kind = idea_ui::typography_kind::H2) },
        ui! {
            Typography(content = "The framework's only seam to the platform. Implement \
                this trait once per target and the entire existing app surface runs \
                there. Web is `<div>`s and DOM mutations; iOS is `UIView` + `addSubview`; \
                Android is `android.view.View` + `addView`; wgpu is GPU draw calls.".to_string())
        },
        ui! { CodePanel(src = snippet) },
        ui! {
            Typography(content = "Adding a new platform is implementing a trait, not \
                forking the framework. Most backends fit in a single crate of moderate \
                size.".to_string())
        },
    ];
    ui! { Stack(gap = StackGap::Md) { children } }
}

fn building_your_own() -> Element {
    let component_snippet = "// A component is a function returning a Element.\n\
                             // That's the whole contract \u{2014} no class, no lifecycle\n\
                             // method, no framework-side registration.\n\
                             #[component]\n\
                             pub fn MyButton(props: &MyButtonProps) -> Element {\n    \
                                 let on_click = props.on_click.clone();\n    \
                                 let label = props.label.clone();\n    \
                                 let style = button_style().intent(props.intent);\n    \
                                 ui! {\n        \
                                     Pressable(on_click = move || (on_click)()) {\n            \
                                         text(style = style) { label }\n        \
                                     }\n    \
                                 }\n\
                             }";
    let theme_snippet = "// 1. A theme is a struct that produces a flat token table.\n\
                         //    `ThemeTokens::tokens()` returns the (name, value) pairs.\n\
                         impl ThemeTokens for MyTheme {\n    \
                             fn tokens(&self) -> Vec<TokenEntry> {\n        \
                                 vec![\n            \
                                     TokenEntry { name: \"color-accent\", value: TokenValue::Color(self.accent.clone()) },\n            \
                                     TokenEntry { name: \"radius-md\", value: TokenValue::Length(self.radius) },\n        \
                                 ]\n    \
                             }\n\
                         }\n\
                         \n\
                         // 2. Stylesheets reference values by token NAME \u{2014} not by reading\n\
                         //    a theme struct. The `<()>` / `(_t)` slots are vestigial.\n\
                         stylesheet! {\n    \
                             pub MyButton<()> {\n        \
                                 base(_t) {\n            \
                                     background: Tokenized::token(\"color-accent\", Color(\"#5b6cff\".into())),\n            \
                                     border_radius: Tokenized::token(\"radius-md\", Length::Px(8.0)),\n        \
                                 }\n    \
                             }\n\
                         }\n\
                         \n\
                         // 3. Install at bootstrap; swap any time with set_theme(..).\n\
                         install_theme(MyTheme::default());";
    let children: Vec<Element> = vec![
        ui! { Typography(content = "Building your own".to_string(), kind = idea_ui::typography_kind::H2) },
        ui! {
            Typography(content = "The framework's core is small on purpose. Most of what \
                idealyst-the-shipping-product is \u{2014} `idea-ui`, the navigator SDKs, \
                the icon registry \u{2014} sits on top of the framework as ordinary user \
                code. Your own component library and theme system slot in the same way.".to_string())
        },
        ui! { Typography(content = "Custom component libraries".to_string(), kind = idea_ui::typography_kind::H3) },
        ui! {
            Typography(content = "A component library is a crate full of `#[component]` \
                functions. Each one takes a props struct, builds a `ui!` tree, returns a \
                `Element`. There's nothing privileged about idea-ui's components versus \
                yours \u{2014} they all go through the same path.".to_string())
        },
        ui! { CodePanel(src = component_snippet) },
        ui! {
            Typography(content = "Bundle a crate full of these, export them, and your \
                library's consumers `use my_lib::my_button` like any other Rust function. \
                The macros and primitives the framework ships are designed to be \
                composed; there's no framework-side registration step, no metadata to \
                ship, no plugin manifest.".to_string())
        },
        ui! { Typography(content = "Custom theme systems".to_string(), kind = idea_ui::typography_kind::H3) },
        ui! {
            Typography(content = "A theme is a collection of style tokens. Your library \
                defines a struct that implements `ThemeTokens` \u{2014} its `tokens()` method \
                returns the `(name, value)` table to install \u{2014} and stylesheets \
                reference those values by token name via `Tokenized::token(\"\u{2026}\", \
                fallback)`, never by reading the struct in their bodies. Token reads are \
                reactive: a dark/light swap (`set_theme(..)`) updates the tokens and \
                re-applies exactly the rules that read a changed one, so the same component \
                code adapts to whatever theme is currently installed.".to_string())
        },
        ui! { CodePanel(src = theme_snippet) },
        ui! {
            Typography(content = "The pattern is straight from `idea-ui`. Its theme structs \
                implement `ThemeTokens`; `light_theme()` / `dark_theme()` are ready-made \
                instances the app installs, and every shipped stylesheet references the \
                resulting tokens by name. Apps that want to retheme implement \
                `ThemeTokens` on their own struct \u{2014} same path, just more tokens.".to_string())
        },
        ui! {
            Typography(content = "Read idea-ui's source as the canonical reference. It's \
                an entire component library + theme system written against the framework's \
                primitives \u{2014} nothing more privileged than what your own code can do.".to_string())
        },
    ];
    ui! { Stack(gap = StackGap::Md) { children } }
}

fn where_next() -> Element {
    let title = ui! { Typography(content = "Where to go from here".to_string(), kind = idea_ui::typography_kind::H2) };
    let para_a = ui! {
        Typography(content = "If you want the language-shape argument \u{2014} why this is \
            written in Rust rather than TypeScript or Kotlin \u{2014} read the Why Rust page.".to_string())
    };
    let cta_a = ui! {
        link(route = &WHY_RUST_ROUTE, params = ()) {
            Typography(content = "Why Rust \u{2192}".to_string())
        }
    };
    let para_b = ui! {
        Typography(content = "If you want the per-target implementation status \u{2014} which \
            primitives are wired on which backends \u{2014} the Backends page has the matrix.".to_string())
    };
    let cta_b = ui! {
        link(route = &BACKENDS_ROUTE, params = ()) {
            Typography(content = "Backends \u{2192}".to_string())
        }
    };
    let children: Vec<Element> = vec![title, para_a, cta_a, para_b, cta_b];
    ui! { Stack(gap = StackGap::Md) { children } }
}
