//! `ui!` proc-macro — a JSX-style DSL that desugars to component calls.
//!
//! Grammar (informal):
//!
//! ```text
//! ui!         := node*
//! node        := component
//!              | 'if' rust_expr '{' node* '}' ('else' if_or_block)?
//!              | 'for' pat 'in' rust_expr '{' node* '}'
//!              | rust_expr       (anything else parses as a Rust expression
//!                                 and gets passed through to ChildList)
//! component   := ident '(' prop_list? ')' children?
//!              | ident children
//! prop_list   := prop (',' prop)* ','?
//! prop        := ident '=' rust_expr
//! children    := '{' node* '}'
//! ```
//!
//! ## Component recognition
//!
//! An identifier is parsed as a component invocation **only** when
//! immediately followed by `(` or `{`. Capitalization is purely a
//! convention; the parser doesn't consult it. A bare `Foo` (no parens,
//! no brace) is parsed as a plain Rust expression — useful for things
//! like dropping a precomputed `Primitive` into a children slot.
//!
//! ## Dispatch
//!
//! Each parsed component emits one of:
//!  - `text(expr)` for `Text` — content from a single-expr children block
//!    or from a `content = expr` prop.
//!  - `button(label, on_click)` for `Button`.
//!  - `view(children)` for `View`.
//!  - `name!(...)` for any other identifier (delegates to the per-component
//!    macro generated by `#[component]`).
//!
//! Reactive `if` (conditions containing `.get()`) is rewritten to
//! `when(cond, then, otherwise)`; non-reactive `if` is emitted verbatim.
//! `for` desugars to a `Vec<Primitive>` built by mapping over the
//! iterable.
//!
//! ## Attribute coercion
//!
//! String literal attribute values get an implicit `.into()` so
//! `label = "Score"` flows into a `String` field. Other attribute values
//! pass through verbatim — we don't apply generalized `.into()` because
//! of Rust inference fragility on non-literal types.

use proc_macro2::{Span, TokenStream as TokenStream2};
use quote::{quote, ToTokens};
use syn::parse::{Parse, ParseStream};
use syn::punctuated::Punctuated;
use syn::{braced, parenthesized, Expr, Ident, Token};

/// Top-level entry: a `ui! { ... }` invocation parses to a list of elements.
pub struct Ui {
    elements: Vec<UiNode>,
}

/// A single node in the UI tree. Either a component invocation we parsed,
/// or a raw Rust expression that goes through ChildList passthrough.
enum UiNode {
    Component {
        name: Ident,
        props: Vec<Prop>,
        children: Option<Vec<UiNode>>,
    },
    /// A `for` loop whose body is itself a UI block.
    For {
        pat: syn::Pat,
        iter: Expr,
        body: Vec<UiNode>,
    },
    /// An `if` / `if let` / `match`: parsed as a raw Rust expression with
    /// `ui!` recursively applied to each branch's contents.
    /// Branches always evaluate to a single UI node (or nothing for absent else).
    If {
        cond: Expr,
        then_body: Vec<UiNode>,
        else_body: Option<Vec<UiNode>>,
    },
    /// Arbitrary Rust expression to be flattened via ChildList.
    Expr(Expr),
}

struct Prop {
    name: Ident,
    value: Expr,
}

impl Parse for Ui {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let elements = parse_ui_nodes(input)?;
        Ok(Ui { elements })
    }
}

/// Parses a sequence of `UiNode`s until end-of-input.
fn parse_ui_nodes(input: ParseStream) -> syn::Result<Vec<UiNode>> {
    let mut out = Vec::new();
    while !input.is_empty() {
        out.push(parse_ui_node(input)?);
        // Optional commas between elements — purely cosmetic.
        let _ = input.parse::<Token![,]>();
    }
    Ok(out)
}

fn parse_ui_node(input: ParseStream) -> syn::Result<UiNode> {
    // Control flow keywords first.
    if input.peek(Token![if]) {
        return parse_if(input);
    }
    if input.peek(Token![for]) {
        return parse_for(input);
    }
    // Identifier followed by `(` or `{` is a component invocation:
    //   Foo()              Foo(props)              Foo { children }
    //   Foo(props) { children }
    // A bare `Foo` (no parens, no brace) is NOT a component — it parses
    // as a normal Rust expression. Capitalization is purely a convention;
    // the parser doesn't consult it.
    if input.peek(Ident) && next_is_component_invocation(input) {
        return parse_component(input);
    }
    // Fallback: parse a Rust expression. Goes through ChildList::append_to.
    let expr: Expr = input.parse()?;
    Ok(UiNode::Expr(expr))
}

/// Peeks past an identifier to see whether the *next* token is `(` or `{` —
/// the two shapes that mark a component invocation. We have to fork the
/// stream to do the lookahead.
fn next_is_component_invocation(input: ParseStream) -> bool {
    let fork = input.fork();
    if fork.parse::<Ident>().is_err() {
        return false;
    }
    fork.peek(syn::token::Paren) || fork.peek(syn::token::Brace)
}

fn parse_component(input: ParseStream) -> syn::Result<UiNode> {
    let name: Ident = input.parse()?;

    // Optional `(prop = expr, ...)` props list.
    let props = if input.peek(syn::token::Paren) {
        let content;
        parenthesized!(content in input);
        let pairs: Punctuated<Prop, Token![,]> = content.parse_terminated(Prop::parse, Token![,])?;
        pairs.into_iter().collect()
    } else {
        Vec::new()
    };

    // Optional `{ children }` block.
    let children = if input.peek(syn::token::Brace) {
        let content;
        braced!(content in input);
        Some(parse_ui_nodes(&content)?)
    } else {
        None
    };

    Ok(UiNode::Component { name, props, children })
}

fn parse_if(input: ParseStream) -> syn::Result<UiNode> {
    let _if_token: Token![if] = input.parse()?;
    // Parse the condition as a Rust expression. `Expr::parse_without_eager_brace`
    // stops the parser from consuming the trailing `{` as a struct-literal.
    let cond: Expr = Expr::parse_without_eager_brace(input)?;
    let then_content;
    braced!(then_content in input);
    let then_body = parse_ui_nodes(&then_content)?;

    let else_body = if input.peek(Token![else]) {
        let _: Token![else] = input.parse()?;
        // Allow chained `else if` by wrapping the rest as a single If node.
        if input.peek(Token![if]) {
            let nested = parse_if(input)?;
            Some(vec![nested])
        } else {
            let else_content;
            braced!(else_content in input);
            Some(parse_ui_nodes(&else_content)?)
        }
    } else {
        None
    };

    Ok(UiNode::If { cond, then_body, else_body })
}

fn parse_for(input: ParseStream) -> syn::Result<UiNode> {
    let _for_token: Token![for] = input.parse()?;
    let pat = syn::Pat::parse_single(input)?;
    let _in_token: Token![in] = input.parse()?;
    let iter: Expr = Expr::parse_without_eager_brace(input)?;
    let body_content;
    braced!(body_content in input);
    let body = parse_ui_nodes(&body_content)?;
    Ok(UiNode::For { pat, iter, body })
}

impl Parse for Prop {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let name: Ident = input.parse()?;
        let _: Token![=] = input.parse()?;
        let value: Expr = input.parse()?;
        Ok(Prop { name, value })
    }
}

// =============================================================================
// Emit
// =============================================================================

/// Top-level emit: produce a single expression that yields a `Primitive`.
/// If the `ui!` body has exactly one element, emit it directly. Otherwise
/// wrap in `view(children![...])`.
pub fn emit(ui: Ui) -> TokenStream2 {
    match ui.elements.len() {
        0 => quote! { ::framework_core::view(::std::vec::Vec::new()) },
        1 => emit_node(&ui.elements[0]),
        _ => {
            let kids = ui.elements.iter().map(emit_node);
            quote! {
                ::framework_core::view({
                    let mut __c: ::std::vec::Vec<::framework_core::Primitive>
                        = ::std::vec::Vec::new();
                    #( ::framework_core::ChildList::append_to(#kids, &mut __c); )*
                    __c
                })
            }
        }
    }
}

fn emit_node(node: &UiNode) -> TokenStream2 {
    match node {
        UiNode::Component { name, props, children } => emit_component(name, props, children.as_deref()),
        UiNode::If { cond, then_body, else_body } => emit_if(cond, then_body, else_body.as_deref()),
        UiNode::For { pat, iter, body } => emit_for(pat, iter, body),
        UiNode::Expr(e) => e.to_token_stream(),
    }
}

/// Emit a prop's value tokens. String literals get an implicit `.into()` so
/// `label = "Score"` can flow into a `String` field without `.to_string()`.
/// Other expressions pass through verbatim — we don't want generalized
/// .into() coercion because of inference fragility on non-literal types.
fn emit_attr_value(value: &Expr) -> TokenStream2 {
    if matches!(value, Expr::Lit(syn::ExprLit { lit: syn::Lit::Str(_), .. })) {
        quote! { #value.into() }
    } else {
        quote! { #value }
    }
}

/// Emit a component invocation. Primitives (Text/Button/View/When) dispatch
/// to free functions in framework_core; other names dispatch to per-component
/// `name!` macros generated by `#[component]`.
fn emit_component(name: &Ident, props: &[Prop], children: Option<&[UiNode]>) -> TokenStream2 {
    let lower = name.to_string().to_ascii_lowercase();
    // For primitives, recognize a `style = ...` attribute and emit a
    // `.with_style(...)` chain on the result. Strip the style prop from
    // the props list before dispatching to the per-primitive emitter.
    // For user components, pass the style prop through unchanged — the
    // component author decides what to do with it (typically declares
    // `style: StyleApplication` in their props struct and applies it).
    let is_primitive = matches!(lower.as_str(), "text" | "button" | "view" | "when");

    let (style_prop, other_props): (Vec<&Prop>, Vec<&Prop>) =
        if is_primitive {
            let mut style = None;
            let mut rest = Vec::with_capacity(props.len());
            for p in props {
                if p.name == "style" && style.is_none() {
                    style = Some(p);
                } else {
                    rest.push(p);
                }
            }
            (style.into_iter().collect(), rest)
        } else {
            (Vec::new(), props.iter().collect())
        };

    let other_props: Vec<Prop> = other_props
        .into_iter()
        .map(|p| Prop { name: p.name.clone(), value: p.value.clone() })
        .collect();

    let inner = match lower.as_str() {
        "text" => emit_text(&other_props, children),
        "button" => emit_button(&other_props, children),
        "view" => emit_view(&other_props, children),
        "when" => emit_when(&other_props, children),
        _ => emit_user(name, props, children),
    };

    if let Some(p) = style_prop.first() {
        let v = &p.value;
        quote! { (#inner).with_style(#v) }
    } else {
        inner
    }
}

fn emit_text(props: &[Prop], children: Option<&[UiNode]>) -> TokenStream2 {
    // Text takes its content from either a `content` prop or a children
    // block. The children block is preferred when present.
    if let Some(kids) = children {
        // Single Rust expression preferred; if multi-item, concatenate via
        // a String build expression. Keep it simple: single-item only for now.
        match kids.len() {
            0 => quote! { ::framework_core::text("") },
            1 => {
                let e = emit_node(&kids[0]);
                quote! { ::framework_core::text(#e) }
            }
            _ => {
                let parts = kids.iter().map(emit_node);
                quote! {
                    ::framework_core::text({
                        let mut __s = ::std::string::String::new();
                        #( __s.push_str(&::std::string::ToString::to_string(&#parts)); )*
                        __s
                    })
                }
            }
        }
    } else {
        // No children block. Look for a `content` prop.
        if let Some(p) = props.iter().find(|p| p.name == "content") {
            let v = &p.value;
            quote! { ::framework_core::text(#v) }
        } else {
            quote! { ::framework_core::text("") }
        }
    }
}

fn emit_button(props: &[Prop], _children: Option<&[UiNode]>) -> TokenStream2 {
    let label = props
        .iter()
        .find(|p| p.name == "label")
        .map(|p| p.value.to_token_stream())
        .unwrap_or_else(|| quote! { "" });
    let on_click = props
        .iter()
        .find(|p| p.name == "on_click")
        .map(|p| p.value.to_token_stream())
        .unwrap_or_else(|| quote! { || {} });
    quote! { ::framework_core::button(#label, #on_click) }
}

fn emit_view(_props: &[Prop], children: Option<&[UiNode]>) -> TokenStream2 {
    let kids = children.unwrap_or(&[]);
    let parts = kids.iter().map(emit_node);
    quote! {
        ::framework_core::view({
            let mut __c: ::std::vec::Vec<::framework_core::Primitive>
                = ::std::vec::Vec::new();
            #( ::framework_core::ChildList::append_to(#parts, &mut __c); )*
            __c
        })
    }
}

fn emit_when(props: &[Prop], _children: Option<&[UiNode]>) -> TokenStream2 {
    let cond = props.iter().find(|p| p.name == "cond").map(|p| p.value.to_token_stream()).unwrap_or_else(|| quote! { || false });
    let then_e = props.iter().find(|p| p.name == "then").map(|p| p.value.to_token_stream()).unwrap_or_else(|| quote! { || ::framework_core::view(::std::vec::Vec::new()) });
    let other = props.iter().find(|p| p.name == "otherwise").map(|p| p.value.to_token_stream()).unwrap_or_else(|| quote! { || ::framework_core::view(::std::vec::Vec::new()) });
    quote! { ::framework_core::when(#cond, #then_e, #other) }
}

/// Emit a user-defined component invocation. Lowercases the name and calls
/// the per-component macro generated by `#[component]`. Children block (if
/// present) becomes the `children` prop, wrapped in `children![...]`.
fn emit_user(name: &Ident, props: &[Prop], children: Option<&[UiNode]>) -> TokenStream2 {
    let lower = Ident::new(&name.to_string().to_ascii_lowercase(), name.span());
    let prop_assignments = props.iter().map(|p| {
        let n = &p.name;
        let v = emit_attr_value(&p.value);
        quote! { #n = #v }
    });

    if let Some(kids) = children {
        let parts = kids.iter().map(emit_node);
        // Always emit children as a Vec<Primitive>. If the component expects
        // a different type, the user gets a type error at the call site —
        // intentional; we don't try to be polymorphic across children types
        // for user components in this first cut.
        quote! {
            #lower!(
                #(#prop_assignments,)*
                children = {
                    let mut __c: ::std::vec::Vec<::framework_core::Primitive>
                        = ::std::vec::Vec::new();
                    #( ::framework_core::ChildList::append_to(#parts, &mut __c); )*
                    __c
                }
            )
        }
    } else {
        quote! { #lower!( #(#prop_assignments),* ) }
    }
}

fn emit_if(cond: &Expr, then_body: &[UiNode], else_body: Option<&[UiNode]>) -> TokenStream2 {
    let then_expr = emit_block_as_primitive(then_body);
    let else_expr = match else_body {
        Some(body) => emit_block_as_primitive(body),
        None => quote! { ::framework_core::view(::std::vec::Vec::new()) },
    };

    // Reactivity heuristic: if the condition contains `.get()`, dispatch
    // to `when()` so the subtree re-runs on signal changes. Otherwise
    // emit a plain `if`. The `.get()` is the author's signal of intent.
    if condition_is_reactive(cond) {
        quote! {
            ::framework_core::when(
                move || #cond,
                move || #then_expr,
                move || #else_expr,
            )
        }
    } else {
        quote! {
            if #cond { #then_expr } else { #else_expr }
        }
    }
}

/// Returns true iff the condition's token stream contains a `.get()` call,
/// using the same heuristic the component macro already uses elsewhere.
fn condition_is_reactive(cond: &Expr) -> bool {
    let tokens = cond.to_token_stream().to_string();
    // Crude but effective: look for the pattern `. get (` after stripping
    // whitespace. Matches `.get()` regardless of spacing.
    tokens.contains(".get()") || tokens.contains(". get ()")
}

fn emit_for(pat: &syn::Pat, iter: &Expr, body: &[UiNode]) -> TokenStream2 {
    let body_expr = emit_block_as_primitive(body);
    quote! {
        {
            let mut __c: ::std::vec::Vec<::framework_core::Primitive>
                = ::std::vec::Vec::new();
            for #pat in #iter {
                ::framework_core::ChildList::append_to(#body_expr, &mut __c);
            }
            __c
        }
    }
}

/// Emit a block of UI nodes as a single `Primitive`-producing expression.
/// Used for if/else/for branches where we need exactly one primitive value.
fn emit_block_as_primitive(nodes: &[UiNode]) -> TokenStream2 {
    match nodes.len() {
        0 => quote! { ::framework_core::view(::std::vec::Vec::new()) },
        1 => emit_node(&nodes[0]),
        _ => {
            let parts = nodes.iter().map(emit_node);
            quote! {
                ::framework_core::view({
                    let mut __c: ::std::vec::Vec<::framework_core::Primitive>
                        = ::std::vec::Vec::new();
                    #( ::framework_core::ChildList::append_to(#parts, &mut __c); )*
                    __c
                })
            }
        }
    }
}

// Silence "unused" complaints on items we may need later.
#[allow(dead_code)]
fn _unused(_: Span) {}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    /// Parse a `ui!` body and emit it, returning the emitted token stream
    /// as a string for substring assertions.
    fn parse_and_emit(input: TokenStream2) -> String {
        let ui: Ui = syn::parse2(input).expect("parse ui");
        emit(ui).to_string()
    }

    #[test]
    fn empty_ui_emits_empty_view() {
        let out = parse_and_emit(quote! {});
        assert!(out.contains("view"));
        assert!(out.contains("Vec :: new"));
    }

    #[test]
    fn text_with_children_block_emits_text_call() {
        let out = parse_and_emit(quote! { Text { "hello" } });
        assert!(out.contains(":: framework_core :: text"));
        assert!(out.contains("\"hello\""));
    }

    #[test]
    fn text_with_content_prop_emits_text_call() {
        let out = parse_and_emit(quote! { Text(content = "hi") });
        assert!(out.contains(":: framework_core :: text"));
        assert!(out.contains("\"hi\""));
    }

    #[test]
    fn user_component_dispatches_to_lower_macro() {
        let out = parse_and_emit(quote! { Counter(label = "x", value = score) });
        assert!(out.contains("counter !"));
    }

    #[test]
    fn user_component_string_literal_attr_gets_into() {
        let out = parse_and_emit(quote! { Counter(label = "x", value = score) });
        // `.into()` applied to the string literal attribute value.
        assert!(out.contains("\"x\" . into ()"));
    }

    #[test]
    fn user_component_non_literal_attr_passes_verbatim() {
        let out = parse_and_emit(quote! { Counter(value = score) });
        // No spurious .into() on `score`.
        assert!(!out.contains("score . into"));
    }

    #[test]
    fn user_component_with_children_emits_children_block() {
        let out = parse_and_emit(quote! {
            Card(title = "T") {
                Counter(value = s)
            }
        });
        assert!(out.contains("card !"));
        assert!(out.contains("children ="));
        assert!(out.contains("ChildList :: append_to"));
    }

    #[test]
    fn lowercase_component_name_is_recognized_too() {
        // Capitalization is cosmetic; shape is what matters.
        let out = parse_and_emit(quote! { mycomp(x = 1) });
        assert!(out.contains("mycomp !"));
    }

    #[test]
    fn bare_ident_is_passed_through_as_rust_expr() {
        // `extra` alone (no parens, no brace) — parses as a Rust
        // expression and goes through ChildList passthrough.
        let out = parse_and_emit(quote! { extra });
        // No `extra !` macro invocation should appear.
        assert!(!out.contains("extra !"));
    }

    #[test]
    fn reactive_if_rewrites_to_when() {
        let out = parse_and_emit(quote! {
            if flag.get() {
                Text { "on" }
            } else {
                Text { "off" }
            }
        });
        assert!(out.contains(":: framework_core :: when"));
        assert!(out.contains("move ||"));
    }

    #[test]
    fn non_reactive_if_emits_plain_if() {
        let out = parse_and_emit(quote! {
            if some_bool {
                Text { "on" }
            } else {
                Text { "off" }
            }
        });
        // Plain if, not when() — `.get()` is required to opt into reactivity.
        assert!(!out.contains(":: framework_core :: when"));
        assert!(out.contains("if some_bool"));
    }

    #[test]
    fn for_loop_emits_vec_collection() {
        let out = parse_and_emit(quote! {
            for n in items {
                Text { "x" }
            }
        });
        // For loops desugar to a Vec<Primitive>.
        assert!(out.contains("for n in items"));
        assert!(out.contains("ChildList :: append_to"));
    }

    #[test]
    fn else_if_chain_parses() {
        // Should parse without error; emitted shape contains nested
        // if/else.
        let out = parse_and_emit(quote! {
            if a.get() { Text { "a" } } else if b.get() { Text { "b" } } else { Text { "c" } }
        });
        assert!(out.contains(":: framework_core :: when"));
    }

    #[test]
    fn multiple_children_get_wrapped_in_children() {
        let out = parse_and_emit(quote! {
            Card {
                Counter(value = s)
                Counter(value = t)
            }
        });
        // Both counter calls appear, and the wrapping ChildList::append_to
        // ensures they flatten into Vec<Primitive>.
        let count = out.matches("counter !").count();
        assert_eq!(count, 2);
    }
}
