//! `ui!` proc-macro — a JSX-style DSL that desugars to component calls.
//!
//! Grammar (informal):
//!
//! ```text
//! ui!         := element*
//! element     := Name '(' prop_list? ')' children?
//!              | Name children
//!              | Name
//!              | rust_expr      (anything else parses as a Rust expression and
//!                                gets passed through to ChildList::append_to)
//! prop_list   := prop (',' prop)* ','?
//! prop        := ident '=' expr
//! children    := '{' element* '}'
//! ```
//!
//! Where `Name` is a capitalized identifier. Lowercase identifiers in the
//! same position parse as plain Rust expressions and pass through.
//!
//! Each parsed element emits one of:
//!  - `text(expr)` for `Text`
//!  - `button(label, on_click)` for `Button`
//!  - `view(children)` for `View`
//!  - `when(cond, then, otherwise)` for `When`
//!  - `name!(...)` for any other capitalized name (delegates to per-component
//!    macros generated by `#[component]`).
//!
//! Children blocks are wrapped in `children![...]` so they flatten via the
//! `ChildList` trait.

use proc_macro2::{Span, TokenStream as TokenStream2};
use quote::{quote, ToTokens};
use syn::parse::{Parse, ParseStream};
use syn::punctuated::Punctuated;
use syn::{braced, parenthesized, Expr, Ident, Token};

/// Top-level entry: a `ui! { ... }` invocation parses to a list of elements.
pub struct Ui {
    elements: Vec<UiNode>,
}

/// A single node in the UI tree. Either a component invocation we parsed,
/// or a raw Rust expression that goes through ChildList passthrough.
enum UiNode {
    Component {
        name: Ident,
        props: Vec<Prop>,
        children: Option<Vec<UiNode>>,
    },
    /// A `for` loop whose body is itself a UI block.
    For {
        pat: syn::Pat,
        iter: Expr,
        body: Vec<UiNode>,
    },
    /// An `if` / `if let` / `match`: parsed as a raw Rust expression with
    /// `ui!` recursively applied to each branch's contents.
    /// Branches always evaluate to a single UI node (or nothing for absent else).
    If {
        cond: Expr,
        then_body: Vec<UiNode>,
        else_body: Option<Vec<UiNode>>,
    },
    /// Arbitrary Rust expression to be flattened via ChildList.
    Expr(Expr),
}

struct Prop {
    name: Ident,
    value: Expr,
}

impl Parse for Ui {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let elements = parse_ui_nodes(input)?;
        Ok(Ui { elements })
    }
}

/// Parses a sequence of `UiNode`s until end-of-input.
fn parse_ui_nodes(input: ParseStream) -> syn::Result<Vec<UiNode>> {
    let mut out = Vec::new();
    while !input.is_empty() {
        out.push(parse_ui_node(input)?);
        // Optional commas between elements — purely cosmetic.
        let _ = input.parse::<Token![,]>();
    }
    Ok(out)
}

fn parse_ui_node(input: ParseStream) -> syn::Result<UiNode> {
    // Control flow keywords first.
    if input.peek(Token![if]) {
        return parse_if(input);
    }
    if input.peek(Token![for]) {
        return parse_for(input);
    }
    // Identifier followed by `(` or `{` is a component invocation:
    //   Foo()              Foo(props)              Foo { children }
    //   Foo(props) { children }
    // A bare `Foo` (no parens, no brace) is NOT a component — it parses
    // as a normal Rust expression. Capitalization is purely a convention;
    // the parser doesn't consult it.
    if input.peek(Ident) && next_is_component_invocation(input) {
        return parse_component(input);
    }
    // Fallback: parse a Rust expression. Goes through ChildList::append_to.
    let expr: Expr = input.parse()?;
    Ok(UiNode::Expr(expr))
}

/// Peeks past an identifier to see whether the *next* token is `(` or `{` —
/// the two shapes that mark a component invocation. We have to fork the
/// stream to do the lookahead.
fn next_is_component_invocation(input: ParseStream) -> bool {
    let fork = input.fork();
    if fork.parse::<Ident>().is_err() {
        return false;
    }
    fork.peek(syn::token::Paren) || fork.peek(syn::token::Brace)
}

fn parse_component(input: ParseStream) -> syn::Result<UiNode> {
    let name: Ident = input.parse()?;

    // Optional `(prop = expr, ...)` props list.
    let props = if input.peek(syn::token::Paren) {
        let content;
        parenthesized!(content in input);
        let pairs: Punctuated<Prop, Token![,]> = content.parse_terminated(Prop::parse, Token![,])?;
        pairs.into_iter().collect()
    } else {
        Vec::new()
    };

    // Optional `{ children }` block.
    let children = if input.peek(syn::token::Brace) {
        let content;
        braced!(content in input);
        Some(parse_ui_nodes(&content)?)
    } else {
        None
    };

    Ok(UiNode::Component { name, props, children })
}

fn parse_if(input: ParseStream) -> syn::Result<UiNode> {
    let _if_token: Token![if] = input.parse()?;
    // Parse the condition as a Rust expression. `Expr::parse_without_eager_brace`
    // stops the parser from consuming the trailing `{` as a struct-literal.
    let cond: Expr = Expr::parse_without_eager_brace(input)?;
    let then_content;
    braced!(then_content in input);
    let then_body = parse_ui_nodes(&then_content)?;

    let else_body = if input.peek(Token![else]) {
        let _: Token![else] = input.parse()?;
        // Allow chained `else if` by wrapping the rest as a single If node.
        if input.peek(Token![if]) {
            let nested = parse_if(input)?;
            Some(vec![nested])
        } else {
            let else_content;
            braced!(else_content in input);
            Some(parse_ui_nodes(&else_content)?)
        }
    } else {
        None
    };

    Ok(UiNode::If { cond, then_body, else_body })
}

fn parse_for(input: ParseStream) -> syn::Result<UiNode> {
    let _for_token: Token![for] = input.parse()?;
    let pat = syn::Pat::parse_single(input)?;
    let _in_token: Token![in] = input.parse()?;
    let iter: Expr = Expr::parse_without_eager_brace(input)?;
    let body_content;
    braced!(body_content in input);
    let body = parse_ui_nodes(&body_content)?;
    Ok(UiNode::For { pat, iter, body })
}

impl Parse for Prop {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let name: Ident = input.parse()?;
        let _: Token![=] = input.parse()?;
        let value: Expr = input.parse()?;
        Ok(Prop { name, value })
    }
}

// =============================================================================
// Emit
// =============================================================================

/// Top-level emit: produce a single expression that yields a `Primitive`.
/// If the `ui!` body has exactly one element, emit it directly. Otherwise
/// wrap in `view(children![...])`.
pub fn emit(ui: Ui) -> TokenStream2 {
    match ui.elements.len() {
        0 => quote! { ::framework_core::view(::std::vec::Vec::new()) },
        1 => emit_node(&ui.elements[0]),
        _ => {
            let kids = ui.elements.iter().map(emit_node);
            quote! {
                ::framework_core::view({
                    let mut __c: ::std::vec::Vec<::framework_core::Primitive>
                        = ::std::vec::Vec::new();
                    #( ::framework_core::ChildList::append_to(#kids, &mut __c); )*
                    __c
                })
            }
        }
    }
}

fn emit_node(node: &UiNode) -> TokenStream2 {
    match node {
        UiNode::Component { name, props, children } => emit_component(name, props, children.as_deref()),
        UiNode::If { cond, then_body, else_body } => emit_if(cond, then_body, else_body.as_deref()),
        UiNode::For { pat, iter, body } => emit_for(pat, iter, body),
        UiNode::Expr(e) => e.to_token_stream(),
    }
}

/// Emit a prop's value tokens. String literals get an implicit `.into()` so
/// `label = "Score"` can flow into a `String` field without `.to_string()`.
/// Other expressions pass through verbatim — we don't want generalized
/// .into() coercion because of inference fragility on non-literal types.
fn emit_attr_value(value: &Expr) -> TokenStream2 {
    if matches!(value, Expr::Lit(syn::ExprLit { lit: syn::Lit::Str(_), .. })) {
        quote! { #value.into() }
    } else {
        quote! { #value }
    }
}

/// Emit a component invocation. Primitives (Text/Button/View/When) dispatch
/// to free functions in framework_core; other names dispatch to per-component
/// `name!` macros generated by `#[component]`.
fn emit_component(name: &Ident, props: &[Prop], children: Option<&[UiNode]>) -> TokenStream2 {
    let lower = name.to_string().to_ascii_lowercase();
    match lower.as_str() {
        "text" => emit_text(props, children),
        "button" => emit_button(props, children),
        "view" => emit_view(props, children),
        "when" => emit_when(props, children),
        _ => emit_user(name, props, children),
    }
}

fn emit_text(props: &[Prop], children: Option<&[UiNode]>) -> TokenStream2 {
    // Text takes its content from either a `content` prop or a children
    // block. The children block is preferred when present.
    if let Some(kids) = children {
        // Single Rust expression preferred; if multi-item, concatenate via
        // a String build expression. Keep it simple: single-item only for now.
        match kids.len() {
            0 => quote! { ::framework_core::text("") },
            1 => {
                let e = emit_node(&kids[0]);
                quote! { ::framework_core::text(#e) }
            }
            _ => {
                let parts = kids.iter().map(emit_node);
                quote! {
                    ::framework_core::text({
                        let mut __s = ::std::string::String::new();
                        #( __s.push_str(&::std::string::ToString::to_string(&#parts)); )*
                        __s
                    })
                }
            }
        }
    } else {
        // No children block. Look for a `content` prop.
        if let Some(p) = props.iter().find(|p| p.name == "content") {
            let v = &p.value;
            quote! { ::framework_core::text(#v) }
        } else {
            quote! { ::framework_core::text("") }
        }
    }
}

fn emit_button(props: &[Prop], _children: Option<&[UiNode]>) -> TokenStream2 {
    let label = props
        .iter()
        .find(|p| p.name == "label")
        .map(|p| p.value.to_token_stream())
        .unwrap_or_else(|| quote! { "" });
    let on_click = props
        .iter()
        .find(|p| p.name == "on_click")
        .map(|p| p.value.to_token_stream())
        .unwrap_or_else(|| quote! { || {} });
    quote! { ::framework_core::button(#label, #on_click) }
}

fn emit_view(_props: &[Prop], children: Option<&[UiNode]>) -> TokenStream2 {
    let kids = children.unwrap_or(&[]);
    let parts = kids.iter().map(emit_node);
    quote! {
        ::framework_core::view({
            let mut __c: ::std::vec::Vec<::framework_core::Primitive>
                = ::std::vec::Vec::new();
            #( ::framework_core::ChildList::append_to(#parts, &mut __c); )*
            __c
        })
    }
}

fn emit_when(props: &[Prop], _children: Option<&[UiNode]>) -> TokenStream2 {
    let cond = props.iter().find(|p| p.name == "cond").map(|p| p.value.to_token_stream()).unwrap_or_else(|| quote! { || false });
    let then_e = props.iter().find(|p| p.name == "then").map(|p| p.value.to_token_stream()).unwrap_or_else(|| quote! { || ::framework_core::view(::std::vec::Vec::new()) });
    let other = props.iter().find(|p| p.name == "otherwise").map(|p| p.value.to_token_stream()).unwrap_or_else(|| quote! { || ::framework_core::view(::std::vec::Vec::new()) });
    quote! { ::framework_core::when(#cond, #then_e, #other) }
}

/// Emit a user-defined component invocation. Lowercases the name and calls
/// the per-component macro generated by `#[component]`. Children block (if
/// present) becomes the `children` prop, wrapped in `children![...]`.
fn emit_user(name: &Ident, props: &[Prop], children: Option<&[UiNode]>) -> TokenStream2 {
    let lower = Ident::new(&name.to_string().to_ascii_lowercase(), name.span());
    let prop_assignments = props.iter().map(|p| {
        let n = &p.name;
        let v = emit_attr_value(&p.value);
        quote! { #n = #v }
    });

    if let Some(kids) = children {
        let parts = kids.iter().map(emit_node);
        // Always emit children as a Vec<Primitive>. If the component expects
        // a different type, the user gets a type error at the call site —
        // intentional; we don't try to be polymorphic across children types
        // for user components in this first cut.
        quote! {
            #lower!(
                #(#prop_assignments,)*
                children = {
                    let mut __c: ::std::vec::Vec<::framework_core::Primitive>
                        = ::std::vec::Vec::new();
                    #( ::framework_core::ChildList::append_to(#parts, &mut __c); )*
                    __c
                }
            )
        }
    } else {
        quote! { #lower!( #(#prop_assignments),* ) }
    }
}

fn emit_if(cond: &Expr, then_body: &[UiNode], else_body: Option<&[UiNode]>) -> TokenStream2 {
    let then_expr = emit_block_as_primitive(then_body);
    let else_expr = match else_body {
        Some(body) => emit_block_as_primitive(body),
        None => quote! { ::framework_core::view(::std::vec::Vec::new()) },
    };

    // Reactivity heuristic: if the condition contains `.get()`, rewrite to
    // `when()`. Otherwise plain `if`. We use a textual scan over the
    // condition's token stream.
    if condition_is_reactive(cond) {
        quote! {
            ::framework_core::when(
                move || #cond,
                move || #then_expr,
                move || #else_expr,
            )
        }
    } else {
        quote! {
            if #cond { #then_expr } else { #else_expr }
        }
    }
}

/// Returns true iff the condition's token stream contains a `.get()` call,
/// using the same heuristic the component macro already uses elsewhere.
fn condition_is_reactive(cond: &Expr) -> bool {
    let tokens = cond.to_token_stream().to_string();
    // Crude but effective: look for the pattern `. get (` after stripping
    // whitespace. Matches `.get()` regardless of spacing.
    tokens.contains(".get()") || tokens.contains(". get ()")
}

fn emit_for(pat: &syn::Pat, iter: &Expr, body: &[UiNode]) -> TokenStream2 {
    let body_expr = emit_block_as_primitive(body);
    quote! {
        {
            let mut __c: ::std::vec::Vec<::framework_core::Primitive>
                = ::std::vec::Vec::new();
            for #pat in #iter {
                ::framework_core::ChildList::append_to(#body_expr, &mut __c);
            }
            __c
        }
    }
}

/// Emit a block of UI nodes as a single `Primitive`-producing expression.
/// Used for if/else/for branches where we need exactly one primitive value.
fn emit_block_as_primitive(nodes: &[UiNode]) -> TokenStream2 {
    match nodes.len() {
        0 => quote! { ::framework_core::view(::std::vec::Vec::new()) },
        1 => emit_node(&nodes[0]),
        _ => {
            let parts = nodes.iter().map(emit_node);
            quote! {
                ::framework_core::view({
                    let mut __c: ::std::vec::Vec<::framework_core::Primitive>
                        = ::std::vec::Vec::new();
                    #( ::framework_core::ChildList::append_to(#parts, &mut __c); )*
                    __c
                })
            }
        }
    }
}

// Silence "unused" complaints on items we may need later.
#[allow(dead_code)]
fn _unused(_: Span) {}
